Repository cmu-db/noisepage, pull requests merged in 2018-08, with the labels that each got.

#39 DataTable
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/common/logger.cpp
  src/common/statistics.cpp
  src/include/common/concurrent_bitmap.h
  src/include/common/concurrent_map.h
  src/include/common/container/bitmap.h
  src/include/common/container/concurrent_vector.h
  src/include/common/json_serializable.h
  src/include/common/logger.h
  src/include/common/macros.h
  src/include/common/object_pool.h
  src/include/common/statistics.h
  src/include/common/typedefs.h
  src/include/storage/data_table.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_utils.h
  src/include/storage/tuple_access_strategy.h
  src/include/util/string_util.h
  src/storage/data_table.cpp
  src/storage/storage_defs.cpp
  src/storage/tuple_access_strategy.cpp
  src/util/string_util.cpp
  test/include/storage/tuple_access_strategy_test_util.h
  test/storage/tuple_access_strategy_test.cpp
Labels: feature, ready-for-review

#48 Enable make lint on Travis.
  .travis.yml
Labels: infrastructure

#54 Add release builds to Travis.
  .travis.yml
  src/storage/data_table.cpp
Labels: infrastructure, ready-to-merge

#51 Documentation and Doxygen check
  .travis.yml
  Dockerfile
  cmake_modules/SetupCxxFlags.cmake
  script/installation/packages.sh
  src/include/common/concurrent_bitmap.h
  src/include/common/concurrent_map.h
  src/include/common/constants.h
  src/include/common/container/bitmap.h
  src/include/common/container/concurrent_vector.h
  src/include/common/logger.h
  src/include/common/macros.h
  src/include/common/object_pool.h
  src/include/common/statistics.h
  src/include/common/typedefs.h
  src/include/storage/data_table.h
  src/include/storage/storage_defs.h
  src/include/storage/tuple_access_strategy.h
  src/include/storage/varlen_pool.h
  src/include/util/string_util.h
  src/storage/storage_defs.cpp
  src/util/string_util.cpp
Labels: best-practice, infrastructure, ready-to-merge

#55 Update README.md
  README.md
Labels: infrastructure, ready-to-merge

#56 Modify jemalloc to be linked to the terrier_shared library
  cmake_modules/SetupCxxFlags.cmake
  cmake_modules/ThirdpartyToolchain.cmake
  src/CMakeLists.txt
Labels: bug, infrastructure, ready-for-review

#58 Remove logging and easylogging
  src/CMakeLists.txt
  src/common/logger.cpp
  src/include/common/logger.h
  src/main/terrier.cpp
  test/common/logger_test.cpp
  test/include/common/harness.h
  third_party/easylogging++/easylogging++.cc
  third_party/easylogging++/easylogging++.h
Labels: best-practice, ready-to-merge

#59 Remove FAKED_IN_TEST as it is no longer needed
  src/include/common/concurrent_bitmap.h
  src/include/common/container/bitmap.h
  src/include/common/macros.h
  src/include/common/object_pool.h
Labels: best-practice, ready-for-review

#64 Remove string_util
  src/include/util/string_util.h
  src/util/string_util.cpp
Labels: best-practice, ready-to-merge

#60 Remove stats
  src/common/statistics.cpp
  src/include/common/statistics.h
Labels: best-practice, ready-for-review

#67 disable jemalloc due to ASAN issue.
  cmake_modules/ThirdpartyToolchain.cmake
Labels: bug, infrastructure, ready-to-merge

#65 Enable ASAN on Travis.
  .travis.yml
  src/include/common/concurrent_bitmap.h
  src/include/common/container/bitmap.h
Labels: infrastructure, ready-for-review

#61 Add RawConcurrentBitmap::FirstUnsetPos, use it in TAS::Allocate
  src/include/common/concurrent_bitmap.h
  src/include/storage/tuple_access_strategy.h
  test/common/concurrent_bitmap_test.cpp
Labels: performance, ready-for-review

#69 Remove global functions
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/common/typedefs.h
  src/include/storage/storage_util.h
  src/include/storage/storage_utils.h
  src/include/storage/tuple_access_strategy.h
  src/include/storage/varlen_pool.h
  src/storage/data_table.cpp
  src/storage/tuple_access_strategy.cpp
  test/common/bitmap_test.cpp
  test/common/concurrent_bitmap_test.cpp
  test/common/object_pool_test.cpp
  test/include/common/test_util.h
  test/include/storage/tuple_access_strategy_test_util.h
  test/include/util/container_test_util.h
  test/include/util/multi_threaded_test_util.h
  test/include/util/storage_test_util.h
  test/include/util/tuple_access_strategy_test_util.h
  test/storage/tuple_access_strategy_test.cpp
  test/storage/varlen_pool_test.cpp
Labels: best-practice, ready-for-review

#72 Add DataTable unit tests
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/common/typedefs.h
  src/include/storage/data_table.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/transaction/transaction_util.h
  src/storage/data_table.cpp
  src/storage/storage_defs.cpp
  test/include/util/storage_test_util.h
  test/include/util/tuple_access_strategy_test_util.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/tuple_access_strategy_test.cpp
Labels: feature, ready-for-review

#75 Misc best practice fixes
  CMakeLists.txt
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/common/constants.h
  src/include/common/container/bitmap.h
  src/include/common/container/concurrent_bitmap.h
  src/include/common/container/concurrent_map.h
  src/include/common/container/concurrent_queue.h
  src/include/common/json_serializable.h
  src/include/common/macros.h
  src/include/common/object_pool.h
  src/include/common/spin_latch.h
  src/include/common/typedefs.h
  src/include/storage/data_table.h
  src/include/storage/storage_defs.h
  src/include/storage/tuple_access_strategy.h
  src/include/storage/varlen_pool.h
  src/main/terrier.cpp
  src/storage/data_table.cpp
  src/storage/tuple_access_strategy.cpp
  test/common/bitmap_test.cpp
  test/common/concurrent_bitmap_test.cpp
  test/common/object_pool_test.cpp
  test/include/util/multi_threaded_test_util.h
  test/include/util/storage_test_util.h
  test/include/util/tuple_access_strategy_test_util.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/storage/varlen_pool_test.cpp
Labels: best-practice, infrastructure

#76 Clang tidy fixes
  .clang-tidy
  build-support/run-clang-tidy.sh
  cmake_modules/FindTBB.cmake
  src/include/common/container/concurrent_bitmap.h
  src/include/common/json_serializable.h
  src/include/storage/storage_defs.h
Labels: infrastructure, ready-for-review

#77 TupleAccessStrategy benchmarks
  benchmark/include/util/storage_benchmark_util.h
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  test/include/util/storage_test_util.h
  test/include/util/tuple_access_strategy_test_util.h
  test/storage/tuple_access_strategy_test.cpp
Labels: performance, tests

#78 Require an explanatory message in PELOTON_ASSERT.
  src/include/common/macros.h
  src/include/storage/storage_defs.h
  src/storage/data_table.cpp
  test/include/util/multi_threaded_test_util.h
  test/include/util/storage_test_util.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
Labels: best-practice, ready-for-review

#80 Bugfix: bits_left should account for start_pos.
  src/include/common/container/concurrent_bitmap.h
Labels: bug, ready-to-merge

#81 Data Table insert benchmarks and performance fixes
  benchmark/include/util/storage_benchmark_util.h
  benchmark/storage/data_table_benchmark.cpp
  src/include/common/container/concurrent_bitmap.h
  src/include/common/object_pool.h
  src/include/storage/data_table.h
  src/include/storage/storage_defs.h
  src/include/storage/tuple_access_strategy.h
  src/storage/data_table.cpp
  src/storage/storage_defs.cpp
  src/storage/tuple_access_strategy.cpp
  test/include/util/storage_test_util.h
  test/storage/tuple_access_strategy_test.cpp
Labels: performance, ready-for-review, tests

#79 Beef up tests for bitmap, concurrent bitmap and tuple access strategy
  test/common/bitmap_test.cpp
  test/common/concurrent_bitmap_test.cpp
  test/include/util/container_test_util.h
  test/storage/tuple_access_strategy_test.cpp
Labels: performance, ready-for-review, tests

#84 Concurrent Bitmap speedup
  src/include/common/container/concurrent_bitmap.h
  src/include/storage/tuple_access_strategy.h
  test/common/concurrent_bitmap_test.cpp
Labels: performance, ready-for-review

#86 Add comments for concurrent data table tests.
  test/storage/data_table_concurrent_test.cpp
Labels: best-practice, ready-for-review

#87 Update spin_latch to use TBB spin_mutex
  src/include/common/spin_latch.h
Labels: performance, ready-for-review

#89 Adds a rw_latch implementation that wraps TBB's
  src/include/common/rw_latch.h
Labels: feature, ready-to-merge

#88 Concurrency Control
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/common/container/concurrent_map.h
  src/include/common/object_pool.h
  src/include/storage/data_table.h
  src/include/storage/storage_defs.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/storage/data_table.cpp
  src/storage/storage_defs.cpp
  test/CMakeLists.txt
  test/common/object_pool_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/transaction/CMakeLists.txt
  test/transaction/mvcc_test.cpp
Labels: feature, ready-to-merge

#90 Cleanup TAS tests
  benchmark/include/util/storage_benchmark_util.h
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  test/include/util/storage_test_util.h
  test/storage/tuple_access_strategy_test.cpp
Labels: best-practice, ready-to-merge, tests

#93 Boost filesystem
  Dockerfile
  cmake_modules/ThirdpartyToolchain.cmake
  script/installation/packages.sh
Labels: infrastructure, ready-to-merge

#94 Refactored MVCC anomaly tests
  test/include/util/storage_test_util.h
  test/transaction/mvcc_test.cpp
Labels: ready-to-merge, tests

#96 Enable clang-format on benchmark and test
  CMakeLists.txt
  benchmark/include/util/storage_benchmark_util.h
  build-support/run_clang_format.py
  test/include/util/storage_test_util.h
Labels: best-practice, ready-for-review

#101 Extended first writer wins logic for HasConflict
  src/include/storage/data_table.h
  src/include/storage/storage_defs.h
  src/storage/data_table.cpp
  test/storage/data_table_concurrent_test.cpp
  test/transaction/mvcc_test.cpp
Labels: bug, ready-to-merge, tests

#92 Debug logging (spdlog)
  src/CMakeLists.txt
  src/include/loggers/main_logger.h
  src/include/loggers/storage_logger.h
  src/loggers/main_logger.cpp
  src/loggers/storage_logger.cpp
  src/main/terrier.cpp
  test/include/util/test_harness.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  third_party/spdlog/async.h
  third_party/spdlog/async_logger.h
  third_party/spdlog/common.h
  third_party/spdlog/details/async_logger_impl.h
  third_party/spdlog/details/circular_q.h
  third_party/spdlog/details/console_globals.h
  third_party/spdlog/details/file_helper.h
  third_party/spdlog/details/fmt_helper.h
  third_party/spdlog/details/log_msg.h
  third_party/spdlog/details/logger_impl.h
  third_party/spdlog/details/mpmc_blocking_q.h
  third_party/spdlog/details/null_mutex.h
  third_party/spdlog/details/os.h
  third_party/spdlog/details/pattern_formatter.h
  third_party/spdlog/details/periodic_worker.h
  third_party/spdlog/details/registry.h
  third_party/spdlog/details/thread_pool.h
  third_party/spdlog/fmt/bundled/LICENSE.rst
  third_party/spdlog/fmt/bundled/colors.h
  third_party/spdlog/fmt/bundled/core.h
  third_party/spdlog/fmt/bundled/format-inl.h
  third_party/spdlog/fmt/bundled/format.h
  third_party/spdlog/fmt/bundled/locale.h
  third_party/spdlog/fmt/bundled/ostream.h
  third_party/spdlog/fmt/bundled/posix.h
  third_party/spdlog/fmt/bundled/printf.h
  third_party/spdlog/fmt/bundled/ranges.h
  third_party/spdlog/fmt/bundled/time.h
  third_party/spdlog/fmt/fmt.h
  third_party/spdlog/fmt/ostr.h
  third_party/spdlog/formatter.h
  third_party/spdlog/logger.h
  third_party/spdlog/sinks/android_sink.h
  third_party/spdlog/sinks/ansicolor_sink.h
  third_party/spdlog/sinks/base_sink.h
  third_party/spdlog/sinks/basic_file_sink.h
  third_party/spdlog/sinks/daily_file_sink.h
  third_party/spdlog/sinks/dist_sink.h
  third_party/spdlog/sinks/msvc_sink.h
  third_party/spdlog/sinks/null_sink.h
  third_party/spdlog/sinks/ostream_sink.h
  third_party/spdlog/sinks/rotating_file_sink.h
  third_party/spdlog/sinks/sink.h
  third_party/spdlog/sinks/stdout_color_sinks.h
  third_party/spdlog/sinks/stdout_sinks.h
  third_party/spdlog/sinks/syslog_sink.h
  third_party/spdlog/sinks/wincolor_sink.h
  third_party/spdlog/spdlog.h
  third_party/spdlog/tweakme.h
  third_party/spdlog/version.h
Labels: feature, ready-for-review

#103 Add tests for ProjectedRow, DeltaRecord and StorageUtil
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
Labels: ready-for-review, tests

#98 Large transaction tests and associated DataTable and CC bug fixes
  src/include/common/object_pool.h
  src/include/common/spin_latch.h
  src/include/common/typedefs.h
  src/include/storage/data_table.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/storage/data_table.cpp
  src/storage/storage_defs.cpp
  test/include/util/multi_threaded_test_util.h
  test/storage/data_table_test.cpp
  test/transaction/large_transaction_test.cpp
  test/transaction/mvcc_test.cpp
Labels: bug, ready-to-merge, tests

#104 Benchmarks refactor
  benchmark/include/util/storage_benchmark_util.h
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  cmake_modules/FindClangTools.cmake
Labels: best-practice, ready-to-merge, tests

#115 Garbage Collection
  src/include/common/typedefs.h
  src/include/loggers/transaction_logger.h
  src/include/storage/data_table.h
  src/include/storage/garbage_collector.h
  src/include/storage/storage_defs.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/loggers/transaction_logger.cpp
  src/main/terrier.cpp
  src/storage/garbage_collector.cpp
  test/include/util/test_harness.h
  test/storage/garbage_collector_test.cpp
  test/transaction/large_transaction_test.cpp
  test/transaction/mvcc_test.cpp
Labels: feature, ready-for-review

#118 Cmake fixes for linking issues
  CMakeLists.txt
  benchmark/CMakeLists.txt
  cmake_modules/BuildUtils.cmake
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/util/test_main.cpp
Labels: bug, infrastructure, ready-to-merge

#116 LargeTransactionTest framework refactor + large randomized GC tests
  src/include/transaction/transaction_manager.h
  src/storage/garbage_collector.cpp
  test/include/util/storage_test_util.h
  test/include/util/transaction_test_util.h
  test/transaction/garbage_collection_test.cpp
  test/transaction/large_transaction_test.cpp
  test/util/test_main.cpp
  test/util/transaction_test_util.cpp
Labels: ready-for-review, tests

#120 Fix CMP0068 CMake warning on Mac
  CMakeLists.txt
  cmake_modules/SetupCxxFlags.cmake
  cmake_modules/ThirdpartyToolchain.cmake
  cmake_modules/san-config.cmake
Labels: infrastructure, ready-to-merge

#121 Fix typo in the storage and transaction logger macro definitions
  src/include/loggers/storage_logger.h
  src/include/loggers/transaction_logger.h
Labels: bug, infrastructure, ready-to-merge

#122 Revert to arrow behavior in run-test.sh
  build-support/run-test.sh
Labels: bug, infrastructure, ready-to-merge

#119 Add thread pool to Google Tests to avoid constant creation and reaping of threads
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  test/common/concurrent_bitmap_test.cpp
  test/common/object_pool_test.cpp
  test/include/util/random_test_util.h
  test/include/util/storage_test_util.h
  test/include/util/test_thread_pool.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/storage/varlen_pool_test.cpp
  test/util/transaction_test_util.cpp
Labels: bug, feature, ready-to-merge

#123 Break StorageDef, move some implementation to .cpp, and documentation for testing framework
  benchmark/storage/data_table_benchmark.cpp
  src/include/storage/data_table.h
  src/include/storage/delta_record.h
  src/include/storage/garbage_collector.h
  src/include/storage/record_buffer.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/storage/tuple_access_strategy.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/storage/data_table.cpp
  src/storage/delta_record.cpp
  src/storage/garbage_collector.cpp
  src/storage/storage_util.cpp
  src/storage/tuple_access_strategy.cpp
  src/transaction/transaction_manager.cpp
  test/include/util/storage_test_util.h
  test/include/util/transaction_test_util.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/large_transaction_test.cpp
  test/transaction/large_transaction_test_with_gc.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
Labels: best-practice, ready-for-review

#124 Allow external iteration control on benchmarks
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
Labels: infrastructure, ready-to-merge

#125 Revisit all the TODOs; remove magic constant; minor reorganization.
  src/include/common/constants.h
  src/include/common/object_pool.h
  src/include/common/typedefs.h
  src/include/storage/data_table.h
  src/include/storage/record_buffer.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/storage/tuple_access_strategy.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/storage/data_table.cpp
  src/storage/delta_record.cpp
  src/storage/storage_util.cpp
  src/storage/tuple_access_strategy.cpp
  src/transaction/transaction_manager.cpp
  test/common/object_pool_test.cpp
  test/include/util/storage_test_util.h
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/large_transaction_test_with_gc.cpp
  test/util/transaction_test_util.cpp
Labels: best-practice, ready-to-merge

#126 Refactor, documentation
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/common/constants.h
  src/include/common/container/bitmap.h
  src/include/common/container/concurrent_bitmap.h
  src/include/common/container/concurrent_map.h
  src/include/common/container/concurrent_queue.h
  src/include/common/container/concurrent_vector.h
  src/include/common/macros.h
  src/include/common/object_pool.h
  src/include/common/rw_latch.h
  src/include/common/spin_latch.h
  src/include/storage/data_table.h
  src/include/storage/delta_record.h
  src/include/storage/garbage_collector.h
  src/include/storage/record_buffer.h
  src/include/storage/storage_defs.h
  src/include/storage/tuple_access_strategy.h
  src/include/storage/varlen_pool.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/storage/data_table.cpp
  src/storage/delta_record.cpp
  src/storage/garbage_collector.cpp
  src/storage/storage_util.cpp
  src/transaction/transaction_manager.cpp
  test/common/bitmap_test.cpp
  test/include/util/random_test_util.h
  test/include/util/storage_test_util.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/large_garbage_collector_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
Labels: best-practice, ready-for-review

#130 Define TransactionQueue to be backed by std::list, add TRACE logging to GC
  src/include/storage/garbage_collector.h
  src/include/transaction/transaction_defs.h
  src/include/transaction/transaction_manager.h
  src/storage/garbage_collector.cpp
  src/transaction/transaction_manager.cpp
Labels: best-practice, performance, ready-to-merge

#131 Add small-scale GC tests and optimization for read-only txns
  src/include/storage/garbage_collector.h
  src/storage/garbage_collector.cpp
  test/storage/garbage_collector_test.cpp
  test/transaction/mvcc_test.cpp
Labels: performance, ready-to-merge, tests

#128 Alignment of ProjectedRow & Layout optimization
  benchmark/include/util/storage_benchmark_util.h
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/common/allocator.h
  src/include/common/container/bitmap.h
  src/include/common/container/concurrent_bitmap.h
  src/include/common/object_pool.h
  src/include/storage/data_table.h
  src/include/storage/delta_record.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/storage/tuple_access_strategy.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/storage/data_table.cpp
  src/storage/delta_record.cpp
  src/storage/storage_util.cpp
  src/storage/tuple_access_strategy.cpp
  src/transaction/transaction_manager.cpp
  test/common/bitmap_test.cpp
  test/include/util/storage_test_util.h
  test/include/util/transaction_test_util.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
Labels: performance, ready-to-merge

#117 Fix clang-format for .cpp files
  CMakeLists.txt
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  benchmark/util/benchmark_main.cpp
  build-support/run_clang_format.py
  src/loggers/main_logger.cpp
  src/loggers/storage_logger.cpp
  src/loggers/transaction_logger.cpp
  src/main/terrier.cpp
  src/storage/data_table.cpp
  src/storage/delta_record.cpp
  src/storage/garbage_collector.cpp
  src/storage/storage_util.cpp
  src/storage/tuple_access_strategy.cpp
  src/transaction/transaction_manager.cpp
  test/common/bitmap_test.cpp
  test/common/concurrent_bitmap_test.cpp
  test/common/object_pool_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/large_garbage_collector_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/storage/varlen_pool_test.cpp
  test/transaction/large_transaction_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
Labels: best-practice, ready-to-merge

#136 tweak test numbers
  test/common/bitmap_test.cpp
  test/common/concurrent_bitmap_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/large_garbage_collector_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/large_transaction_test.cpp
Labels: best-practice, ready-to-merge, tests

#139 Switch from libjsoncpp to nlohmann::json.
  Dockerfile
  cmake_modules/FindJsoncpp.cmake
  cmake_modules/ThirdpartyToolchain.cmake
  script/installation/packages.sh
  src/include/common/json_serializable.h
  third_party/nlohmann/json.hpp
  third_party/versions.txt
Labels: infrastructure, ready-for-review

#143 Strong typedef col_id to avoid confusion. Associated minor fixes
  benchmark/include/util/storage_benchmark_util.h
  src/include/common/typedefs.h
  src/include/storage/data_table.h
  src/include/storage/delta_record.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/storage/tuple_access_strategy.h
  src/include/transaction/transaction_util.h
  src/storage/data_table.cpp
  src/storage/delta_record.cpp
  src/storage/storage_util.cpp
  src/storage/tuple_access_strategy.cpp
  test/include/util/storage_test_util.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
Labels: best-practice, ready-to-merge

#148 num_iterations adjustment on mvcc and gc tests
  test/storage/garbage_collector_test.cpp
  test/transaction/mvcc_test.cpp
Labels: ready-to-merge, tests

#127 Make Object Pool Size and Reuse Limit Tunable
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/common/object_pool.h
  test/common/object_pool_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/large_garbage_collector_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/large_transaction_test.cpp
  test/transaction/mvcc_test.cpp
Labels: feature, ready-to-merge, tests

#151 Rename rw latch to shared latch
  src/include/common/shared_latch.h
  src/include/transaction/transaction_manager.h
  src/transaction/transaction_manager.cpp
Labels: best-practice, ready-to-merge

#150 ScopedTimer
  src/include/common/scoped_timer.h
Labels: feature, ready-to-merge

#149 Switch TransactionQueue from a std::queue to a std::forward_list.
  src/include/transaction/transaction_defs.h
  src/storage/garbage_collector.cpp
  src/transaction/transaction_manager.cpp
Labels: performance, ready-to-merge

#154 Remove ConcurrentVector from DataTable
  benchmark/storage/data_table_benchmark.cpp
  src/include/storage/data_table.h
  src/storage/data_table.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
Labels: feature, performance, ready-for-review
