Repository cmu-db/noisepage, pull requests merged in 2018-09, with the labels that each got.

#155 Spdlog info
  third_party/versions.txt
Labels: best-practice, infrastructure, ready-to-merge

#158 Document and enforce the alignment assumption in RawConcurrentBitmap.
  src/include/common/container/concurrent_bitmap.h
Labels: best-practice, ready-for-review

#107 Performance counters
  CMakeLists.txt
  benchmark/storage/data_table_benchmark.cpp
  src/include/common/json.h
  src/include/common/macros.h
  src/include/common/performance_counter.h
  src/include/common/stat_registry.h
  src/include/storage/data_table.h
  src/main/terrier.cpp
  src/storage/data_table.cpp
  test/common/performance_counter_test.cpp
  test/common/stat_registry_test.cpp
  test/include/util/test_harness.h
Labels: feature, ready-for-review

#159 Add micro benchmarks into Jenkins configuration
  Jenkinsfile
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, ready-to-merge, tests

#160 TypeId enum class from Peloton
  src/include/type/type_id.h
  src/include/type/type_util.h
Labels: feature, ready-to-merge

#161 Refactor BlockLayout constructor to take single argument
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/storage/storage_defs.h
  src/main/terrier.cpp
  test/include/util/storage_test_util.h
Labels: best-practice, ready-for-review

#164 Add DataTable read benchmark
  benchmark/storage/data_table_benchmark.cpp
Labels: ready-for-review, tests

#165 Micro benchmark changes
  script/micro_bench/cpu_lib.py
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, tests

#166 #141 - New scenarios for large_transaction_test (& w/ GC)
  test/storage/large_garbage_collector_test.cpp
  test/transaction/large_transaction_test.cpp
Labels: tests

#162 Write Ahead Log
  benchmark/storage/data_table_benchmark.cpp
  src/include/common/allocator.h
  src/include/common/container/bitmap.h
  src/include/common/container/concurrent_bitmap.h
  src/include/common/container/concurrent_queue.h
  src/include/common/macros.h
  src/include/common/shared_latch.h
  src/include/common/spin_latch.h
  src/include/common/typedefs.h
  src/include/storage/data_table.h
  src/include/storage/projected_row.h
  src/include/storage/record_buffer.h
  src/include/storage/storage_defs.h
  src/include/storage/tuple_access_strategy.h
  src/include/storage/undo_record.h
  src/include/storage/write_ahead_log/log_io.h
  src/include/storage/write_ahead_log/log_manager.h
  src/include/storage/write_ahead_log/log_record.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/main/terrier.cpp
  src/storage/garbage_collector.cpp
  src/storage/projected_row.cpp
  src/storage/record_buffer.cpp
  src/storage/storage_util.cpp
  src/storage/write_ahead_log/log_io.cpp
  src/storage/write_ahead_log/log_manager.cpp
  src/transaction/transaction_manager.cpp
  test/include/util/storage_test_util.h
  test/include/util/transaction_test_util.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/large_garbage_collector_test.cpp
  test/storage/log_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/large_transaction_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
Labels: feature, ready-to-merge

#170 Update LLVM_DIR path for LLVM@6 after LLVM 7's release
  .travis.yml
Labels: bug, infrastructure, ready-for-review

#169 Added simple Column and Schema classes
  src/include/catalog/schema.h
  src/include/common/typedefs.h
  src/include/type/type_util.h
Labels: feature, ready-to-merge

#171 Fix for GC contending with TM's Rollback()
  src/include/storage/garbage_collector.h
  src/include/storage/undo_record.h
  src/storage/data_table.cpp
  src/storage/garbage_collector.cpp
  src/transaction/transaction_manager.cpp
  test/storage/garbage_collector_test.cpp
Labels: bug, ready-to-merge

#167 #141 - New scenarios for large_transaction_test (& w/ GC)
  test/storage/large_garbage_collector_test.cpp
  test/transaction/large_transaction_test.cpp
Labels: ready-to-merge, tests

#176 Quick fix for stage write when logging is turned off
  src/storage/record_buffer.cpp
  src/transaction/transaction_manager.cpp
Labels: bug, ready-for-review

#178 Fix typo
  src/include/common/container/bitmap.h
  src/include/common/container/concurrent_bitmap.h
  src/include/common/macros.h
  src/include/storage/projected_row.h
  src/include/storage/tuple_access_strategy.h
  src/include/storage/undo_record.h
  src/include/storage/write_ahead_log/log_record.h
Labels: best-practice, ready-to-merge

#174 Delete() added to DataTable
  benchmark/include/util/storage_benchmark_util.h
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/common/macros.h
  src/include/storage/data_table.h
  src/include/storage/projected_row.h
  src/include/storage/record_buffer.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/storage/tuple_access_strategy.h
  src/storage/data_table.cpp
  src/storage/projected_row.cpp
  src/storage/record_buffer.cpp
  src/storage/storage_util.cpp
  src/storage/tuple_access_strategy.cpp
  src/transaction/transaction_manager.cpp
  test/include/util/storage_test_util.h
  test/storage/garbage_collector_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/mvcc_test.cpp
Labels: feature, ready-to-merge

#182 Micro bench updates
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, ready-for-review
