Repository cmu-db/noisepage, pull requests merged in 2018-10, with the labels that each got.

#185 Add benchmarks for GC unlinking and deallocating
  benchmark/storage/garbage_collector_benchmark.cpp
  benchmark/util/benchmark_main.cpp
  script/micro_bench/run_micro_bench.py
Labels: ready-for-review, tests

#187 column access API
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/storage/block_layout.h
  src/include/storage/data_table.h
  src/include/storage/projected_columns.h
  src/include/storage/projected_row.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/storage/tuple_access_strategy.h
  src/include/storage/undo_record.h
  src/include/storage/write_ahead_log/log_record.h
  src/include/transaction/transaction_context.h
  src/storage/block_layout.cpp
  src/storage/data_table.cpp
  src/storage/projected_columns.cpp
  src/storage/projected_row.cpp
  src/storage/storage_util.cpp
  src/storage/tuple_access_strategy.cpp
  src/storage/write_ahead_log/log_manager.cpp
  src/transaction/transaction_manager.cpp
  test/include/util/storage_test_util.h
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/large_transaction_test.cpp
Labels: feature, ready-to-merge

#183 Travis/Jenkins trigger support
  .travis.yml
  Jenkinsfile
  cmake_modules/CoverallsGenerateGcov.cmake
Labels: infrastructure, ready-for-review

#186 SqlTable
  src/include/catalog/schema.h
  src/include/storage/block_layout.h
  src/include/storage/projected_columns.h
  src/include/storage/projected_row.h
  src/include/storage/sql_table.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/type/type_id.h
  src/include/type/type_util.h
  src/storage/data_table.cpp
  src/storage/projected_columns.cpp
  src/storage/projected_row.cpp
  src/storage/sql_table.cpp
  src/storage/storage_util.cpp
  test/include/util/catalog_test_util.h
  test/include/util/storage_test_util.h
  test/storage/storage_util_test.cpp
Labels: feature, ready-to-merge

#201 Deadlock bug fix
  src/include/storage/write_ahead_log/log_manager.h
  src/storage/write_ahead_log/log_manager.cpp
Labels: bug, ready-to-merge

#205 Shorten LogManager's critical section
  src/storage/write_ahead_log/log_manager.cpp
Labels: performance, ready-for-review

#204 Micro bench updates - allow higher performance
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, ready-to-merge

#210 TransactionManager performance fix
  src/transaction/transaction_manager.cpp
Labels: performance, ready-to-merge

#214 back out the main point of #183
  .travis.yml
  Jenkinsfile
Labels: infrastructure, ready-to-merge

#217 Extend critical section in commit to fix race condition
  src/transaction/transaction_manager.cpp
Labels: bug, ready-to-merge

#218 Micro bench updates
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, ready-to-merge

#221 read-only transaction optimization
  src/include/transaction/transaction_manager.h
  src/transaction/transaction_manager.cpp
Labels: performance, ready-for-review

#222 Documentation cleanup
  src/include/storage/tuple_access_strategy.h
Labels: best-practice, ready-to-merge

#219 codecov on Travis
  .travis.yml
  CMakeLists.txt
  cmake_modules/Coveralls.cmake
  cmake_modules/CoverallsClear.cmake
  cmake_modules/CoverallsGenerateGcov.cmake
Labels: infrastructure, ready-for-review

#226 Replace Coveralls badge with Codecov badge
  README.md
Labels: infrastructure, ready-to-merge

#180 Logical expressions and Values
  src/include/common/hash_util.h
  src/include/common/typedefs.h
  src/include/parser/expression/abstract_expression.h
  src/include/parser/expression/aggregate_expression.h
  src/include/parser/expression/case_expression.h
  src/include/parser/expression/comparison_expression.h
  src/include/parser/expression/conjunction_expression.h
  src/include/parser/expression/constant_value_expression.h
  src/include/parser/expression/function_expression.h
  src/include/parser/expression/operator_expression.h
  src/include/parser/expression/parameter_value_expression.h
  src/include/parser/expression/star_expression.h
  src/include/parser/expression/subquery_expression.h
  src/include/parser/expression/tuple_value_expression.h
  src/include/parser/expression_defs.h
  src/include/parser/parameter.h
  src/include/type/type_util.h
  src/include/type/value.h
  src/include/type/value_factory.h
  test/CMakeLists.txt
  test/parser/CMakeLists.txt
  test/parser/expression_test.cpp
  test/type/CMakeLists.txt
  test/type/value_type_test.cpp
Labels: feature, in-progress
