Repository cmu-db/noisepage, pull requests merged in 2018-11, with the labels that each got.

#228 Fix object pool exceptions
  src/include/common/object_pool.h
Labels: bug, ready-for-review

#224 Stop serializing commit record for read-only transactions
  src/include/storage/write_ahead_log/log_record.h
  src/storage/write_ahead_log/log_manager.cpp
  src/transaction/transaction_manager.cpp
  test/storage/log_test.cpp
Labels: feature, in-progress

#238 Reorganize strong typedefs to have namespaces
  benchmark/include/util/transaction_benchmark_util.h
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  benchmark/util/transaction_benchmark_util.cpp
  src/include/catalog/catalog_defs.h
  src/include/catalog/schema.h
  src/include/common/allocator.h
  src/include/common/container/bitmap.h
  src/include/common/container/concurrent_bitmap.h
  src/include/common/container/concurrent_map.h
  src/include/common/hash_util.h
  src/include/common/object_pool.h
  src/include/common/strong_typedef.h
  src/include/storage/garbage_collector.h
  src/include/storage/projected_columns.h
  src/include/storage/projected_row.h
  src/include/storage/record_buffer.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/storage/undo_record.h
  src/include/storage/varlen_pool.h
  src/include/storage/write_ahead_log/log_manager.h
  src/include/storage/write_ahead_log/log_record.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_defs.h
  src/include/transaction/transaction_manager.h
  src/include/transaction/transaction_util.h
  src/include/type/type_id.h
  src/include/type/type_util.h
  src/include/type/value.h
  src/include/type/value_factory.h
  src/main/terrier.cpp
  src/storage/data_table.cpp
  src/storage/garbage_collector.cpp
  test/include/util/catalog_test_util.h
  test/include/util/storage_test_util.h
  test/include/util/transaction_test_util.h
  test/parser/expression_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/log_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/mvcc_test.cpp
  test/type/value_type_test.cpp
  test/util/transaction_test_util.cpp
Labels: best-practice, ready-for-review

#236 rename table latch
  src/include/transaction/transaction_manager.h
  src/transaction/transaction_manager.cpp
Labels: best-practice, ready-to-merge

#243 Fix for #237 - clang-tidy show usage
  build-support/run-clang-tidy.py
  build-support/run_clang_tidy_extra.py
Labels: best-practice, infrastructure, ready-to-merge

#253 Xcode10 for Travis and Jenkins, LLVM_DIR change for Homebrew
  .travis.yml
  Jenkinsfile
  cmake_modules/CompilerInfo.cmake
Labels: infrastructure, ready-to-merge

#254 Replace running_txns map with unordered_set
  src/include/transaction/transaction_manager.h
  src/transaction/transaction_manager.cpp
Labels: performance, ready-for-review

#246 Port BwTree from Peloton
  CMakeLists.txt
  benchmark/storage/bwtree_benchmark.cpp
  benchmark/util/benchmark_main.cpp
  src/CMakeLists.txt
  src/include/loggers/index_logger.h
  src/loggers/index_logger.cpp
  src/main/terrier.cpp
  test/include/util/bwtree_test_util.h
  test/include/util/test_harness.h
  test/storage/bwtree_test.cpp
  third_party/.clang-tidy
  third_party/bwtree/atomic_stack.h
  third_party/bwtree/bloom_filter.h
  third_party/bwtree/bwtree.cpp
  third_party/bwtree/bwtree.h
  third_party/bwtree/sorted_small_set.h
Labels: feature, ready-to-merge, tests

#256 Fix assertion failure in Terrier main
  src/main/terrier.cpp
Labels: bug, ready-for-review
