Repository cmu-db/noisepage, pull requests merged in 2019-05, with the labels that each got.

#369 Add short circuit on Select
  src/storage/data_table.cpp
Labels: performance, ready-to-merge

#364 Remove the commit latch
  src/include/common/gate.h
  src/include/transaction/transaction_manager.h
  src/transaction/transaction_manager.cpp
Labels: feature, performance, ready-for-review

#372 Fix doxygen problem
  src/include/common/gate.h
Labels: bug, ready-to-merge

#373 clang-tidy heartbeat
  build-support/run-clang-tidy.py
Labels: infrastructure, ready-to-merge

#260 Catalog
  benchmark/CMakeLists.txt
  benchmark/catalog/CMakeLists.txt
  benchmark/catalog/catalog_benchmark.cpp
  benchmark/util/benchmark_main.cpp
  src/catalog/attr_def_handle.cpp
  src/catalog/attribute_handle.cpp
  src/catalog/catalog.cpp
  src/catalog/class_handle.cpp
  src/catalog/database_handle.cpp
  src/catalog/namespace_handle.cpp
  src/catalog/settings_handle.cpp
  src/catalog/table_handle.cpp
  src/catalog/tablespace_handle.cpp
  src/catalog/type_handle.cpp
  src/include/catalog/attr_def_handle.h
  src/include/catalog/attribute_handle.h
  src/include/catalog/catalog.h
  src/include/catalog/catalog_defs.h
  src/include/catalog/catalog_entry.h
  src/include/catalog/catalog_sql_table.h
  src/include/catalog/class_handle.h
  src/include/catalog/database_handle.h
  src/include/catalog/namespace_handle.h
  src/include/catalog/schema.h
  src/include/catalog/settings_handle.h
  src/include/catalog/table_handle.h
  src/include/catalog/tablespace_handle.h
  src/include/catalog/type_handle.h
  src/include/common/exception.h
  src/include/common/settings.h
  src/include/loggers/catalog_logger.h
  src/include/storage/sql_table.h
  src/include/storage/storage_util.h
  src/include/type/transient_value.h
  src/include/type/transient_value_factory.h
  src/include/type/transient_value_peeker.h
  src/loggers/catalog_logger.cpp
  src/main/terrier.cpp
  src/storage/sql_table.cpp
  src/storage/storage_util.cpp
  test/CMakeLists.txt
  test/catalog/CMakeLists.txt
  test/catalog/attribute_handle_test.cpp
  test/catalog/catalog_test.cpp
  test/catalog/database_handle_test.cpp
  test/catalog/namespace_handle_test.cpp
  test/catalog/settings_handle_test.cpp
  test/catalog/table_handle_test.cpp
  test/catalog/tablespace_handle_test.cpp
  test/catalog/type_handle_test.cpp
  test/include/util/test_harness.h
  test/parser/parser_test.cpp
  test/type/transient_value_test.cpp
Labels: feature, in-progress

#375 Rename CreateProjectedRowInitializer to Create
  benchmark/include/util/transaction_benchmark_util.h
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  benchmark/util/transaction_benchmark_util.cpp
  src/include/storage/index/index_metadata.h
  src/include/storage/projected_row.h
  src/include/storage/sql_table.h
  src/storage/projected_row.cpp
  test/common/stat_registry_test.cpp
  test/include/util/storage_test_util.h
  test/include/util/transaction_test_util.h
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
Labels: best-practice, ready-for-review

#368 Fix wrong cmake "if" usage in FindPOSTGRES
  cmake_modules/FindPOSTGRES.cmake
Labels: bug, ready-for-review

#378 Prevent Travis from killing clang-tidy
  build-support/run-clang-tidy.py
Labels: infrastructure, ready-for-review

#382 Move clang-tidy to Jenkins
  .travis.yml
  Jenkinsfile
Labels: infrastructure, ready-to-merge

#356 BwTreeIndex: Add visibility logic, abort and deferred delete logic, descending and limit scans
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/include/storage/data_table.h
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/index.h
  src/include/storage/index/index_metadata.h
  src/include/storage/storage_defs.h
  src/include/storage/tuple_access_strategy.h
  src/storage/block_layout.cpp
  src/storage/data_table.cpp
  src/storage/tuple_access_strategy.cpp
  src/transaction/transaction_manager.cpp
  test/include/util/storage_test_util.h
  test/storage/bwtree_index_test.cpp
  test/storage/bwtree_key_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/mvcc_test.cpp
Labels: feature, ready-to-merge

#376 Extend parser CREATE INDEX
  src/include/parser/create_statement.h
  src/include/planner/plannodes/create_index_plan_node.h
  src/parser/postgresparser.cpp
  test/parser/parser_test.cpp
Labels: feature, ready-to-merge

#385 Add dedicated GC thread class for tests and main to use.
  benchmark/storage/logging_benchmark.cpp
  benchmark/transaction/large_transaction_benchmark.cpp
  src/include/storage/garbage_collector_thread.h
  test/storage/bwtree_index_test.cpp
  test/storage/large_garbage_collector_test.cpp
  test/storage/log_test.cpp
Labels: feature, ready-to-merge

#389 Fix bulk insert for InsertPlanNode
  src/include/planner/plannodes/insert_plan_node.h
  src/planner/plannodes/insert_plan_node.cpp
  test/planner/plan_node_json_test.cpp
Labels: feature, ready-for-review

#336 DBMain and Settings Manager
  CMakeLists.txt
  apidoc/Doxyfile.in
  benchmark/util/benchmark_main.cpp
  build-support/clang_format_exclusions.txt
  src/catalog/settings_handle.cpp
  src/include/catalog/catalog_defs.h
  src/include/common/action_context.h
  src/include/common/exception.h
  src/include/common/object_pool.h
  src/include/loggers/loggers_util.h
  src/include/loggers/settings_logger.h
  src/include/loggers/type_logger.h
  src/include/main/db_main.h
  src/include/settings/CPPLINT.cfg
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_common.h
  src/include/settings/settings_defs.h
  src/include/settings/settings_manager.h
  src/include/settings/settings_param.h
  src/include/transaction/transaction_util.h
  src/include/type/transient_value.h
  src/loggers/settings_logger.cpp
  src/loggers/type_logger.cpp
  src/main/db_main.cpp
  src/main/terrier.cpp
  src/settings/README.md
  src/settings/doc/callback_flow.png
  src/settings/settings_callbacks.cpp
  src/settings/settings_manager.cpp
  test/CMakeLists.txt
  test/catalog/attribute_handle_test.cpp
  test/catalog/catalog_test.cpp
  test/catalog/database_handle_test.cpp
  test/catalog/namespace_handle_test.cpp
  test/catalog/settings_handle_test.cpp
  test/catalog/table_handle_test.cpp
  test/catalog/tablespace_handle_test.cpp
  test/catalog/type_handle_test.cpp
  test/include/util/test_harness.h
  test/include/util/transaction_test_util.h
  test/network/network_test.cpp
  test/settings/CMakeLists.txt
  test/settings/settings_test.cpp
  test/storage/bwtree_index_test.cpp
  test/storage/bwtree_key_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/sql_table_test.cpp
  test/transaction/deferred_actions_test.cpp
  test/transaction/mvcc_test.cpp
  test/type/transient_value_test.cpp
  test/util/transaction_test_util.cpp
Labels: class-project, feature, ready-to-merge

#354 Fix typo in network README
  src/network/README
  src/network/README.md
Labels: best-practice, ready-to-merge

#394 Add ManagedPointer
  src/include/common/managed_pointer.h
Labels: best-practice, ready-for-review

#396 ManagedPointer Test Cases
  test/common/managed_pointer_test.cpp
Labels: ready-for-review, tests
