Repository cmu-db/noisepage, pull requests merged in 2019-04, with the labels that each got.

#331 Update benchmark lookback and threshold
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, ready-for-review, tests

#314 Index keys and builder
  benchmark/include/util/transaction_benchmark_util.h
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  benchmark/util/transaction_benchmark_util.cpp
  src/include/catalog/catalog_defs.h
  src/include/catalog/schema.h
  src/include/common/macros.h
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/compact_ints_key.h
  src/include/storage/index/generic_key.h
  src/include/storage/index/index.h
  src/include/storage/index/index_builder.h
  src/include/storage/index/index_defs.h
  src/include/storage/index/index_metadata.h
  src/include/storage/projected_row.h
  src/include/storage/sql_table.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/type/type_id.h
  src/include/type/type_util.h
  src/storage/projected_row.cpp
  src/storage/storage_util.cpp
  test/common/stat_registry_test.cpp
  test/include/util/transaction_test_util.h
  test/storage/bwtree_index_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
  third_party/bwtree/bwtree.h
  third_party/portable_endian/portable_endian.h
Labels: feature, ready-to-merge

#345 Updates now retry on failure
  src/storage/data_table.cpp
Labels: performance, ready-for-review

#349 Add std::string_view accessor for VarlenEntry
  src/include/storage/storage_defs.h
  test/storage/varlen_entry_test.cpp
Labels: feature, ready-for-review

#350 Faster padding calculation
  src/include/storage/storage_util.h
  src/storage/storage_util.cpp
Labels: performance, ready-for-review

#352 BwTreeIndex::Scan and PRI accessor.
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/index.h
  src/include/storage/index/index_metadata.h
  test/storage/bwtree_index_test.cpp
Labels: feature, ready-to-merge

#334 Expression JSON (De)serialization
  .gitignore
  src/include/common/json.h
  src/include/common/sql_node_visitor.h
  src/include/parser/create_function_statement.h
  src/include/parser/expression/abstract_expression.h
  src/include/parser/expression/aggregate_expression.h
  src/include/parser/expression/case_expression.h
  src/include/parser/expression/comparison_expression.h
  src/include/parser/expression/conjunction_expression.h
  src/include/parser/expression/constant_value_expression.h
  src/include/parser/expression/function_expression.h
  src/include/parser/expression/operator_expression.h
  src/include/parser/expression/parameter_value_expression.h
  src/include/parser/expression/star_expression.h
  src/include/parser/expression/subquery_expression.h
  src/include/parser/expression/tuple_value_expression.h
  src/include/parser/expression/type_cast_expression.h
  src/include/parser/select_statement.h
  src/include/parser/sql_statement.h
  src/include/parser/table_ref.h
  src/include/type/transient_value.h
  src/parser/expression/abstract_expression.cpp
  src/parser/postgresparser.cpp
  src/parser/select_statement.cpp
  src/parser/table_ref.cpp
  test/parser/expression_test.cpp
  test/parser/parser_test.cpp
  test/type/transient_value_test.cpp
Labels: beginner, in-progress

#324 Layout changes for Arrow
  src/include/catalog/schema.h
  src/include/common/allocator.h
  src/include/common/constants.h
  src/include/common/strong_typedef.h
  src/include/storage/arrow_block_metadata.h
  src/include/storage/block_access_controller.h
  src/include/storage/block_layout.h
  src/include/storage/data_table.h
  src/include/storage/storage_defs.h
  src/include/storage/tuple_access_strategy.h
  src/include/storage/undo_record.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/storage/block_layout.cpp
  src/storage/data_table.cpp
  src/storage/garbage_collector.cpp
  src/storage/tuple_access_strategy.cpp
  test/include/util/storage_test_util.h
  test/network/network_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/log_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
Labels: bug, feature, ready-to-merge

#361 Update lookback on benchmarks
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, performance, ready-for-review

#360 Add another Column constructor with a field for max VARLEN length
  src/include/catalog/schema.h
  test/include/util/catalog_test_util.h
  test/storage/sql_table_test.cpp
Labels: ready-to-merge

#358 Add action framework
  benchmark/storage/data_table_benchmark.cpp
  src/include/storage/garbage_collector.h
  src/include/storage/storage_defs.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_defs.h
  src/include/transaction/transaction_manager.h
  src/storage/garbage_collector.cpp
  src/transaction/transaction_manager.cpp
  test/common/stat_registry_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/transaction/deferred_actions_test.cpp
Labels: feature, ready-to-merge

#348 Embed attribute sizes into ProjectedColumns
  src/include/storage/projected_columns.h
  src/include/storage/sql_table.h
  src/include/storage/storage_defs.h
  src/include/type/type_util.h
  src/storage/data_table.cpp
  src/storage/projected_columns.cpp
  src/storage/sql_table.cpp
  src/storage/storage_util.cpp
  test/include/util/storage_test_util.h
  test/storage/data_table_test.cpp
  test/storage/sql_table_test.cpp
  test/storage/storage_util_test.cpp
Labels: feature, ready-to-merge
