Repository cmu-db/noisepage, pull requests merged in 2019-06, with the labels that each got.

#399 BwTree memory leak fix
  test/storage/bwtree_test.cpp
  third_party/bwtree/bwtree.h
Labels: bug, ready-to-merge, tests

#383 TPC-C microbenchmark
  benchmark/CMakeLists.txt
  benchmark/integration/CMakeLists.txt
  benchmark/integration/tpcc_benchmark.cpp
  script/micro_bench/run_micro_bench.py
  src/include/storage/index/bwtree_index.h
  test/CMakeLists.txt
  test/include/util/tpcc/README.md
  test/include/util/tpcc/builder.h
  test/include/util/tpcc/database.h
  test/include/util/tpcc/delivery.h
  test/include/util/tpcc/loader.h
  test/include/util/tpcc/new_order.h
  test/include/util/tpcc/order_status.h
  test/include/util/tpcc/payment.h
  test/include/util/tpcc/schemas.h
  test/include/util/tpcc/stock_level.h
  test/include/util/tpcc/tpcc_defs.h
  test/include/util/tpcc/util.h
  test/include/util/tpcc/worker.h
  test/include/util/tpcc/workload.h
  test/integration/CMakeLists.txt
  test/integration/tpcc_test.cpp
  test/util/tpcc/builder.cpp
  test/util/tpcc/delivery.cpp
  test/util/tpcc/new_order.cpp
  test/util/tpcc/order_status.cpp
  test/util/tpcc/payment.cpp
  test/util/tpcc/stock_level.cpp
  test/util/tpcc/workload.cpp
Labels: feature, ready-for-review, tests

#406 Logical Ops
  src/include/common/hash_util.h
  src/include/common/managed_pointer.h
  src/include/optimizer/operator_expression.h
  src/include/optimizer/operator_node.h
  src/include/optimizer/operator_visitor.h
  src/include/optimizer/operators.h
  src/include/optimizer/optimizer_defs.h
  src/include/parser/expression/abstract_expression.h
  src/include/parser/update_statement.h
  src/include/planner/plannodes/delete_plan_node.h
  src/include/planner/plannodes/plan_node_defs.h
  src/optimizer/operator_node.cpp
  src/optimizer/operators.cpp
  src/parser/postgresparser.cpp
  test/CMakeLists.txt
  test/common/hash_util_test.cpp
  test/optimizer/CMakeLists.txt
  test/optimizer/operator_test.cpp
  test/parser/parser_test.cpp
Labels: feature, in-progress

#408 Physical operators
  src/include/optimizer/logical_operators.h
  src/include/optimizer/operator_expression.h
  src/include/optimizer/operator_node.h
  src/include/optimizer/operator_visitor.h
  src/include/optimizer/physical_operators.h
  src/optimizer/logical_operators.cpp
  src/optimizer/physical_operators.cpp
  test/optimizer/logical_operator_test.cpp
  test/optimizer/operator_expression_test.cpp
  test/optimizer/physical_operator_test.cpp
Labels: ready-to-merge

#409 HyPer bug fix
  src/include/storage/storage_defs.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/storage/data_table.cpp
  src/storage/garbage_collector.cpp
  src/transaction/transaction_manager.cpp
  test/storage/garbage_collector_test.cpp
Labels: bug, ready-for-review

#405 Add BwTree garbage collection to centralized GC
  benchmark/integration/tpcc_benchmark.cpp
  src/include/storage/garbage_collector.h
  src/include/storage/garbage_collector_thread.h
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/index.h
  src/storage/garbage_collector.cpp
  test/include/util/tpcc/util.h
  test/integration/tpcc_test.cpp
  test/storage/bwtree_index_test.cpp
Labels: feature, ready-to-merge

#411 SqlTable::Insert API change
  src/include/storage/sql_table.h
  src/include/transaction/transaction_context.h
  test/include/util/tpcc/loader.h
  test/storage/bwtree_index_test.cpp
  test/storage/bwtree_key_test.cpp
  test/util/tpcc/delivery.cpp
  test/util/tpcc/new_order.cpp
Labels: ready-to-merge

#390 Default value support with tests.
  src/include/parser/expression/default_value_expression.h
  src/include/parser/expression_defs.h
  src/parser/postgresparser.cpp
  test/parser/parser_test.cpp
Labels: feature, ready-to-merge

#412 Update benchmark lookback
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, tests

#416 Removed GetCopy() from TransientValueFactory
  src/include/parser/expression/default_value_expression.h
  src/include/settings/settings_manager.h
  src/include/type/transient_value_factory.h
  src/settings/settings_manager.cpp
  test/type/transient_value_test.cpp
Labels: ready-to-merge

#422 Add missing unlink for LoggingBenchmark
  benchmark/storage/logging_benchmark.cpp
Labels: bug

#414 Network Refactor
  src/include/main/db_main.h
  src/include/network/connection_context.h
  src/include/network/connection_dispatcher_task.h
  src/include/network/connection_handle.h
  src/include/network/connection_handle_factory.h
  src/include/network/connection_handler_task.h
  src/include/network/network_defs.h
  src/include/network/network_io_wrapper.h
  src/include/network/postgres/postgres_command_factory.h
  src/include/network/postgres/postgres_network_commands.h
  src/include/network/postgres/postgres_protocol_interpreter.h
  src/include/network/postgres/postgres_protocol_utils.h
  src/include/network/protocol_interpreter.h
  src/include/network/terrier_server.h
  src/include/traffic_cop/portal.h
  src/include/traffic_cop/result_set.h
  src/include/traffic_cop/sqlite.h
  src/include/traffic_cop/statement.h
  src/include/traffic_cop/traffic_cop.h
  src/main/db_main.cpp
  src/network/connection_dispatcher_task.cpp
  src/network/connection_handle.cpp
  src/network/connection_handle_factory.cpp
  src/network/connection_handler_task.cpp
  src/network/postgres/postgres_network_commands.cpp
  src/network/postgres/postgres_protocol_interpreter.cpp
  src/network/postgres_command_factory.cpp
  src/network/terrier_server.cpp
  src/traffic_cop/sqlite.cpp
  test/include/util/manual_packet_helpers.h
  test/include/util/manual_packet_util.h
  test/network/network_test.cpp
  test/traffic_cop/traffic_cop_test.cpp
Labels: best-practice, ready-to-merge

#425 Add AbortRecord to logging
  src/include/storage/record_buffer.h
  src/include/storage/sql_table.h
  src/include/storage/storage_defs.h
  src/include/storage/write_ahead_log/log_manager.h
  src/include/storage/write_ahead_log/log_record.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_manager.h
  src/storage/record_buffer.cpp
  src/storage/write_ahead_log/log_serializer_task.cpp
  src/transaction/transaction_manager.cpp
  test/storage/log_test.cpp
Labels: feature, ready-for-review

#428 Switch TPC-C microbenchmark for CI runs to use ramdisk
  benchmark/integration/tpcc_benchmark.cpp
Labels: ready-for-review, tests

#400 SettingsManager + PlanNode Fixes/Tests
  src/include/catalog/catalog_defs.h
  src/include/common/action_context.h
  src/include/planner/plannodes/abstract_plan_node.h
  src/include/planner/plannodes/create_table_plan_node.h
  src/include/planner/plannodes/output_schema.h
  src/include/settings/settings_defs.h
  src/planner/plannodes/abstract_join_plan_node.cpp
  src/planner/plannodes/abstract_scan_plan_node.cpp
  src/planner/plannodes/aggregate_plan_node.cpp
  src/planner/plannodes/analyze_plan_node.cpp
  src/planner/plannodes/create_database_plan_node.cpp
  src/planner/plannodes/create_function_plan_node.cpp
  src/planner/plannodes/create_index_plan_node.cpp
  src/planner/plannodes/create_namespace_plan_node.cpp
  src/planner/plannodes/create_table_plan_node.cpp
  src/planner/plannodes/create_trigger_plan_node.cpp
  src/planner/plannodes/create_view_plan_node.cpp
  src/planner/plannodes/csv_scan_plan_node.cpp
  src/planner/plannodes/delete_plan_node.cpp
  src/planner/plannodes/drop_database_plan_node.cpp
  src/planner/plannodes/drop_index_plan_node.cpp
  src/planner/plannodes/drop_namespace_plan_node.cpp
  src/planner/plannodes/drop_table_plan_node.cpp
  src/planner/plannodes/drop_trigger_plan_node.cpp
  src/planner/plannodes/drop_view_plan_node.cpp
  src/planner/plannodes/export_external_file_plan_node.cpp
  src/planner/plannodes/hash_join_plan_node.cpp
  src/planner/plannodes/hash_plan_node.cpp
  src/planner/plannodes/index_scan_plan_node.cpp
  src/planner/plannodes/insert_plan_node.cpp
  src/planner/plannodes/limit_plan_node.cpp
  src/planner/plannodes/nested_loop_join_plan_node.cpp
  src/planner/plannodes/order_by_plan_node.cpp
  src/planner/plannodes/projection_plan_node.cpp
  src/planner/plannodes/result_plan_node.cpp
  src/planner/plannodes/seq_scan_plan_node.cpp
  src/planner/plannodes/set_op_plan_node.cpp
  src/planner/plannodes/update_plan_node.cpp
  src/settings/settings_manager.cpp
  test/planner/output_schema_test.cpp
  test/planner/plan_node_json_test.cpp
  test/planner/plan_node_test.cpp
  test/settings/settings_test.cpp
  test/type/type_util_test.cpp
Labels: ready-to-merge, tests

#435 Abort Record Fix
  src/include/storage/write_ahead_log/log_record.h
  src/include/transaction/transaction_manager.h
  src/storage/write_ahead_log/log_serializer_task.cpp
  src/transaction/transaction_manager.cpp
  test/storage/log_test.cpp
Labels: bug, ready-for-review

#434 Rename TransactionContext::TxnId() to FinishTime()
  src/include/transaction/transaction_context.h
  src/storage/data_table.cpp
  src/storage/garbage_collector.cpp
  src/transaction/transaction_manager.cpp
Labels: best-practice, ready-to-merge

#438 Optimizer Stats: Histogram
  src/include/loggers/optimizer_logger.h
  src/include/optimizer/statistics/histogram.h
  test/optimizer/histogram_test.cpp
Labels: ready-for-review

#440 Optimizer Stats: CountMinSketch
  src/CMakeLists.txt
  src/include/loggers/loggers_util.h
  src/include/loggers/optimizer_logger.h
  src/include/optimizer/statistics/count_min_sketch.h
  src/include/optimizer/statistics/histogram.h
  src/loggers/optimizer_logger.cpp
  test/optimizer/count_min_sketch_test.cpp
  test/optimizer/histogram_test.cpp
  third_party/madoka/approx.h
  third_party/madoka/croquis.h
  third_party/madoka/exception.h
  third_party/madoka/file.cc
  third_party/madoka/file.h
  third_party/madoka/hash.h
  third_party/madoka/header.h
  third_party/madoka/madoka.h
  third_party/madoka/random.h
  third_party/madoka/sketch.cc
  third_party/madoka/sketch.h
  third_party/madoka/util.h
  third_party/murmur3/MurmurHash3.cpp
  third_party/murmur3/MurmurHash3.h
  third_party/versions.txt
Labels: ready-for-review

#445 Revert "Optimizer Stats: CountMinSketch"
  src/CMakeLists.txt
  src/include/loggers/loggers_util.h
  src/include/loggers/optimizer_logger.h
  src/include/optimizer/statistics/count_min_sketch.h
  src/include/optimizer/statistics/histogram.h
  src/loggers/optimizer_logger.cpp
  test/optimizer/count_min_sketch_test.cpp
  test/optimizer/histogram_test.cpp
  third_party/madoka/approx.h
  third_party/madoka/croquis.h
  third_party/madoka/exception.h
  third_party/madoka/file.cc
  third_party/madoka/file.h
  third_party/madoka/hash.h
  third_party/madoka/header.h
  third_party/madoka/madoka.h
  third_party/madoka/random.h
  third_party/madoka/sketch.cc
  third_party/madoka/sketch.h
  third_party/madoka/util.h
  third_party/murmur3/MurmurHash3.cpp
  third_party/murmur3/MurmurHash3.h
  third_party/versions.txt
Labels: bug, ready-for-review

#451 Optimizer Stats: HyperLogLog
  src/CMakeLists.txt
  src/include/optimizer/statistics/hyperloglog.h
  test/optimizer/hyperloglog_test.cpp
  third_party/libcount/c.cc
  third_party/libcount/c.h
  third_party/libcount/empirical_data.cc
  third_party/libcount/empirical_data.h
  third_party/libcount/hll.cc
  third_party/libcount/hll.h
  third_party/libcount/hll_data.cc
  third_party/libcount/hll_data.h
  third_party/libcount/hll_limits.h
  third_party/libcount/utility.cc
  third_party/libcount/utility.h
  third_party/versions.txt
Labels: ready-for-review

#447 Add GMock and associated macro
  CMakeLists.txt
  cmake_modules/FindGTest.cmake
  cmake_modules/ThirdpartyToolchain.cmake
  src/include/common/macros.h
  test/include/util/test_harness.h
Labels: best-practice, ready-for-review, tests

#452 Templatize ScopedTimer
  benchmark/integration/tpcc_benchmark.cpp
  benchmark/storage/bwtree_benchmark.cpp
  benchmark/storage/garbage_collector_benchmark.cpp
  benchmark/storage/logging_benchmark.cpp
  benchmark/transaction/large_transaction_benchmark.cpp
  src/include/common/scoped_timer.h
Labels: ready-to-merge

#454 Optimizer Stats: ValueCondition
  src/include/optimizer/statistics/value_condition.h
  test/optimizer/value_condition_test.cpp
Labels: feature, ready-for-review

#455 Fix to log persist timeout
  src/storage/write_ahead_log/disk_log_consumer_task.cpp
Labels: bug, ready-to-merge
