Repository cmu-db/noisepage, pull requests merged in 2019-09, with the labels that each got.

#441 Refactor deferred action framework
  benchmark/include/util/transaction_benchmark_util.h
  benchmark/integration/tpcc_benchmark.cpp
  benchmark/storage/block_compactor_benchmark.cpp
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/garbage_collector_benchmark.cpp
  benchmark/storage/logging_benchmark.cpp
  benchmark/transaction/large_transaction_benchmark.cpp
  benchmark/util/transaction_benchmark_util.cpp
  src/catalog/catalog.cpp
  src/catalog/database_catalog.cpp
  src/include/catalog/catalog.h
  src/include/catalog/database_catalog.h
  src/include/common/macros.h
  src/include/di/injectors.h
  src/include/main/db_main.h
  src/include/planner/plannodes/create_table_plan_node.h
  src/include/storage/block_compactor.h
  src/include/storage/garbage_collector.h
  src/include/storage/garbage_collector_thread.h
  src/include/storage/index/bwtree_index.h
  src/include/storage/storage_defs.h
  src/include/transaction/deferred_action_manager.h
  src/include/transaction/timestamp_manager.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_defs.h
  src/include/transaction/transaction_manager.h
  src/main/db_main.cpp
  src/storage/block_compactor.cpp
  src/storage/garbage_collector.cpp
  src/storage/garbage_collector_thread.cpp
  src/storage/record_buffer.cpp
  src/transaction/transaction_manager.cpp
  test/catalog/catalog_test.cpp
  test/common/stat_registry_test.cpp
  test/integration/tpcc_test.cpp
  test/storage/block_compactor_test.cpp
  test/storage/bwtree_index_test.cpp
  test/storage/bwtree_key_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/garbage_collector_test.cpp
  test/transaction/deferred_actions_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
  third_party/libpg_query/src/postgres/include/catalog/index.h
  third_party/libpg_query/src/postgres/include/utils/errcodes.h
  third_party/libpg_query/src/postgres/scan.c
Labels: best-practice, feature, ready-to-merge

#467 Optimizer Stats: StatsStorage & Supporting Files
  src/include/optimizer/statistics/column_stats.h
  src/include/optimizer/statistics/stats_storage.h
  src/include/optimizer/statistics/table_stats.h
  src/optimizer/statistics/stats_storage.cpp
  src/optimizer/statistics/table_stats.cpp
  test/optimizer/column_stats_test.cpp
  test/optimizer/stats_storage_test.cpp
  test/optimizer/table_stats_test.cpp
Labels: feature, ready-for-review

#528 Statistics Utilities
  src/CMakeLists.txt
  src/include/loggers/loggers_util.h
  src/include/loggers/optimizer_logger.h
  src/include/optimizer/statistics/column_stats.h
  src/include/optimizer/statistics/count_min_sketch.h
  src/include/optimizer/statistics/histogram.h
  src/include/optimizer/statistics/hyperloglog.h
  src/include/optimizer/statistics/stats_storage.h
  src/include/optimizer/statistics/table_stats.h
  src/include/optimizer/statistics/top_k_elements.h
  src/include/optimizer/statistics/value_condition.h
  src/loggers/optimizer_logger.cpp
  src/optimizer/statistics/stats_storage.cpp
  src/optimizer/statistics/table_stats.cpp
  test/optimizer/column_stats_test.cpp
  test/optimizer/count_min_sketch_test.cpp
  test/optimizer/histogram_test.cpp
  test/optimizer/hyperloglog_test.cpp
  test/optimizer/stats_storage_test.cpp
  test/optimizer/table_stats_test.cpp
  test/optimizer/top_k_elements_test.cpp
  test/optimizer/value_condition_test.cpp
  third_party/libcount/c.cc
  third_party/libcount/c.h
  third_party/libcount/empirical_data.cc
  third_party/libcount/empirical_data.h
  third_party/libcount/hll.cc
  third_party/libcount/hll.h
  third_party/libcount/hll_data.cc
  third_party/libcount/hll_data.h
  third_party/libcount/hll_limits.h
  third_party/libcount/utility.cc
  third_party/libcount/utility.h
  third_party/madoka/approx.h
  third_party/madoka/croquis.h
  third_party/madoka/exception.h
  third_party/madoka/file.cc
  third_party/madoka/file.h
  third_party/madoka/hash.h
  third_party/madoka/header.h
  third_party/madoka/madoka.h
  third_party/madoka/random.h
  third_party/madoka/sketch.cc
  third_party/madoka/sketch.h
  third_party/madoka/util.h
  third_party/murmur3/MurmurHash3.cpp
  third_party/murmur3/MurmurHash3.h
  third_party/versions.txt
Labels: ready-for-review

#532 Remove dead code
  src/include/storage/tuple_access_strategy.h
Labels: best-practice, ready-to-merge

#529 Use numactl instead of taskset for run_micro_bench.py
  Jenkinsfile
  script/micro_bench/cpu_lib.py
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, ready-to-merge

#533 CountMinSketch Tests Fixes
  test/optimizer/count_min_sketch_test.cpp
Labels: bug, ready-to-merge, tests

#535 clang-tidy: performance-unnecessary-value-param
  .clang-tidy
  src/include/planner/plannodes/abstract_join_plan_node.h
  src/include/planner/plannodes/abstract_plan_node.h
  src/include/planner/plannodes/abstract_scan_plan_node.h
  src/include/planner/plannodes/hash_plan_node.h
  src/include/settings/settings_manager.h
  src/settings/settings_manager.cpp
Labels: best-practice, ready-to-merge, tests

#527 GC queue and Deferred Action queue Ordering
  src/include/transaction/deferred_action_manager.h
  src/include/transaction/timestamp_manager.h
  src/include/transaction/transaction_manager.h
  src/transaction/transaction_manager.cpp
Labels: bug, feature, ready-to-merge

#542 Update lookback after merging #516
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, ready-for-review, tests

#538 Change catalog's #define'd constants to be constexpr instead
  src/catalog/catalog.cpp
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/include/catalog/catalog_accessor.h
  src/include/catalog/catalog_defs.h
  src/include/catalog/postgres/pg_attribute.h
  src/include/catalog/postgres/pg_class.h
  src/include/catalog/postgres/pg_constraint.h
  src/include/catalog/postgres/pg_database.h
  src/include/catalog/postgres/pg_index.h
  src/include/catalog/postgres/pg_namespace.h
  src/include/catalog/postgres/pg_type.h
  test/catalog/catalog_test.cpp
Labels: best-practice, ready-to-merge

#545 Basic catalog microbenchmarks
  benchmark/CMakeLists.txt
  benchmark/catalog/CMakeLists.txt
  benchmark/catalog/catalog_benchmark.cpp
  script/micro_bench/run_micro_bench.py
Labels: ready-to-merge, tests

#546 Catalog: reuse ProjectedRowInitializers and maps
  src/catalog/catalog.cpp
  src/catalog/database_catalog.cpp
  src/include/catalog/catalog.h
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/pg_database.h
  src/include/storage/projected_row.h
Labels: performance, ready-to-merge

#539 Add helper function to extract referenced column oids from AbstractExpression
  src/include/parser/expression/expression_util.h
  test/parser/expression_util_test.cpp
Labels: beginner, best-practice, ready-to-merge

#553 Better GetIndexes method
  benchmark/catalog/catalog_benchmark.cpp
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/include/catalog/catalog_accessor.h
  src/include/catalog/database_catalog.h
  test/catalog/catalog_test.cpp
Labels: feature, ready-to-merge

#543 Added Index OID vector to InsertPlanNode
  src/include/optimizer/physical_operators.h
  src/include/planner/plannodes/insert_plan_node.h
  src/optimizer/physical_operators.cpp
  test/optimizer/physical_operator_test.cpp
  test/planner/plan_node_json_test.cpp
Labels: ready-to-merge

#559 Update LLVM_DIR path for llvm@8 Homebrew package
  .travis.yml
  Jenkinsfile
  script/installation/packages.sh
Labels: infrastructure, ready-to-merge

#551 Move coverage to Jenkins from Travis
  .travis.yml
  Jenkinsfile
  src/storage/sql_table.cpp
Labels: infrastructure, ready-to-merge

#558 Add recovery benchmark to nightly runs and new index recovery benchmark
  benchmark/storage/recovery_benchmark.cpp
  script/micro_bench/run_micro_bench.py
  src/storage/sql_table.cpp
Labels: infrastructure, ready-for-review

#563 Multiplatform thread CPU timer
  src/include/common/thread_cpu_timer.h
  test/common/thread_cpu_timer_test.cpp
Labels: feature, ready-to-merge

#570 Add missing documentation for typedefs
  .gitignore
  src/include/common/hash_util.h
  src/include/common/worker_pool.h
Labels: best-practice, ready-for-review

#573 Simplified thread cpu timer test
  test/common/thread_cpu_timer_test.cpp
Labels: bug, ready-for-review, tests

#572 AstDump Unit Test
  test/common/thread_cpu_timer_test.cpp
  test/execution/ast_dump_test.cpp
Labels: ready-for-review, tests
