Repository cmu-db/noisepage, pull requests merged in 2019-10, with the labels that each got.

#565 Cleaning up nightly microbench script
  Jenkinsfile
  script/micro_bench/.gitignore
  script/micro_bench/README.md
  script/micro_bench/run_micro_bench.py
Labels: ready-for-review, tests

#579 Add `make clean` as final step of Jenkins builds
  Jenkinsfile
Labels: infrastructure, ready-to-merge

#578 Modify TPC-C microbenchmark framework to use Catalog
  benchmark/integration/tpcc_benchmark.cpp
  src/include/storage/garbage_collector.h
  src/storage/garbage_collector.cpp
  test/include/util/tpcc/builder.h
  test/include/util/tpcc/database.h
  test/include/util/tpcc/loader.h
  test/include/util/tpcc/schemas.h
  test/include/util/tpcc/util.h
  test/include/util/tpcc/worker.h
  test/integration/tpcc_test.cpp
  test/metrics/metrics_test.cpp
  test/storage/bwtree_index_test.cpp
  test/storage/hash_index_test.cpp
  test/util/tpcc/builder.cpp
  test/util/tpcc/delivery.cpp
Labels: ready-to-merge, tests

#550 ASAN flag wasn't being passed to the IR compiler
  CMakeLists.txt
  cmake_modules/san-config.cmake
Labels: infrastructure, tests

#587 Fix hashing DropTriggerPlanNode and UpdatePlanNode
  src/optimizer/physical_operators.cpp
  src/planner/plannodes/drop_trigger_plan_node.cpp
  src/planner/plannodes/update_plan_node.cpp
Labels: bug, ready-to-merge

#590 Remove murmur3 from the codebase, bump xxHash version
  src/CMakeLists.txt
  src/include/optimizer/statistics/hyperloglog.h
  test/optimizer/hyperloglog_test.cpp
  third_party/murmur3/MurmurHash3.cpp
  third_party/murmur3/MurmurHash3.h
  third_party/versions.txt
  third_party/xxHash/xxh3.h
  third_party/xxHash/xxhash.c
  third_party/xxHash/xxhash.h
Labels: ready-to-merge

#591 Increase recovery benchmark iterations
  benchmark/storage/recovery_benchmark.cpp
Labels: infrastructure, ready-to-merge

#574 Refactoring for network protocols
  src/include/network/connection_dispatcher_task.h
  src/include/network/network_command.h
  src/include/network/network_defs.h
  src/include/network/network_io_utils.h
  src/include/network/packet_writer.h
  src/include/network/postgres/postgres_command_factory.h
  src/include/network/postgres/postgres_network_commands.h
  src/include/network/postgres/postgres_packet_writer.h
  src/include/network/postgres/postgres_protocol_interpreter.h
  src/include/network/postgres/postgres_protocol_utils.h
  src/main/db_main.cpp
  src/network/connection_dispatcher_task.cpp
  src/network/postgres/postgres_command_factory.cpp
  src/network/postgres/postgres_network_commands.cpp
  src/network/postgres/postgres_protocol_interpreter.cpp
  src/network/postgres_command_factory.cpp
  test/include/util/manual_packet_util.h
  test/network/network_test.cpp
  test/traffic_cop/traffic_cop_test.cpp
Labels: ready-to-merge

#581 Index wrapper benchmark
  benchmark/storage/index_wrapper_benchmark.cpp
  script/micro_bench/run_micro_bench.py
Labels: ready-to-merge, tests

#601 Clean Sqlite TrafficCop
  src/include/network/connection_context.h
  src/include/network/packet_writer.h
  src/include/network/postgres/postgres_packet_writer.h
  src/include/traffic_cop/portal.h
  src/include/traffic_cop/sqlite.h
  src/include/traffic_cop/statement.h
  src/network/postgres/postgres_network_commands.cpp
  src/traffic_cop/sqlite.cpp
  test/traffic_cop/traffic_cop_test.cpp
Labels: ready-for-review, ready-to-merge

#602 ITP Pipeline Setup
  src/include/network/itp/itp_command_factory.h
  src/include/network/itp/itp_network_commands.h
  src/include/network/itp/itp_packet_writer.h
  src/include/network/itp/itp_protocol_interpreter.h
  src/include/network/network_defs.h
  src/include/network/network_io_utils.h
  src/include/network/postgres/postgres_protocol_interpreter.h
  src/include/network/protocol_interpreter.h
  src/include/storage/recovery/replication_log_provider.h
  src/include/traffic_cop/traffic_cop.h
  src/network/itp/itp_command_factory.cpp
  src/network/itp/itp_network_commands.cpp
  src/network/itp/itp_protocol_interpreter.cpp
  src/network/postgres/postgres_protocol_interpreter.cpp
Labels: ready-to-merge
