Repository cmu-db/noisepage, pull requests merged in 2019-01, with the labels that each got.

#269 List checks when invoking make check-clang-tidy.
  build-support/run-clang-tidy.py
Labels: infrastructure, ready-for-review

#192 Thread pool
  benchmark/storage/bwtree_benchmark.cpp
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  benchmark/util/transaction_benchmark_util.cpp
  src/include/common/worker_pool.h
  test/common/concurrent_bitmap_test.cpp
  test/common/object_pool_test.cpp
  test/common/worker_pool_test.cpp
  test/include/util/bwtree_test_util.h
  test/include/util/catalog_test_util.h
  test/include/util/multithread_test_util.h
  test/include/util/storage_test_util.h
  test/include/util/test_thread_pool.h
  test/storage/bwtree_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/large_garbage_collector_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/storage/varlen_pool_test.cpp
  test/transaction/large_transaction_test.cpp
  test/util/transaction_test_util.cpp
Labels: feature, ready-to-merge

#273 Add parser support for DISTINCT in aggregation functions.
  src/include/parser/expression/aggregate_expression.h
  src/parser/postgresparser.cpp
Labels: feature, ready-for-review

#275 Varlen support for SQLTables
  src/include/catalog/schema.h
  src/include/type/type_util.h
  src/storage/storage_util.cpp
  test/storage/sql_table_test.cpp
  test/storage/storage_util_test.cpp
Labels: ready-to-merge

#274 Alignment
  src/storage/block_layout.cpp
  src/storage/projected_row.cpp
  src/storage/tuple_access_strategy.cpp
Labels: feature, ready-to-merge

#277 Insert patch
  src/include/common/container/concurrent_bitmap.h
  src/include/storage/tuple_access_strategy.h
  test/storage/data_table_test.cpp
  test/transaction/mvcc_test.cpp
Labels: bug, ready-for-review

#278 Standardize on not using memory macros and removed from macros.h.
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  benchmark/util/transaction_benchmark_util.cpp
  src/include/common/container/bitmap.h
  src/include/common/container/concurrent_bitmap.h
  src/include/common/macros.h
  src/include/storage/write_ahead_log/log_io.h
  src/storage/data_table.cpp
  src/storage/projected_row.cpp
  src/storage/storage_util.cpp
  test/common/bitmap_test.cpp
  test/include/util/storage_test_util.h
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/sql_table_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/mvcc_test.cpp
  test/util/transaction_test_util.cpp
Labels: best-practice, in-progress

#280 Update libz dependency in ubuntu install scripts
  script/installation/packages.sh
Labels: infrastructure, ready-to-merge

#282 fix typo
  src/include/storage/tuple_access_strategy.h
  src/storage/tuple_access_strategy.cpp
Labels: best-practice, ready-to-merge
