Repository cmu-db/noisepage, pull requests merged in 2019-12, with the labels that each got.

#638 Larger attribute size
  benchmark/benchmark_util/data_table_benchmark_util.cpp
  benchmark/include/benchmark_util/data_table_benchmark_util.h
  benchmark/metrics/large_transaction_metrics_benchmark.cpp
  benchmark/metrics/logging_metrics_benchmark.cpp
  benchmark/storage/block_compactor_benchmark.cpp
  benchmark/storage/index_wrapper_benchmark.cpp
  benchmark/storage/logging_benchmark.cpp
  benchmark/transaction/large_transaction_benchmark.cpp
  src/include/catalog/schema.h
  src/include/storage/block_layout.h
  src/include/storage/index/index_metadata.h
  src/include/storage/projected_row.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/type/transient_value.h
  src/include/type/type_util.h
  src/storage/block_layout.cpp
  src/storage/projected_row.cpp
  src/storage/recovery/abstract_log_provider.cpp
  src/storage/recovery/recovery_manager.cpp
  src/storage/sql_table.cpp
  src/storage/storage_util.cpp
  src/transaction/transaction_manager.cpp
  test/include/test_util/storage_test_util.h
  test/include/test_util/tpcc/util.h
  test/storage/bwtree_index_test.cpp
  test/storage/hash_index_test.cpp
  test/storage/index_key_test.cpp
  test/storage/log_test.cpp
  test/storage/projected_row_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/type/type_util_test.cpp
  util/execution/table_generator/table_generator.cpp
Labels: best-practice, ready-to-merge

#644 Cascading DROP logic for table and namespace
  src/catalog/database_catalog.cpp
  src/include/catalog/database_catalog.h
  test/catalog/catalog_test.cpp
Labels: feature, ready-to-merge

#632 Per-connection temporary namespaces, many related fixes
  benchmark/integration/tpcc_benchmark.cpp
  benchmark/storage/recovery_benchmark.cpp
  script/testing/junit/PLTestBase.java
  src/execution/vm/bytecode_emitter.cpp
  src/include/main/db_main.h
  src/include/network/connection_context.h
  src/include/network/connection_handle.h
  src/include/network/network_types.h
  src/include/network/postgres/postgres_protocol_interpreter.h
  src/include/network/postgres/postgres_protocol_utils.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_common.h
  src/include/settings/settings_defs.h
  src/include/settings/settings_manager.h
  src/include/traffic_cop/traffic_cop.h
  src/include/traffic_cop/traffic_cop_defs.h
  src/include/transaction/deferred_action_manager.h
  src/main/db_main.cpp
  src/network/connection_handle.cpp
  src/network/postgres/postgres_protocol_interpreter.cpp
  src/settings/settings_callbacks.cpp
  src/settings/settings_manager.cpp
  src/traffic_cop/traffic_cop.cpp
  test/common/perf_monitor_test.cpp
  test/include/test_util/manual_packet_util.h
  test/include/test_util/storage_test_util.h
  test/integration/tpcc_test.cpp
  test/network/network_test.cpp
  test/settings/settings_test.cpp
  test/storage/recovery_test.cpp
  test/traffic_cop/traffic_cop_test.cpp
Labels: feature, ready-for-review

#647 Jenkins cleanup
  Jenkinsfile
  script/jenkins/benchmark-agent-setup.sh
  script/jenkins/docker-agent-setup.sh
  script/jenkins/swarm.sh
  script/jenkins/vmware_startup.sh
Labels: infrastructure, ready-for-review

#608 Operations needed for TPCC.
  sample_tpl/delete.tpl
  sample_tpl/deleter-2.tpl
  sample_tpl/insert.tpl
  sample_tpl/join-index.tpl
  sample_tpl/scan-index-2.tpl
  sample_tpl/scan-index-3.tpl
  sample_tpl/scan-index.tpl
  sample_tpl/tpl_tests.txt
  sample_tpl/update.tpl
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/index_iterator.cpp
  src/execution/sql/storage_interface.cpp
  src/execution/vm/bytecode_emitter.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/bytecode_handlers.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/builtins.h
  src/include/execution/ast/type.h
  src/include/execution/sema/sema.h
  src/include/execution/sql/index_iterator.h
  src/include/execution/sql/storage_interface.h
  src/include/execution/sql/value.h
  src/include/execution/util/hash.h
  src/include/execution/vm/bytecode_emitter.h
  src/include/execution/vm/bytecode_generator.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/storage/projected_row.h
  src/include/storage/storage_defs.h
  test/execution/index_iterator_test.cpp
  test/execution/storage_interface_test.cpp
  util/execution/table_generator/table_generator.cpp
  util/include/execution/table_generator/table_generator.h
Labels: feature, ready-to-merge
