Repository cmu-db/noisepage, pull requests merged in 2019-03, with the labels that each got.

#309 Fix strict aliasing warning on Release mode with TransientValue
  src/include/type/transient_value.h
Labels: bug, ready-for-review

#307 Github PR Czar Scripts
  script/github/github-pr-status.py
  script/github/github-stats.py
Labels: infrastructure, ready-for-review

#306 Bad words filter as "make check-censored" target
  .travis.yml
  CMakeLists.txt
  build-support/bad_words.txt
  src/include/common/performance_counter.h
  src/include/parser/sql_statement.h
  src/include/type/transient_value_peeker.h
  src/main/terrier.cpp
  test/common/stat_registry_test.cpp
  test/include/util/bwtree_test_util.h
  test/include/util/storage_test_util.h
  test/storage/sql_table_test.cpp
Labels: feature, infrastructure, ready-for-review

#296 More parser test for coverage
  test/parser/parser_test.cpp
Labels: ready-for-review, tests

#276 More test content in parser test
  test/parser/parser_test.cpp
Labels: ready-to-merge, tests

#316 LLVM CMake
  cmake_modules/ThirdpartyToolchain.cmake
Labels: infrastructure, ready-for-review

#317 GCC 8 fixes
  src/storage/projected_row.cpp
  test/common/object_pool_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/storage_util_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/util/transaction_test_util.cpp
Labels: best-practice, ready-to-merge

#318 Remove boost from build infrastructure
  Dockerfile
  cmake_modules/ThirdpartyToolchain.cmake
  script/installation/packages.sh
Labels: best-practice, infrastructure, ready-for-review

#322 Quick fix for a cmake typo
  cmake_modules/ThirdpartyToolchain.cmake
Labels: bug, ready-for-review, ready-to-merge

#270 Network layer
  CMakeLists.txt
  Dockerfile
  cmake/Templates/terrier_config.h.in
  cmake_modules/FindLibevent.cmake
  cmake_modules/FindPOSTGRES.cmake
  cmake_modules/FindPQXX.cmake
  cmake_modules/ThirdpartyToolchain.cmake
  script/installation/packages.sh
  src/common/notifiable_task.cpp
  src/common/utility.cpp
  src/include/common/dedicated_thread_owner.h
  src/include/common/dedicated_thread_registry.h
  src/include/common/dedicated_thread_task.h
  src/include/common/event_util.h
  src/include/common/exception.h
  src/include/common/notifiable_task.h
  src/include/common/settings.h
  src/include/common/utility.h
  src/include/loggers/network_logger.h
  src/include/loggers/test_logger.h
  src/include/network/connection_dispatcher_task.h
  src/include/network/connection_handle.h
  src/include/network/connection_handle_factory.h
  src/include/network/connection_handler_task.h
  src/include/network/network_defs.h
  src/include/network/network_io_utils.h
  src/include/network/network_io_wrapper.h
  src/include/network/network_types.h
  src/include/network/postgres_network_commands.h
  src/include/network/postgres_protocol_interpreter.h
  src/include/network/postgres_protocol_utils.h
  src/include/network/protocol_interpreter.h
  src/include/network/terrier_server.h
  src/include/util/portable_endian.h
  src/loggers/network_logger.cpp
  src/loggers/test_logger.cpp
  src/main/terrier.cpp
  src/network/README
  src/network/connection_dispatcher_task.cpp
  src/network/connection_handle.cpp
  src/network/connection_handle_factory.cpp
  src/network/connection_handler_task.cpp
  src/network/network_io_wrapper.cpp
  src/network/postgres_network_commands.cpp
  src/network/postgres_protocol_interpreter.cpp
  src/network/terrier_server.cpp
  test/CMakeLists.txt
  test/include/util/test_harness.h
  test/network/CMakeLists.txt
  test/network/network_test.cpp
Labels: feature

#299 Add Compression to Arrow Experimental
  .travis.yml
  CMakeLists.txt
  Jenkinsfile
  src/include/common/macros.h
  src/include/loggers/type_logger.h
  src/include/parser/expression/abstract_expression.h
  src/include/parser/expression/constant_value_expression.h
  src/include/parser/expression/operator_expression.h
  src/include/parser/expression/parameter_value_expression.h
  src/include/parser/expression/type_cast_expression.h
  src/include/parser/expression_defs.h
  src/include/storage/arrow_block_metadata.h
  src/include/storage/block_compactor.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/storage/tuple_access_strategy.h
  src/include/transaction/transaction_context.h
  src/include/type/transient_value.h
  src/include/type/transient_value_factory.h
  src/include/type/transient_value_peeker.h
  src/include/type/type_id.h
  src/include/type/type_util.h
  src/include/type/value.h
  src/include/type/value_factory.h
  src/loggers/type_logger.cpp
  src/main/terrier.cpp
  src/parser/postgresparser.cpp
  src/storage/block_compactor.cpp
  src/storage/block_layout.cpp
  src/storage/data_table.cpp
  src/storage/garbage_collector.cpp
  src/storage/storage_util.cpp
  src/storage/tuple_access_strategy.cpp
  src/transaction/transaction_manager.cpp
  test/include/util/catalog_test_util.h
  test/include/util/storage_test_util.h
  test/include/util/test_harness.h
  test/parser/expression_test.cpp
  test/parser/parser_test.cpp
  test/storage/block_compactor_test.cpp
  test/storage/bwtree_test.cpp
  test/storage/sql_table_test.cpp
  test/storage/varlen_entry_test.cpp
  test/type/transient_value_test.cpp
  test/type/value_type_test.cpp
  test/util/transaction_test_util.cpp
  third_party/bwtree/bwtree.h
Labels: feature, in-progress

#326 removed dead terrier_config file and references
  CMakeLists.txt
  cmake/Templates/terrier_config.h.in
  src/network/terrier_server.cpp
Labels: best-practice, infrastructure, ready-for-review

#330 GC contention benchmark
  benchmark/storage/garbage_collector_benchmark.cpp
Labels: ready-for-review, tests

#325 Optimize GC
  src/include/storage/garbage_collector.h
  src/storage/garbage_collector.cpp
  src/transaction/transaction_manager.cpp
  test/storage/garbage_collector_test.cpp
Labels: performance, ready-for-review
