Repository cmu-db/noisepage, pull requests merged in 2019-07, with the labels that each got.

#462 Include 'fmt/ostr.h' in all logger header files
  src/include/loggers/catalog_logger.h
  src/include/loggers/index_logger.h
  src/include/loggers/main_logger.h
  src/include/loggers/network_logger.h
  src/include/loggers/parser_logger.h
  src/include/loggers/settings_logger.h
  src/include/loggers/storage_logger.h
  src/include/loggers/test_logger.h
  src/include/loggers/transaction_logger.h
Labels: ready-for-review

#429 Dependency Injection
  src/include/common/object_pool.h
  src/include/di/di_help.h
  src/include/di/injectors.h
  src/include/storage/garbage_collector_thread.h
  src/include/storage/write_ahead_log/log_manager.h
  src/include/transaction/transaction_manager.h
  src/main/terrier.cpp
  test/include/util/transaction_test_util.h
  test/storage/large_garbage_collector_test.cpp
  test/storage/log_test.cpp
  test/transaction/large_transaction_test.cpp
  test/util/transaction_test_util.cpp
  third_party/boost/di/di.h
Labels: best-practice, ready-for-review

#463 unique_ptr and nullptr support for ManagedPointer
  src/include/common/managed_pointer.h
  test/common/managed_pointer_test.cpp
Labels: feature, ready-to-merge

#464 Force boost::di to treat ManagedPointer as a smart pointer
  src/include/di/di_help.h
Labels: bug, ready-to-merge

#465 Removed DedicatedThreadRegistry singleton, networking refactor
  benchmark/integration/tpcc_benchmark.cpp
  benchmark/storage/logging_benchmark.cpp
  src/include/common/dedicated_thread_owner.h
  src/include/common/dedicated_thread_registry.h
  src/include/common/dedicated_thread_task.h
  src/include/common/notifiable_task.h
  src/include/common/settings.h
  src/include/di/injectors.h
  src/include/main/db_main.h
  src/include/network/connection_dispatcher_task.h
  src/include/network/connection_handle_factory.h
  src/include/network/terrier_server.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/include/storage/write_ahead_log/disk_log_consumer_task.h
  src/include/storage/write_ahead_log/log_manager.h
  src/include/storage/write_ahead_log/log_serializer_task.h
  src/main/db_main.cpp
  src/main/terrier.cpp
  src/network/connection_dispatcher_task.cpp
  src/network/terrier_server.cpp
  src/storage/write_ahead_log/log_manager.cpp
  test/CMakeLists.txt
  test/include/util/catalog_test_util.h
  test/integration/tpcc_test.cpp
  test/network/network_test.cpp
  test/settings/settings_test.cpp
  test/storage/large_garbage_collector_test.cpp
  test/storage/log_test.cpp
  test/traffic_cop/traffic_cop_test.cpp
  test/transaction/large_transaction_test.cpp
Labels: ready-for-review

#461 Optimizer Stats: Top-K Tracker
  src/include/loggers/optimizer_logger.h
  src/include/optimizer/statistics/count_min_sketch.h
  src/include/optimizer/statistics/histogram.h
  src/include/optimizer/statistics/top_k_elements.h
  test/optimizer/count_min_sketch_test.cpp
  test/optimizer/histogram_test.cpp
  test/optimizer/top_k_elements_test.cpp
Labels: ready-to-merge

#433 AbstractExpression & TupleValueExpression Fix
  src/common/sql_node_visitor.cpp
  src/include/common/exception.h
  src/include/common/sql_node_visitor.h
  src/include/parser/expression/abstract_expression.h
  src/include/parser/expression/aggregate_expression.h
  src/include/parser/expression/case_expression.h
  src/include/parser/expression/column_value_expression.h
  src/include/parser/expression/comparison_expression.h
  src/include/parser/expression/conjunction_expression.h
  src/include/parser/expression/constant_value_expression.h
  src/include/parser/expression/default_value_expression.h
  src/include/parser/expression/derived_value_expression.h
  src/include/parser/expression/function_expression.h
  src/include/parser/expression/operator_expression.h
  src/include/parser/expression/parameter_value_expression.h
  src/include/parser/expression/star_expression.h
  src/include/parser/expression/subquery_expression.h
  src/include/parser/expression/tuple_value_expression.h
  src/include/parser/expression/type_cast_expression.h
  src/include/parser/expression_defs.h
  src/include/parser/postgresparser.h
  src/include/parser/select_statement.h
  src/include/planner/plannodes/aggregate_plan_node.h
  src/include/planner/plannodes/create_table_plan_node.h
  src/include/type/transient_value.h
  src/include/type/type_util.h
  src/parser/expression/abstract_expression.cpp
  src/parser/expression_defs.cpp
  src/parser/postgresparser.cpp
  test/parser/expression_defs_test.cpp
  test/parser/expression_test.cpp
  test/parser/parser_test.cpp
  test/planner/plan_node_json_test.cpp
  test/planner/plan_node_test.cpp
  test/type/transient_value_test.cpp
  test/type/type_util_test.cpp
Labels: ready-to-merge

#377 Transformation to Arrow
  benchmark/storage/block_compactor_benchmark.cpp
  benchmark/storage/garbage_collector_benchmark.cpp
  src/include/storage/access_observer.h
  src/include/storage/arrow_block_metadata.h
  src/include/storage/block_access_controller.h
  src/include/storage/block_compactor.h
  src/include/storage/data_table.h
  src/include/storage/garbage_collector.h
  src/include/storage/garbage_collector_thread.h
  src/include/storage/storage_util.h
  src/include/storage/tuple_access_strategy.h
  src/include/transaction/transaction_context.h
  src/storage/access_observer.cpp
  src/storage/block_compactor.cpp
  src/storage/data_table.cpp
  src/storage/garbage_collector.cpp
  src/storage/storage_util.cpp
  src/storage/tuple_access_strategy.cpp
  src/transaction/transaction_manager.cpp
  test/catalog/catalog_test.cpp
  test/include/util/storage_test_util.h
  test/storage/access_observer_test.cpp
  test/storage/block_access_controller_test.cpp
  test/storage/block_compactor_test.cpp
  test/storage/bwtree_key_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/large_garbage_collector_test.cpp
  test/storage/log_test.cpp
  test/storage/tuple_access_strategy_test.cpp
  test/transaction/deferred_actions_test.cpp
  test/transaction/large_transaction_test.cpp
Labels: feature, ready-to-merge

#472 Normalize catalog names
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/include/catalog/catalog_accessor.h
  test/catalog/catalog_test.cpp
Labels: bug, ready-to-merge

#480 Fix to null TransientValue serialization
  src/include/type/transient_value.h
  test/parser/expression_test.cpp
Labels: bug, ready-to-merge

#482 Real Murmur3
  third_party/murmur3/MurmurHash3.cpp
  third_party/murmur3/MurmurHash3.h
Labels: ready-for-review

#476 Switch InsertPlanNode.parameter_info to use std::vector
  src/include/planner/plannodes/insert_plan_node.h
  src/planner/plannodes/drop_trigger_plan_node.cpp
  src/planner/plannodes/drop_view_plan_node.cpp
  src/planner/plannodes/insert_plan_node.cpp
  test/planner/plan_node_json_test.cpp
Labels: beginner, ready-to-merge
