Repository cmu-db/noisepage, pull requests merged in 2019-02, with the labels that each got.

#289 Fix cases where committed transactions may be empty
  test/util/transaction_test_util.cpp
Labels: bug, ready-to-merge, tests

#290 type::TransientValue
  .travis.yml
  Jenkinsfile
  src/include/loggers/type_logger.h
  src/include/parser/expression/abstract_expression.h
  src/include/parser/expression/constant_value_expression.h
  src/include/parser/expression/operator_expression.h
  src/include/parser/expression/parameter_value_expression.h
  src/include/storage/storage_util.h
  src/include/type/transient_value.h
  src/include/type/transient_value_factory.h
  src/include/type/transient_value_peeker.h
  src/include/type/type_id.h
  src/include/type/type_util.h
  src/include/type/value.h
  src/include/type/value_factory.h
  src/loggers/type_logger.cpp
  src/main/terrier.cpp
  src/parser/postgresparser.cpp
  test/include/util/catalog_test_util.h
  test/include/util/test_harness.h
  test/parser/expression_test.cpp
  test/parser/parser_test.cpp
  test/type/transient_value_test.cpp
  test/type/value_type_test.cpp
Labels: feature, ready-for-review

#292 Adding more parser tests for coverage
  test/parser/parser_test.cpp
Labels: ready-to-merge, tests

#284 Quickfix parser
  src/parser/postgresparser.cpp
  test/parser/parser_test.cpp
Labels: bug, ready-for-review

#293 bwtree: reconcile mapping table discrepancy, add recycling of NodeIds
  third_party/bwtree/bwtree.h
Labels: bug, ready-to-merge

#294 Fix bwtree tests for odd numbered hardware_concurrency()
  test/storage/bwtree_test.cpp
Labels: bug, ready-for-review, tests

#295 Merge CAST() and ExpressionType::OPERATOR_CAST
  src/include/parser/expression/type_cast_expression.h
  src/include/parser/expression_defs.h
  src/parser/postgresparser.cpp
  test/parser/parser_test.cpp
Labels: feature, ready-to-merge

#301 NUM_RESERVED_COLUMNS fix
  CMakeLists.txt
  src/storage/block_layout.cpp
  src/storage/storage_util.cpp
  test/include/util/storage_test_util.h
Labels: bug, ready-to-merge

#303 Remove gtest dependency from terrier lib
  src/include/common/macros.h
  src/include/type/transient_value.h
Labels: best-practice, ready-to-merge

#305 Cleanup main
  cmake_modules/BuildUtils.cmake
  src/main/terrier.cpp
  test/common/stat_registry_test.cpp
Labels: best-practice, ready-for-review

#288 Add early stop for sequential scans down a partially filled block
  src/include/storage/data_table.h
  src/storage/data_table.cpp
  test/storage/data_table_test.cpp
Labels: feature, ready-to-merge

#286 Add flags to VarlenEntry (#285)
  src/include/storage/storage_defs.h
  src/storage/data_table.cpp
  src/storage/garbage_collector.cpp
  src/transaction/transaction_manager.cpp
  test/include/util/storage_test_util.h
  test/storage/sql_table_test.cpp
  test/storage/varlen_entry_test.cpp
Labels: feature, ready-to-merge
