Repository cmu-db/noisepage, pull requests merged in 2019-08, with the labels that each got.

#481 Persist columns
  build-support/bad_words.txt
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/include/catalog/database_catalog.h
  src/include/catalog/index_schema.h
  src/include/catalog/postgres/pg_attribute.h
  src/include/catalog/schema.h
  src/include/storage/index/index_builder.h
Labels: bug, feature, ready-to-merge

#486 Search path fix
  src/catalog/catalog.cpp
  src/catalog/catalog_accessor.cpp
  src/include/catalog/catalog.h
  src/include/catalog/catalog_accessor.h
  test/catalog/catalog_test.cpp
Labels: feature, ready-for-review

#494 Fix doxygen for CatalogAccessor
  src/include/catalog/catalog_accessor.h
Labels: bug, ready-to-merge

#493 Fix block access controller test
  src/include/storage/block_access_controller.h
  test/storage/block_access_controller_test.cpp
Labels: bug, ready-to-merge

#491 CMake cleanup, jemalloc flag
  .travis.yml
  CMakeLists.txt
  Jenkinsfile
  benchmark/CMakeLists.txt
  cmake_modules/Findjemalloc.cmake
  cmake_modules/SetupCxxFlags.cmake
  cmake_modules/ThirdpartyToolchain.cmake
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: infrastructure, ready-to-merge

#495 Jenkins: Release build compiles with stricter warning level
  .travis.yml
  Jenkinsfile
  test/include/util/manual_packet_util.h
Labels: infrastructure, ready-to-merge

#496 Jenkins: Enable jemalloc for benchmark build on Jenkins
  Jenkinsfile
Labels: infrastructure, ready-to-merge

#499 Reset benchmark lookback due to jemalloc being enabled
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, tests

#497 Add bwtree_benchmark to the nightly suite
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, ready-to-merge, tests

#500 Fix to pg_namespace index
  src/catalog/database_catalog.cpp
Labels: bug, ready-to-merge

#501 LLVM 8 and accompanying CI checks
  .clang-tidy
  .travis.yml
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  benchmark/storage/block_compactor_benchmark.cpp
  benchmark/util/transaction_benchmark_util.cpp
  cmake_modules/FindClangTools.cmake
  cmake_modules/ThirdpartyToolchain.cmake
  script/installation/packages.sh
  src/catalog/catalog.cpp
  src/common/notifiable_task.cpp
  src/include/common/container/bitmap.h
  src/include/common/container/concurrent_vector.h
  src/include/common/exception.h
  src/include/network/postgres/postgres_protocol_utils.h
  src/include/parser/table_ref.h
  src/include/planner/plannodes/insert_plan_node.h
  src/include/planner/plannodes/result_plan_node.h
  src/include/storage/block_layout.h
  src/include/storage/data_table.h
  src/include/storage/projected_columns.h
  src/include/storage/record_buffer.h
  src/include/storage/storage_defs.h
  src/include/transaction/transaction_manager.h
  src/parser/postgresparser.cpp
  src/planner/plannodes/csv_scan_plan_node.cpp
  src/storage/projected_columns.cpp
  src/storage/write_ahead_log/log_serializer_task.cpp
  src/transaction/transaction_manager.cpp
  test/common/bitmap_test.cpp
  test/common/concurrent_bitmap_test.cpp
  test/common/hash_util_test.cpp
  test/common/worker_pool_test.cpp
  test/include/util/random_test_util.h
  test/include/util/storage_test_util.h
  test/include/util/transaction_test_util.h
  test/storage/block_compactor_test.cpp
  test/storage/bwtree_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/log_test.cpp
  test/util/tpcc/order_status.cpp
  test/util/tpcc/payment.cpp
  test/util/transaction_test_util.cpp
Labels: best-practice, infrastructure, ready-to-merge

#502 Canonical schemas
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/builder.h
  src/include/catalog/postgres/pg_attribute.h
  test/catalog/catalog_test.cpp
Labels: feature, in-progress

#507 Decouple projection maps
  src/catalog/catalog.cpp
  src/catalog/database_catalog.cpp
  src/include/storage/sql_table.h
  src/storage/sql_table.cpp
  test/include/util/tpcc/delivery.h
  test/include/util/tpcc/loader.h
  test/include/util/tpcc/new_order.h
  test/include/util/tpcc/order_status.h
  test/include/util/tpcc/payment.h
  test/include/util/tpcc/stock_level.h
  test/include/util/tpcc/worker.h
  test/storage/bwtree_index_test.cpp
  test/storage/bwtree_key_test.cpp
  test/storage/log_test.cpp
Labels: feature, ready-for-review

#509 Be smarter about Column copies
  src/include/catalog/schema.h
  test/include/util/tpcc/util.h
Labels: performance, ready-to-merge, tests

#508 Add clang-8 builds to Linux CI
  .travis.yml
  Jenkinsfile
Labels: infrastructure, ready-to-merge, tests

#511 Add 'timeout' for Ubuntu and 'gtimeout' for macOS
  Jenkinsfile
  script/installation/packages.sh
Labels: infrastructure, ready-to-merge

#512 Update packages.sh
  script/installation/packages.sh
Labels: bug, infrastructure

#521 Bump CMake minimum version from 3.2 to 3.8
  CMakeLists.txt
Labels: best-practice, infrastructure, ready-for-review
