Repository cmu-db/noisepage, pull requests merged in 2019-11, with the labels that each got.

#609 Parser Microbenchmark
  benchmark/CMakeLists.txt
  benchmark/parser/CMakeLists.txt
  benchmark/parser/parser_benchmark.cpp
  cmake_modules/BuildUtils.cmake
  cmake_modules/CompilerInfo.cmake
  cmake_modules/FindClangTools.cmake
  cmake_modules/FindGBenchmark.cmake
  cmake_modules/FindGFlags.cmake
  cmake_modules/FindGTest.cmake
  cmake_modules/Findjemalloc.cmake
  cmake_modules/SetupCxxFlags.cmake
  cmake_modules/ThirdpartyToolchain.cmake
  cmake_modules/san-config.cmake
  script/micro_bench/run_micro_bench.py
  test/parser/parser_test.cpp
Labels: ready-for-review

#618 Update LLVM_DIR for macOS
  .travis.yml
  Jenkinsfile
Labels: bug, infrastructure

#620 Fix InputPacket::Clear() to reset extended_ flag
  src/include/network/network_defs.h
  src/include/network/protocol_interpreter.h
  test/network/network_test.cpp
Labels: bug, ready-to-merge

#621 Remove shared_ptr from the network layer
  src/include/network/connection_handle.h
  src/include/network/itp/itp_command_factory.h
  src/include/network/itp/itp_network_commands.h
  src/include/network/itp/itp_packet_writer.h
  src/include/network/itp/itp_protocol_interpreter.h
  src/include/network/network_command.h
  src/include/network/network_defs.h
  src/include/network/network_io_utils.h
  src/include/network/network_io_wrapper.h
  src/include/network/packet_writer.h
  src/include/network/postgres/postgres_command_factory.h
  src/include/network/postgres/postgres_network_commands.h
  src/include/network/postgres/postgres_packet_writer.h
  src/include/network/postgres/postgres_protocol_interpreter.h
  src/include/network/protocol_interpreter.h
  src/network/connection_handle.cpp
  src/network/itp/itp_command_factory.cpp
  src/network/itp/itp_protocol_interpreter.cpp
  src/network/network_io_wrapper.cpp
  src/network/postgres/postgres_command_factory.cpp
  src/network/postgres/postgres_protocol_interpreter.cpp
  src/network/postgres/postgres_protocol_utils.cpp
  test/network/network_test.cpp
Labels: best-practice

#619 Remove DI framework
  src/include/common/object_pool.h
  src/include/di/di_help.h
  src/include/di/injectors.h
  src/include/metrics/metrics_thread.h
  src/include/network/network_io_utils.h
  src/include/network/packet_writer.h
  src/include/storage/garbage_collector_thread.h
  src/include/storage/write_ahead_log/log_manager.h
  src/include/transaction/transaction_manager.h
  src/storage/data_table.cpp
  test/storage/large_garbage_collector_test.cpp
  test/storage/log_test.cpp
  test/transaction/large_transaction_test.cpp
  third_party/boost/di/di.h
Labels: ready-for-review

#599 Add wrapper around Linux perf events. Renamed CPU timer to reflect rusage
  cmake_modules/SetupCxxFlags.cmake
  src/include/common/perf_monitor.h
  src/include/common/rusage_monitor.h
  src/include/common/thread_cpu_timer.h
  test/common/perf_monitor_test.cpp
  test/common/rusage_monitor_test.cpp
  test/common/thread_cpu_timer_test.cpp
  test/integration/tpcc_test.cpp
Labels: feature, ready-to-merge

#625 Refactor pointers in Operator and OperatorExpression
  src/include/optimizer/operator_expression.h
  src/include/optimizer/operator_node.h
  src/include/optimizer/query_to_operator_transformer.h
  src/optimizer/logical_operators.cpp
  src/optimizer/operator_node.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/query_to_operator_transformer.cpp
  test/optimizer/operator_expression_test.cpp
  test/optimizer/operator_transformer_test.cpp
Labels: best-practice, ready-to-merge

#628 Fix CMake goof on macOS
  cmake_modules/SetupCxxFlags.cmake
Labels: bug, infrastructure

#580 Restructure Jenkins pipeline
  Jenkinsfile
Labels: infrastructure, tests

#401 Banning shared_ptr and std::cerr
  CMakeLists.txt
  build-support/bad_words.txt
  src/include/catalog/index_schema.h
  src/include/loggers/binder_logger.h
  src/include/loggers/catalog_logger.h
  src/include/loggers/execution_logger.h
  src/include/loggers/index_logger.h
  src/include/loggers/main_logger.h
  src/include/loggers/network_logger.h
  src/include/loggers/optimizer_logger.h
  src/include/loggers/parser_logger.h
  src/include/loggers/settings_logger.h
  src/include/loggers/storage_logger.h
  src/include/loggers/test_logger.h
  src/include/loggers/transaction_logger.h
  src/include/main/db_main.h
  src/include/optimizer/statistics/value_condition.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_common.h
  src/include/settings/settings_manager.h
  src/include/settings/settings_param.h
  src/include/traffic_cop/portal.h
  src/include/traffic_cop/sqlite.h
  src/loggers/binder_logger.cpp
  src/loggers/catalog_logger.cpp
  src/loggers/execution_logger.cpp
  src/loggers/index_logger.cpp
  src/loggers/main_logger.cpp
  src/loggers/network_logger.cpp
  src/loggers/optimizer_logger.cpp
  src/loggers/parser_logger.cpp
  src/loggers/settings_logger.cpp
  src/loggers/storage_logger.cpp
  src/loggers/test_logger.cpp
  src/loggers/transaction_logger.cpp
  src/main/db_main.cpp
  src/main/terrier.cpp
  src/network/postgres/postgres_network_commands.cpp
  src/settings/settings_callbacks.cpp
  src/settings/settings_manager.cpp
  src/traffic_cop/sqlite.cpp
  test/metrics/metrics_test.cpp
  test/optimizer/value_condition_test.cpp
  test/settings/settings_test.cpp
Labels: best-practice, infrastructure, ready-to-merge

#613 data table benchmarking
  benchmark/storage/data_table_benchmark.cpp
Labels: ready-to-merge, tests

#627 Extern templates for indexes
  src/include/common/object_pool.h
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/compact_ints_key.h
  src/include/storage/index/generic_key.h
  src/include/storage/index/hash_index.h
  src/include/storage/index/hash_key.h
  src/include/storage/write_ahead_log/disk_log_consumer_task.h
  src/include/storage/write_ahead_log/log_serializer_task.h
  src/storage/index/bwtree_index.cpp
  src/storage/index/compact_ints_key.cpp
  src/storage/index/generic_key.cpp
  src/storage/index/hash_index.cpp
  src/storage/index/hash_key.cpp
Labels: best-practice, infrastructure, ready-to-merge

#639 Update openssl Homebrew package to 1.1 for macOS
  script/installation/packages.sh
Labels: infrastructure, ready-to-merge

#640 Relax metrics_test strictness due to timing issues in CI
  test/metrics/metrics_test.cpp
Labels: infrastructure, tests

#641 DDL lock in DatabaseCatalog
  src/catalog/database_catalog.cpp
  src/include/catalog/database_catalog.h
  src/include/storage/recovery/recovery_manager.h
  src/transaction/transaction_manager.cpp
  test/catalog/catalog_test.cpp
  test/test_util/tpcc/builder.cpp
Labels: feature, ready-to-merge

#636 CREATE/DROP plan node cleanup and executors
  src/catalog/catalog.cpp
  src/catalog/database_catalog.cpp
  src/execution/sql/ddl_executors.cpp
  src/include/catalog/catalog_accessor.h
  src/include/execution/sql/ddl_executors.h
  src/include/parser/parser_defs.h
  src/include/planner/plannodes/create_database_plan_node.h
  src/include/planner/plannodes/create_function_plan_node.h
  src/include/planner/plannodes/create_index_plan_node.h
  src/include/planner/plannodes/create_namespace_plan_node.h
  src/include/planner/plannodes/create_table_plan_node.h
  src/include/planner/plannodes/create_trigger_plan_node.h
  src/include/planner/plannodes/create_view_plan_node.h
  src/include/planner/plannodes/drop_database_plan_node.h
  src/include/planner/plannodes/drop_index_plan_node.h
  src/include/planner/plannodes/drop_namespace_plan_node.h
  src/include/planner/plannodes/drop_table_plan_node.h
  src/include/planner/plannodes/drop_trigger_plan_node.h
  src/include/planner/plannodes/drop_view_plan_node.h
  src/parser/postgresparser.cpp
  src/planner/plannodes/create_database_plan_node.cpp
  src/planner/plannodes/create_index_plan_node.cpp
  src/planner/plannodes/create_namespace_plan_node.cpp
  src/planner/plannodes/create_table_plan_node.cpp
  src/planner/plannodes/drop_database_plan_node.cpp
  src/planner/plannodes/drop_index_plan_node.cpp
  src/planner/plannodes/drop_namespace_plan_node.cpp
  src/planner/plannodes/drop_table_plan_node.cpp
  test/catalog/catalog_test.cpp
  test/execution/ddl_executors_test.cpp
  test/parser/parser_test.cpp
  test/planner/plan_node_json_test.cpp
  test/planner/plan_node_test.cpp
  test/storage/recovery_test.cpp
Labels: ready-to-merge

#642 More GCC 8+ fixes
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  src/catalog/database_catalog.cpp
  src/execution/vm/bytecode_emitter.cpp
  src/include/execution/sql/concise_hash_table.h
  src/include/storage/index/generic_key.h
  src/storage/block_compactor.cpp
  test/execution/projected_columns_iterator_test.cpp
  test/optimizer/logical_operator_test.cpp
  test/storage/index_key_test.cpp
  third_party/madoka/sketch.cc
Labels: infrastructure, ready-to-merge
