Repository cmu-db/noisepage, pull requests merged in 2020-06, with the labels that each got.

#934 Abort running txn on disconnect
  script/testing/junit/src/TrafficCopTest.java
  src/network/postgres/postgres_protocol_interpreter.cpp
Labels: bug, ready-to-merge

#933 Extended query fixes
  script/testing/junit/src/WireTest.java
  src/include/network/network_io_utils.h
  src/include/network/postgres/postgres_protocol_interpreter.h
  src/include/network/postgres/statement.h
  src/network/postgres/postgres_network_commands.cpp
  src/network/postgres/statement.cpp
Labels: bug, ready-to-merge

#924 Updated third_party nlohmann::json library
  src/parser/expression/constant_value_expression.cpp
  third_party/nlohmann/adl_serializer.hpp
  third_party/nlohmann/detail/conversions/from_json.hpp
  third_party/nlohmann/detail/conversions/to_chars.hpp
  third_party/nlohmann/detail/conversions/to_json.hpp
  third_party/nlohmann/detail/exceptions.hpp
  third_party/nlohmann/detail/input/binary_reader.hpp
  third_party/nlohmann/detail/input/input_adapters.hpp
  third_party/nlohmann/detail/input/lexer.hpp
  third_party/nlohmann/detail/input/parser.hpp
  third_party/nlohmann/detail/iterators/internal_iterator.hpp
  third_party/nlohmann/detail/iterators/iter_impl.hpp
  third_party/nlohmann/detail/iterators/iteration_proxy.hpp
  third_party/nlohmann/detail/iterators/json_reverse_iterator.hpp
  third_party/nlohmann/detail/iterators/primitive_iterator.hpp
  third_party/nlohmann/detail/json_pointer.hpp
  third_party/nlohmann/detail/json_ref.hpp
  third_party/nlohmann/detail/macro_scope.hpp
  third_party/nlohmann/detail/macro_unscope.hpp
  third_party/nlohmann/detail/meta.hpp
  third_party/nlohmann/detail/output/binary_writer.hpp
  third_party/nlohmann/detail/output/output_adapters.hpp
  third_party/nlohmann/detail/output/serializer.hpp
  third_party/nlohmann/detail/value_t.hpp
  third_party/nlohmann/json.hpp
  third_party/nlohmann/json_fwd.hpp
Labels: ready-to-merge

#935 Binder fast path for cached prepared statements
  apidoc/Doxyfile.in
  benchmark/runner/mini_runners.cpp
  script/testing/junit/src/TrafficCopTest.java
  src/binder/bind_node_visitor.cpp
  src/binder/binder_sherpa.cpp
  src/binder/binder_util.cpp
  src/include/binder/bind_node_visitor.h
  src/include/binder/binder_sherpa.h
  src/include/binder/binder_util.h
  src/include/network/network_util.h
  src/include/network/postgres/postgres_protocol_interpreter.h
  src/include/network/postgres/statement.h
  src/include/network/postgres/statement_cache.h
  src/include/parser/expression/abstract_expression.h
  src/network/postgres/postgres_network_commands.cpp
  src/network/postgres/statement.cpp
  src/traffic_cop/traffic_cop.cpp
  test/binder/binder_test.cpp
  test/optimizer/index_nested_loops_join_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/test_util/tpcc/tpcc_plan_test.cpp
  test/test_util/tpcc/workload_cached.cpp
Labels: bug, performance, ready-to-merge

#930 [issue-822] save CTest output in Jenkins builds
  CMakeLists.txt
  Jenkinsfile
  cmake_modules/ThirdpartyToolchain.cmake
  script/jenkins/benchmark-agent-setup.sh
  script/jenkins/docker-agent-setup.sh
  test/CTestCustom.cmake
Labels: infrastructure, tests

#940 Improving compilation time
  benchmark/integration/tpcc_benchmark.cpp
  benchmark/metrics/logging_metrics_benchmark.cpp
  benchmark/runner/transaction_logging_gc_runner.cpp
  benchmark/storage/logging_benchmark.cpp
  src/common/time_util.cpp
  src/execution/compiler/codegen.cpp
  src/include/catalog/catalog.h
  src/include/catalog/postgres/builder.h
  src/include/catalog/postgres/pg_attribute.h
  src/include/catalog/postgres/pg_class.h
  src/include/catalog/postgres/pg_constraint.h
  src/include/catalog/postgres/pg_database.h
  src/include/catalog/postgres/pg_index.h
  src/include/catalog/postgres/pg_language.h
  src/include/catalog/postgres/pg_namespace.h
  src/include/catalog/postgres/pg_proc.h
  src/include/catalog/postgres/pg_type.h
  src/include/catalog/schema.h
  src/include/common/gate.h
  src/include/common/managed_pointer.h
  src/include/execution/sql/index_iterator.h
  src/include/execution/sql/value.h
  src/include/optimizer/expression_node_contents.h
  src/include/parser/expression_defs.h
  src/include/planner/plannodes/output_schema.h
  src/include/planner/plannodes/result_plan_node.h
  src/include/storage/access_observer.h
  src/include/storage/data_table.h
  src/include/storage/index/compact_ints_key.h
  src/include/storage/index/hash_key.h
  src/include/storage/index/index.h
  src/include/storage/recovery/recovery_manager.h
  src/include/storage/sql_table.h
  src/include/storage/write_ahead_log/log_manager.h
  src/include/transaction/transaction_context.h
  src/include/util/time_util.h
  src/parser/expression_defs.cpp
  src/storage/garbage_collector.cpp
  src/storage/recovery/recovery_manager.cpp
  src/storage/write_ahead_log/log_manager.cpp
  test/execution/expression_util.cpp
  test/include/execution/compiler/expression_util.h
  test/include/test_util/storage_test_util.h
  test/include/test_util/tpcc/delivery.h
  test/include/test_util/tpcc/order_status.h
  test/include/test_util/tpcc/payment.h
  test/include/test_util/tpcc/stock_level.h
  test/include/test_util/tpcc/workload_cached.h
  test/include/test_util/tpch/workload.h
  test/parser/expression_defs_test.cpp
  test/storage/export_table_test.cpp
  test/util/time_util_test.cpp
Labels: ready-to-merge

#939 Unify the time unit for intervals to microseconds.
  benchmark/integration/tpcc_benchmark.cpp
  benchmark/metrics/garbage_collection_metrics_benchmark.cpp
  benchmark/metrics/large_transaction_metrics_benchmark.cpp
  benchmark/metrics/logging_metrics_benchmark.cpp
  benchmark/runner/transaction_logging_gc_runner.cpp
  benchmark/storage/index_wrapper_benchmark.cpp
  benchmark/storage/logging_benchmark.cpp
  benchmark/transaction/large_transaction_benchmark.cpp
  src/include/main/db_main.h
  src/include/metrics/metrics_thread.h
  src/include/settings/settings_defs.h
  src/include/storage/garbage_collector_thread.h
  src/include/storage/write_ahead_log/disk_log_consumer_task.h
  src/include/storage/write_ahead_log/log_manager.h
  src/storage/garbage_collector_thread.cpp
  src/storage/write_ahead_log/disk_log_consumer_task.cpp
  src/storage/write_ahead_log/log_serializer_task.cpp
Labels: ready-to-merge

#954 Update libcount to Prashanth's version.
  src/execution/sql/aggregation_hash_table.cpp
  src/include/optimizer/statistics/hyperloglog.h
  third_party/libcount/AUTHORS
  third_party/libcount/README.md
  third_party/libcount/c.cc
  third_party/libcount/hll.cc
  third_party/libcount/hll.h
  third_party/libcount/utility.cc
  third_party/libcount/utility.h
  third_party/versions.txt
Labels: ready-to-merge

#953 StorageInterface instantiates PRI once
  src/execution/compiler/operator/delete_translator.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/storage_interface.cpp
  src/include/execution/sql/storage_interface.h
  src/include/storage/projected_row.h
Labels: performance, ready-to-merge

#957 Compile speed up changes
  benchmark/storage/recovery_benchmark.cpp
  src/brain/operating_unit_recorder.cpp
  src/catalog/catalog.cpp
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/expression/function_translator.cpp
  src/execution/compiler/expression/pr_filler.cpp
  src/execution/compiler/operator/delete_translator.cpp
  src/execution/compiler/operator/index_join_translator.cpp
  src/execution/compiler/operator/index_scan_translator.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/execution/compiler/pipeline.cpp
  src/execution/exec/execution_context.cpp
  src/execution/sql/index_iterator.cpp
  src/include/brain/operating_unit_recorder.h
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/builder.h
  src/include/catalog/postgres/pg_class.h
  src/include/common/spin_latch.h
  src/include/execution/compiler/codegen.h
  src/include/execution/compiler/expression/pr_filler.h
  src/include/execution/compiler/operator/delete_translator.h
  src/include/execution/compiler/operator/index_join_translator.h
  src/include/execution/exec/execution_context.h
  src/include/execution/exec/output.h
  src/include/execution/sql/index_iterator.h
  src/include/execution/sql/storage_interface.h
  src/include/execution/sql/value.h
  src/include/execution/util/hash.h
  src/include/network/postgres/portal.h
  src/include/optimizer/index_util.h
  src/include/optimizer/plan_generator.h
  src/include/planner/plannodes/plan_node_defs.h
  src/include/storage/index/index.h
  test/include/test_util/tpcc/database.h
  util/execution/tpl.cpp
Labels: best-practice, ready-to-merge

#959 Add support for formatted strings in exceptions
  src/include/common/exception.h
  src/parser/expression/aggregate_expression.cpp
Labels: feature, ready-to-merge

#962 Manually deregister exception frames
  src/execution/vm/llvm_engine.cpp
Labels: bug, ready-to-merge

#965 Binder error messages returned to client
  script/testing/junit/out/options.xml
  script/testing/junit/src/TrafficCopTest.java
  src/binder/bind_node_visitor.cpp
  src/binder/binder_context.cpp
  src/include/network/postgres/postgres_packet_writer.h
  src/network/postgres/postgres_network_commands.cpp
  src/network/postgres/postgres_protocol_interpreter.cpp
  src/traffic_cop/traffic_cop.cpp
  test/traffic_cop/traffic_cop_test.cpp
Labels: best-practice, ready-to-merge

#966 Add a small sleep to DisconnectAbort JUnit test
  script/testing/junit/src/TrafficCopTest.java
Labels: tests

#952 Per-connection CatalogCache prototype
  benchmark/catalog/catalog_benchmark.cpp
  benchmark/runner/mini_runners.cpp
  benchmark/storage/recovery_benchmark.cpp
  src/binder/bind_node_visitor.cpp
  src/catalog/catalog.cpp
  src/catalog/catalog_accessor.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/operator/delete_translator.cpp
  src/execution/compiler/operator/index_join_translator.cpp
  src/execution/compiler/operator/index_scan_translator.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/execution/sql/storage_interface.cpp
  src/include/catalog/catalog.h
  src/include/catalog/catalog_accessor.h
  src/include/catalog/catalog_cache.h
  src/include/network/connection_context.h
  src/include/storage/index/index.h
  src/include/storage/index/index_defs.h
  src/include/storage/recovery/recovery_manager.h
  src/traffic_cop/traffic_cop.cpp
  test/binder/binder_test.cpp
  test/catalog/catalog_test.cpp
  test/execution/ddl_executors_test.cpp
  test/include/execution/sql_test.h
  test/optimizer/index_nested_loops_join_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/test_util/sql_table_test_util.cpp
  test/test_util/tpcc/builder.cpp
  test/test_util/tpcc/tpcc_plan_test.cpp
  test/test_util/tpcc/workload_cached.cpp
  test/test_util/tpch/workload.cpp
  test/traffic_cop/traffic_cop_test.cpp
  util/execution/tpl.cpp
Labels: performance, ready-to-merge

#974 PostgresPacketWriter cleanup
  src/include/network/packet_writer.h
  src/include/network/postgres/postgres_packet_writer.h
  src/network/postgres/postgres_packet_writer.cpp
Labels: best-practice, ready-for-review

#963 Faster Timestamps
  .gitignore
  sample_tpl/types/timestamps.tpl
  src/binder/binder_sherpa.cpp
  src/binder/binder_util.cpp
  src/common/time_util.cpp
  src/execution/compiler/codegen.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/runtime_types.cpp
  src/execution/vm/bytecode_emitter.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/binder/binder_sherpa.h
  src/include/execution/ast/builtins.h
  src/include/execution/sql/runtime_types.h
  src/include/execution/sql/value.h
  src/include/execution/vm/bytecode_emitter.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/util/time_util.h
  src/network/postgres/postgres_packet_util.cpp
  test/CMakeLists.txt
  test/execution/expression_util.cpp
  test/execution/runtime_types_test.cpp
  test/include/execution/compiler/expression_util.h
  test/optimizer/tpcc_plan_delivery_test.cpp
  test/util/CMakeLists.txt
  test/util/time_util_test.cpp
  third_party/date/date.h
Labels: performance, ready-for-review

#970 Dedicated test for BinderUtil::CheckAndTryPromoteType
  src/binder/binder_util.cpp
  test/binder/binder_util_test.cpp
Labels: ready-to-merge, tests

#921 JUnit: add QueryMode option from command line
  .gitignore
  script/testing/README.md
  script/testing/junit/.gitignore
  script/testing/junit/constants.py
  script/testing/junit/run_junit.py
  script/testing/junit/src/TestUtility.java
  script/testing/junit/test_junit.py
  script/testing/oltpbench/run_oltpbench.py
  script/testing/oltpbench/test_oltpbench.py
  script/testing/util/common.py
  script/testing/util/test_server.py
Labels: infrastructure, ready-to-merge, tests

#975 Set client_time as 60 seconds in nightly jenkins job
  Jenkinsfile-nightly
Labels: tests

#980 Move index wrapper definitions to cpp files
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/hash_index.h
  src/include/storage/index/index.h
  src/storage/block_compactor.cpp
  src/storage/index/bwtree_index.cpp
  src/storage/index/hash_index.cpp
  src/storage/recovery/recovery_manager.cpp
Labels: best-practice, ready-to-merge

#981 Fix for AVX512 on macOS
  src/include/execution/util/simd/avx512.h
Labels: bug, ready-to-merge

#983 Error framework, including parser failures
  Jenkinsfile
  script/testing/junit/src/TrafficCopTest.java
  src/binder/bind_node_visitor.cpp
  src/binder/binder_context.cpp
  src/binder/binder_sherpa.cpp
  src/binder/binder_util.cpp
  src/execution/sql/runtime_types.cpp
  src/include/binder/bind_node_visitor.h
  src/include/binder/binder_util.h
  src/include/catalog/postgres/name_builder.h
  src/include/common/error/error_code.h
  src/include/common/error/error_data.h
  src/include/common/error/error_defs.h
  src/include/common/error/exception.h
  src/include/common/event_util.h
  src/include/network/connection_handle.h
  src/include/network/connection_handler_task.h
  src/include/network/network_defs.h
  src/include/network/network_io_utils.h
  src/include/network/network_io_wrapper.h
  src/include/network/postgres/postgres_defs.h
  src/include/network/postgres/postgres_packet_writer.h
  src/include/network/postgres/postgres_protocol_util.h
  src/include/network/postgres/statement.h
  src/include/network/terrier_server.h
  src/include/optimizer/expression_node_contents.h
  src/include/parser/create_statement.h
  src/include/parser/expression/aggregate_expression.h
  src/include/parser/sql_statement.h
  src/include/settings/settings_manager.h
  src/include/traffic_cop/traffic_cop.h
  src/include/traffic_cop/traffic_cop_defs.h
  src/include/type/type_util.h
  src/network/postgres/postgres_network_commands.cpp
  src/network/postgres/postgres_packet_writer.cpp
  src/network/postgres/postgres_protocol_interpreter.cpp
  src/network/postgres/statement.cpp
  src/optimizer/optimizer.cpp
  src/optimizer/plan_generator.cpp
  src/parser/expression_defs.cpp
  src/parser/postgresparser.cpp
  src/traffic_cop/traffic_cop.cpp
  test/execution/runtime_types_test.cpp
  test/optimizer/index_nested_loops_join_test.cpp
  test/parser/expression_defs_test.cpp
  test/parser/parser_test.cpp
  test/traffic_cop/traffic_cop_test.cpp
Labels: best-practice, bug, feature, ready-to-merge

#985 Move IndexBuilder definition to cpp
  src/include/storage/index/index_builder.h
  src/storage/index/index_builder.cpp
  util/execution/table_generator/table_reader.cpp
Labels: best-practice, ready-to-merge

#984 Memory usage estimates, miscellaneous #include cleanups
  benchmark/integration/tpcc_benchmark.cpp
  benchmark/runner/tpcc_runner.cpp
  benchmark/runner/tpch_runner.cpp
  benchmark/storage/index_wrapper_benchmark.cpp
  src/catalog/catalog.cpp
  src/catalog/postgres/builder.cpp
  src/include/catalog/catalog.h
  src/include/catalog/catalog_accessor.h
  src/include/catalog/catalog_cache.h
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/pg_attribute.h
  src/include/catalog/postgres/pg_constraint.h
  src/include/catalog/postgres/pg_database.h
  src/include/catalog/postgres/pg_index.h
  src/include/main/db_main.h
  src/include/storage/data_table.h
  src/include/storage/garbage_collector.h
  src/include/storage/garbage_collector_thread.h
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/hash_index.h
  src/include/storage/index/index.h
  src/include/storage/sql_table.h
  src/include/storage/storage_defs.h
  src/include/transaction/deferred_action_manager.h
  src/include/transaction/transaction_defs.h
  src/include/transaction/transaction_manager.h
  src/planner/plannodes/create_function_plan_node.cpp
  src/planner/plannodes/insert_plan_node.cpp
  src/storage/garbage_collector.cpp
  src/storage/index/bwtree_index.cpp
  src/storage/index/hash_index.cpp
  src/storage/recovery/recovery_manager.cpp
  test/execution/pr_filler_test.cpp
  test/storage/bwtree_index_test.cpp
  test/storage/hash_index_test.cpp
  test/storage/index_key_test.cpp
Labels: best-practice, feature, ready-to-merge

#986 Clean up optimizer includes a bit
  src/include/optimizer/cost_model/trivial_cost_model.h
  src/include/optimizer/input_column_deriver.h
  src/include/optimizer/logical_operators.h
  src/include/optimizer/operator_visitor.h
  src/include/optimizer/optimizer_context.h
  src/include/optimizer/physical_operators.h
  src/include/optimizer/plan_generator.h
  src/optimizer/binding.cpp
  src/optimizer/child_property_deriver.cpp
  src/optimizer/cost_model/trivial_cost_model.cpp
  src/optimizer/optimizer_context.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/optimizer/rules/rewrite_rules.cpp
  src/optimizer/rules/transformation_rules.cpp
  src/optimizer/rules/unnesting_rules.cpp
  src/optimizer/statistics/child_stats_deriver.cpp
  src/optimizer/statistics/stats_calculator.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/optimizer_context_test.cpp
Labels: best-practice, ready-to-merge

#987 Changes to speed up compilation
  benchmark/runner/mini_runners.cpp
  benchmark/runner/transaction_logging_gc_runner.cpp
  src/binder/bind_node_visitor.cpp
  src/include/binder/bind_node_visitor.h
  src/include/binder/binder_context.h
  src/include/binder/binder_sherpa.h
  src/include/catalog/catalog.h
  src/include/catalog/catalog_accessor.h
  src/include/common/dedicated_thread_registry.h
  src/include/execution/executable_query.h
  src/include/main/db_main.h
  src/include/metrics/metrics_manager.h
  src/include/metrics/metrics_store.h
  src/include/network/connection_handle_factory.h
  src/include/network/postgres/statement.h
  src/include/optimizer/abstract_optimizer.h
  src/include/optimizer/index_util.h
  src/include/optimizer/rules/implementation_rules.h
  src/include/parser/expression/comparison_expression.h
  src/include/parser/postgresparser.h
  src/include/storage/sql_table.h
  src/include/storage/write_ahead_log/disk_log_consumer_task.h
  src/include/storage/write_ahead_log/log_manager.h
  src/include/traffic_cop/traffic_cop.h
  src/include/transaction/transaction_manager.h
  src/main/db_main.cpp
  src/metrics/metrics_manager.cpp
  src/parser/postgresparser.cpp
  src/storage/sql_table.cpp
  src/traffic_cop/traffic_cop.cpp
  src/traffic_cop/traffic_cop_util.cpp
  test/binder/binder_test.cpp
  test/execution/aggregation_hash_table_test.cpp
  test/execution/join_hash_table_vector_probe_test.cpp
  test/execution/pr_filler_test.cpp
  test/execution/projected_columns_iterator_test.cpp
  test/network/network_test.cpp
  test/parser/parser_test.cpp
  util/include/execution/table_generator/schema_reader.h
Labels: ready-to-merge

#991 Remove common/stat_registry.h and common/performance_counter.h
  src/include/common/performance_counter.h
  src/include/common/performance_counter_body.h
  src/include/common/stat_registry.h
  src/include/main/db_main.h
  src/include/storage/data_table.h
  src/include/storage/index/index.h
  src/main/terrier.cpp
  src/storage/data_table.cpp
  test/common/performance_counter_test.cpp
  test/common/stat_registry_test.cpp
  test/include/common/performance_counter_test.h
  test/include/common/stat_registry_test.h
Labels: ready-for-review

#941 Improve Logging Efficiency and Performance
  script/testing/oltpbench/run_oltpbench.py
  src/include/storage/write_ahead_log/log_serializer_task.h
  src/storage/write_ahead_log/log_serializer_task.cpp
Labels: ready-to-merge

#988 Add support for version() builtin
  src/catalog/database_catalog.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/functions/system_functions.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/catalog/postgres/pg_proc.h
  src/include/common/version.h
  src/include/execution/ast/builtins.h
  src/include/execution/sql/functions/system_functions.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/network/postgres/postgres_defs.h
  test/execution/system_functions_test.cpp
Labels: ready-for-review

#989 Remove namespace oids where appropriate
  src/include/optimizer/logical_operators.h
  src/include/optimizer/physical_operators.h
  src/include/planner/plannodes/abstract_scan_plan_node.h
  src/include/planner/plannodes/csv_scan_plan_node.h
  src/include/planner/plannodes/delete_plan_node.h
  src/include/planner/plannodes/drop_view_plan_node.h
  src/include/planner/plannodes/index_scan_plan_node.h
  src/include/planner/plannodes/insert_plan_node.h
  src/include/planner/plannodes/seq_scan_plan_node.h
  src/include/planner/plannodes/update_plan_node.h
  src/optimizer/logical_operators.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/optimizer/rules/rewrite_rules.cpp
  src/planner/plannodes/abstract_scan_plan_node.cpp
  src/planner/plannodes/delete_plan_node.cpp
  src/planner/plannodes/drop_view_plan_node.cpp
  src/planner/plannodes/insert_plan_node.cpp
  src/planner/plannodes/update_plan_node.cpp
  test/execution/compiler_test.cpp
  test/optimizer/logical_operator_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/optimizer_context_test.cpp
  test/optimizer/physical_operator_test.cpp
  test/optimizer/tpcc_plan_delivery_test.cpp
  test/optimizer/tpcc_plan_index_scan.cpp
  test/optimizer/tpcc_plan_neworder_test.cpp
  test/optimizer/tpcc_plan_payment_test.cpp
  test/optimizer/tpcc_plan_seq_scan.cpp
  test/planner/plan_node_json_test.cpp
  test/planner/plan_node_test.cpp
  test/test_util/tpcc/tpcc_plan_test.cpp
Labels: best-practice, ready-to-merge
