Repository cmu-db/noisepage, pull requests merged in 2020-02, with the labels that each got.

#705 Reconcile Optimizer and Codegen.
  src/execution/compiler/codegen.cpp
  src/execution/compiler/expression/star_translator.cpp
  src/execution/compiler/operator/aggregate_translator.cpp
  src/execution/compiler/operator/hash_join_translator.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/execution/compiler/translator_factory.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_emitter.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/execution/compiler/codegen.h
  src/include/execution/compiler/expression/star_translator.h
  src/include/execution/compiler/operator/hash_join_translator.h
  src/include/execution/compiler/operator/projection_translator.h
  src/include/execution/compiler/operator/seq_scan_translator.h
  src/include/execution/compiler/translator_factory.h
  src/include/execution/sql/value.h
  src/include/execution/vm/bytecode_emitter.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/parser/expression/star_expression.h
  src/include/parser/expression_util.h
  src/include/planner/plannodes/plan_node_defs.h
  src/main/terrier.cpp
  test/execution/compiler_test.cpp
  test/include/execution/compiler/expression_util.h
  test/include/execution/compiler/output_schema_util.h
  test/parser/expression_test.cpp
Labels: bug, ready-to-merge

#727 Implement Date and Timestamp support
  sample_tpl/tpl_tests.txt
  sample_tpl/types/timestamps.tpl
  src/binder/bind_node_visitor.cpp
  src/binder/binder_context.cpp
  src/execution/ast/ast_dump.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/expression/param_value_translator.cpp
  src/execution/exec/output.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/runtime_types.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/llvm_engine.cpp
  src/execution/vm/vm.cpp
  src/include/binder/bind_node_visitor.h
  src/include/binder/binder_context.h
  src/include/binder/binder_util.h
  src/include/execution/ast/ast.h
  src/include/execution/ast/builtins.h
  src/include/execution/ast/type.h
  src/include/execution/compiler/codegen.h
  src/include/execution/compiler/translator_factory.h
  src/include/execution/sql/functions/comparison_functions.h
  src/include/execution/sql/runtime_types.h
  src/include/execution/sql/value.h
  src/include/execution/util/hash.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/network/postgres/postgres_packet_writer.h
  src/include/parser/expression/constant_value_expression.h
  src/include/storage/projected_columns.h
  src/include/type/transient_value.h
  src/include/type/type_id.h
  src/include/util/time_util.h
  test/execution/compiler_test.cpp
  test/execution/date_functions_test.cpp
  test/execution/is_null_predicate_test.cpp
  test/include/execution/compiler/expression_util.h
  test/include/execution/compiler/output_checker.h
  test/optimizer/tpcc_plan_neworder_test.cpp
  test/optimizer/tpcc_plan_payment_test.cpp
  test/util/time_util_test.cpp
  util/execution/tpl.cpp
Labels: feature, ready-for-review

#735 IndexScan Table Alias Fix
  src/include/optimizer/physical_operators.h
  src/optimizer/child_property_deriver.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/rules/implementation_rules.cpp
  test/optimizer/physical_operator_test.cpp
Labels: ready-for-review

#738 TerrierServer throws on socket already in use, DBMain catches and returns
  src/main/db_main.cpp
  src/network/terrier_server.cpp
Labels: bug, ready-to-merge

#736 Fix bugs found with TATP.
  src/execution/compiler/expression/comparison_translator.cpp
  src/execution/vm/vm.cpp
  src/include/optimizer/plan_generator.h
  src/optimizer/plan_generator.cpp
  test/include/test_util/tpcc/tpcc_plan_test.h
  test/optimizer/tpcc_plan_delivery_test.cpp
  test/optimizer/tpcc_plan_index_scan.cpp
  test/optimizer/tpcc_plan_neworder_test.cpp
  test/optimizer/tpcc_plan_payment_test.cpp
  test/optimizer/tpcc_plan_seq_scan.cpp
  test/test_util/tpcc/tpcc_plan_test.cpp
Labels: bug, ready-to-merge

#751 Variable Change Tolerance for Microbenchmarks
  script/micro_bench/run_micro_bench.py
Labels: in-progress, infrastructure

#658 pg_language and pg_proc catalog tables
  src/binder/bind_node_visitor.cpp
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/include/binder/bind_node_visitor.h
  src/include/catalog/catalog_accessor.h
  src/include/catalog/catalog_defs.h
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/builder.h
  src/include/catalog/postgres/pg_language.h
  src/include/catalog/postgres/pg_proc.h
  src/include/catalog/postgres/pg_type.h
  src/include/parser/expression/function_expression.h
  src/include/storage/storage_defs.h
  src/include/storage/storage_util.h
  src/include/type/type_id.h
  src/storage/recovery/recovery_manager.cpp
  test/binder/binder_test.cpp
  test/catalog/catalog_test.cpp
  test/storage/varlen_entry_test.cpp
Labels: feature, in-progress, ready-for-review

#749 Unique indexes for CREATE TABLE
  src/execution/sql/ddl_executors.cpp
  src/include/planner/plannodes/create_table_plan_node.h
  test/optimizer/operator_transformer_test.cpp
Labels: feature, ready-to-merge

#760 Race Condition Fix in ConnectionHandlerTask
  src/include/network/connection_handler_task.h
  src/network/connection_handler_task.cpp
  test/network/network_test.cpp
Labels: ready-for-review, ready-to-merge

#742 DatabaseCatalog registers and unregisters indexes for GC
  benchmark/benchmark_util/data_table_benchmark_util.cpp
  benchmark/catalog/catalog_benchmark.cpp
  benchmark/integration/tpcc_benchmark.cpp
  benchmark/storage/block_compactor_benchmark.cpp
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/index_wrapper_benchmark.cpp
  benchmark/storage/recovery_benchmark.cpp
  benchmark/storage/slot_iterator_benchmark.cpp
  src/catalog/catalog.cpp
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/execution/sql/ddl_executors.cpp
  src/include/catalog/catalog.h
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/builder.h
  src/include/main/db_main.h
  src/include/storage/data_table.h
  src/include/storage/sql_table.h
  src/storage/data_table.cpp
  src/storage/recovery/recovery_manager.cpp
  src/storage/sql_table.cpp
  test/binder/binder_test.cpp
  test/catalog/catalog_test.cpp
  test/common/stat_registry_test.cpp
  test/execution/filter_manager_test.cpp
  test/include/execution/sql_test.h
  test/include/test_util/tpcc/util.h
  test/integration/tpcc_test.cpp
  test/metrics/metrics_test.cpp
  test/network/network_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/storage/block_compactor_test.cpp
  test/storage/bwtree_index_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/delta_record_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/hash_index_test.cpp
  test/storage/index_key_test.cpp
  test/storage/log_test.cpp
  test/storage/recovery_test.cpp
  test/test_util/data_table_test_util.cpp
  test/test_util/sql_table_test_util.cpp
  test/test_util/tpcc/builder.cpp
  test/transaction/mvcc_test.cpp
  util/execution/table_generator/table_generator.cpp
  util/execution/tpl.cpp
  util/include/execution/table_generator/table_generator.h
Labels: ready-to-merge

#765 Improved distribution checking in packages.sh
  script/installation/packages.sh
Labels: infrastructure, ready-to-merge

#757 Operator expression/node class name changes
  src/include/optimizer/abstract_optimizer.h
  src/include/optimizer/binding.h
  src/include/optimizer/group.h
  src/include/optimizer/group_expression.h
  src/include/optimizer/input_column_deriver.h
  src/include/optimizer/logical_operators.h
  src/include/optimizer/memo.h
  src/include/optimizer/operator_expression.h
  src/include/optimizer/operator_node.h
  src/include/optimizer/operator_node_contents.h
  src/include/optimizer/optimizer.h
  src/include/optimizer/optimizer_context.h
  src/include/optimizer/pattern.h
  src/include/optimizer/physical_operators.h
  src/include/optimizer/plan_generator.h
  src/include/optimizer/property_enforcer.h
  src/include/optimizer/query_to_operator_transformer.h
  src/include/optimizer/rule.h
  src/include/optimizer/rules/implementation_rules.h
  src/include/optimizer/rules/rewrite_rules.h
  src/include/optimizer/rules/transformation_rules.h
  src/include/optimizer/rules/unnesting_rules.h
  src/optimizer/binding.cpp
  src/optimizer/input_column_deriver.cpp
  src/optimizer/logical_operators.cpp
  src/optimizer/operator_node_contents.cpp
  src/optimizer/optimizer.cpp
  src/optimizer/optimizer_task.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/optimizer/rules/rewrite_rules.cpp
  src/optimizer/rules/transformation_rules.cpp
  src/optimizer/rules/unnesting_rules.cpp
  src/traffic_cop/traffic_cop_util.cpp
  test/optimizer/logical_operator_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/optimizer_context_test.cpp
  test/optimizer/physical_operator_test.cpp
Labels: best-practice, ready-to-merge

#769 Remove unnecessary make in Jenkins' "Check" stage
  Jenkinsfile
Labels: infrastructure, ready-to-merge

#741 Improve the performance of check-clang-tidy
  build-support/run-clang-tidy.py
  build-support/run_clang_tidy_extra.py
Labels: infrastructure, ready-for-review

#772 Network Layer Multiple Connection Fixes
  src/include/network/connection_handle_factory.h
  src/include/network/postgres/postgres_protocol_interpreter.h
  src/network/connection_handle_factory.cpp
  src/network/postgres/postgres_protocol_interpreter.cpp
  test/include/test_util/manual_packet_util.h
  test/network/network_test.cpp
Labels: ready-to-merge

#778 Random Fixes Feb2020: sorter_test / postgres_protocol / build-support
  CMakeLists.txt
  build-support/data/README.md
  build-support/data/bad_words.txt
  build-support/data/clangformat_suppressions.txt
  build-support/data/lsan_suppressions.txt
  build-support/data/sanitize_suppressions.txt
  build-support/data/valgrind_suppressions.txt
  build-support/run-test.sh
  cmake_modules/BuildUtils.cmake
  cmake_modules/san-config.cmake
  src/include/network/packet_writer.h
  src/include/network/postgres/postgres_defs.h
  src/include/network/postgres/postgres_packet_writer.h
  src/include/network/postgres/postgres_protocol_util.h
  src/include/traffic_cop/traffic_cop.h
  src/network/postgres/postgres_protocol_util.cpp
  test/execution/sorter_test.cpp
  test/network/postgres_protocol_util_test.cpp
Labels: ready-for-review

#777 Allow Arithmetic Expressions in INSERT
  src/binder/bind_node_visitor.cpp
  src/parser/postgresparser.cpp
  test/parser/parser_test.cpp
Labels: ready-to-merge

#761 Add NameBuilder Utility
  src/include/catalog/postgres/name_builder.h
  src/include/network/postgres/postgres_defs.h
  src/include/planner/plannodes/create_table_plan_node.h
  test/catalog/name_builder_test.cpp
  test/optimizer/operator_transformer_test.cpp
Labels: ready-to-merge

#787 Upgraded libpqxx + Disable NetworkTest::RacerTest
  Dockerfile
  script/installation/packages.sh
  test/network/network_test.cpp
Labels: infrastructure, ready-for-review

#768 Add support for NULL.
  sample_tpl/tpl_tests.txt
  sample_tpl/types/nulls.tpl
  src/binder/bind_node_visitor.cpp
  src/execution/ast/context.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/expression/null_check_translator.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/builtins.h
  src/include/execution/ast/type.h
  src/include/execution/compiler/codegen.h
  src/include/execution/compiler/translator_factory.h
  src/include/execution/sema/sema.h
  src/include/execution/sql/functions/is_null_predicate.h
  src/include/execution/sql/value.h
  src/include/execution/vm/bytecode_generator.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/network/postgres/postgres_packet_writer.h
  src/include/parser/expression/comparison_expression.h
  test/execution/is_null_predicate_test.cpp
Labels: feature, ready-to-merge

#745 Junit testframework and pipeline
  script/testing/junit/InsertPSTest.java
  script/testing/junit/InsertTPCCTest.java
  script/testing/junit/InsertTest.java
  script/testing/junit/PLTestBase.java
  script/testing/junit/TPCCBootstrapTest.java
  script/testing/junit/TestUtility.java
  script/testing/junit/UpdateTest.java
Labels: in-progress, ready-for-review

#796 Clang-format not returning non-zero exit on failure fix
  build-support/run_clang_format.py
Labels: bug, infrastructure, ready-to-merge

#798 Modify cmake to Build Benchmarks without Building Tests
  Jenkinsfile
  test/CMakeLists.txt
Labels: infrastructure, ready-for-review

#795 Alias Renaming Fix
  script/testing/junit/InsertTest.java
  script/testing/junit/SelectTest.java
  src/include/network/postgres/postgres_packet_writer.h
  src/include/parser/expression/abstract_expression.h
  src/parser/postgresparser.cpp
Labels: ready-to-merge
