Repository cmu-db/noisepage, pull requests merged in 2020-10, with the labels that each got.

#1168 Fix index joins using inequality predicates
  script/testing/junit/traces/select.test
  src/optimizer/index_util.cpp
Labels: bug, ready-to-merge

#1199 SQLite Test Traces: Support for Error Flag + Value List
  Jenkinsfile
  script/testing/junit/README.md
  script/testing/junit/src/FilterTrace.java
  script/testing/junit/src/GenerateTrace.java
  script/testing/junit/src/TracefileTest.java
  script/testing/junit/src/moglib/Constants.java
  script/testing/junit/src/moglib/MogDb.java
  script/testing/junit/src/moglib/MogSqlite.java
  script/testing/junit/traces/functions.test
Labels: in-progress, tests

#1217 Simplify select
  src/storage/data_table.cpp
Labels: best-practice, performance, ready-to-merge

#1214 Fixes struct padding for TPL #1210
  sample_tpl/struct-padding.tpl
  sample_tpl/tpl_tests.txt
  src/execution/ast/context.cpp
  src/execution/ast/type.cpp
  src/execution/ast/type_printer.cpp
  src/execution/vm/llvm_engine.cpp
  src/include/execution/ast/type.h
  test/execution/ast_type_test.cpp
Labels: ready-to-merge

#1138 Nested Query Support
  script/testing/junit/src/TestUtility.java
  script/testing/junit/traces/nested-query.test
  src/execution/compiler/compilation_context.cpp
  src/execution/compiler/expression/comparison_translator.cpp
  src/execution/sql/ddl_executors.cpp
  src/include/execution/sql/ddl_executors.h
  src/include/optimizer/child_property_deriver.h
  src/include/optimizer/cost_model/trivial_cost_model.h
  src/include/optimizer/input_column_deriver.h
  src/include/optimizer/operator_visitor.h
  src/include/optimizer/optimizer_defs.h
  src/include/optimizer/physical_operators.h
  src/include/optimizer/plan_generator.h
  src/include/optimizer/rule.h
  src/include/optimizer/rules/implementation_rules.h
  src/include/optimizer/rules/unnesting_rules.h
  src/include/parser/expression/abstract_expression.h
  src/optimizer/child_property_deriver.cpp
  src/optimizer/input_column_deriver.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/rule.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/optimizer/rules/rewrite_rules.cpp
  src/optimizer/rules/unnesting_rules.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/physical_operator_test.cpp
Labels: feature, ready-to-merge

#1189 Allow SET to accept values that come in as VARCHAR despite having a different type.
  src/settings/settings_manager.cpp
Labels: bug

#1185 Add PR and Issue Templates
  .github/pull_request_template.md
Labels: best-practice, ready-to-merge

#1122 DISTINCT aggregation fix
  script/testing/junit/src/TracefileTest.java
  script/testing/junit/traces/aggregations.test
  src/execution/compiler/operator/distinct_aggregation_util.cpp
  src/execution/compiler/operator/hash_aggregation_translator.cpp
  src/execution/compiler/operator/static_aggregation_translator.cpp
  src/execution/compiler/pipeline.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/type.h
  src/include/execution/compiler/operator/distinct_aggregation_util.h
  src/include/execution/compiler/operator/hash_aggregation_translator.h
  src/include/execution/compiler/operator/static_aggregation_translator.h
  src/include/execution/sql/aggregators.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
Labels: bug, ready-to-merge

#1231 Ubuntu 20.04 fixes for packages.sh and Jenkinsfile
  Jenkinsfile
  script/installation/packages.sh
Labels: infrastructure

#1233 Ubuntu 20.04 OLTPBench testing update
  Dockerfile
  script/installation/packages.sh
  script/testing/oltpbench/reporting/parse_data.py
Labels: infrastructure, tests

#1235 WAL: Remove redundant call between serializer and disk consumer
  src/include/storage/write_ahead_log/disk_log_consumer_task.h
  src/storage/write_ahead_log/disk_log_consumer_task.cpp
  src/storage/write_ahead_log/log_manager.cpp
  src/storage/write_ahead_log/log_serializer_task.cpp
Labels: bug, ready-to-merge

#1190 psutil for pid and check port
  .gitignore
  Jenkinsfile
  script/installation/packages.sh
  script/testing/check_pids.py
  script/testing/kill_server.py
  script/testing/util/common.py
  script/testing/util/constants.py
  script/testing/util/test_server.py
Labels: ready-to-merge

#1242 Prevent pyc bytecode generation when sudo in Jenkins.
  Jenkinsfile
Labels: infrastructure, ready-for-review

#1247 Fail fast on Jenkins without "ready" GitHub labels.
  Jenkinsfile
  build-support/check_github_labels.py
Labels: infrastructure, ready-for-review

#1249 Modify check_github_labels script to scrape the PR page if rate-limited.
  build-support/check_github_labels.py
Labels: infrastructure, ready-for-review

#1256 Fix check_github_labels.py script.
  build-support/check_github_labels.py
Labels: ready-for-ci

#1257 Add explicit dependencies to CMake and -GNinja to nightly.
  CMakeLists.txt
  Jenkinsfile-nightly
Labels: infrastructure

#1258 Add ENABLE_EXPORTS ON to benchmark targets.
  CMakeLists.txt
Labels: infrastructure

#1259 Add all weird CMake dependencies to noisepage_objlib instead of real targets.
  CMakeLists.txt
Labels: infrastructure

#1260 Add CMake dependencies with add_custom_command instead of add_dependencies.
  CMakeLists.txt
Labels: infrastructure

#1248 Fix for SELECT Table Qualifier
  script/testing/junit/traces/select.test
  src/binder/bind_node_visitor.cpp
  src/binder/binder_context.cpp
  src/binder/sql_node_visitor.cpp
  src/include/binder/bind_node_visitor.h
  src/include/binder/binder_context.h
  src/include/binder/sql_node_visitor.h
  src/include/parser/expression/table_star_expression.h
  src/include/parser/expression_defs.h
  src/parser/expression/abstract_expression.cpp
  src/parser/expression/table_star_expression.cpp
  src/parser/expression_defs.cpp
  src/parser/postgresparser.cpp
  test/parser/expression_defs_test.cpp
  test/parser/parser_test.cpp
Labels: ready-for-ci, ready-to-merge

#1262 CMake: Apply +x to build-support for CLion's remote host compatibility.
  CMakeLists.txt
Labels: infrastructure, ready-for-ci, ready-to-merge

#1244 Enable some DISTINCT-related tests that were disabled during the initial TPL2 port.
  test/execution/compiler_test.cpp
Labels: best-practice, ready-for-ci, ready-to-merge, tests

#1202 Fix visiting SQL values in bytecode generation.
  sample_tpl/return-sql.tpl
  sample_tpl/tpl_tests.txt
  script/testing/junit/traces/functions_trig.test
  src/execution/vm/bytecode_generator.cpp
  src/include/execution/vm/bytecode_generator.h
Labels: bug, ready-for-ci, ready-to-merge

#1264 Abort (instead of failing) builds that are not labeled "ready-for-ci".
  Jenkinsfile
Labels: best-practice, infrastructure, ready-for-ci

#1246 Fix SELECT NULL and SELECT * crashing the DBMS.
  build-support/check_github_labels.py
  script/testing/junit/traces/select.test
  src/binder/bind_node_visitor.cpp
Labels: bug, ready-for-ci, ready-to-merge

#850 Rewrite Slot Iterator
  benchmark/benchmark_util/data_table_benchmark_util.cpp
  benchmark/include/benchmark_util/data_table_benchmark_util.h
  benchmark/storage/slot_iterator_benchmark.cpp
  src/include/storage/block_compactor.h
  src/include/storage/data_table.h
  src/storage/access_observer.cpp
  src/storage/arrow_serializer.cpp
  src/storage/data_table.cpp
  src/transaction/transaction_manager.cpp
  test/include/test_util/data_table_test_util.h
  test/include/test_util/multithread_test_util.h
  test/include/test_util/storage_test_util.h
  test/storage/data_table_test.cpp
  test/storage/export_table_test.cpp
Labels: ready-for-ci, ready-to-merge

#1127 Improved performance of AccessCurrentThreadState in ThreadStatecontainer.
  src/execution/sql/thread_state_container.cpp
  src/include/execution/exec/execution_context.h
  src/include/execution/sql/thread_state_container.h
Labels: performance, ready-for-ci, ready-to-merge

#1265 Port NoisePage wiki to a docs/ folder.
  README.md
  apidoc/Doxyfile.in
  docs/README.md
  docs/cpp_guidelines.md
  docs/cpp_guidelines_code_style.md
  docs/design_catalog.md
  docs/design_log_manager.md
  docs/design_messenger.md
  docs/design_storage.md
  docs/discussion_ddl_implementation.md
  docs/profiling.md
  docs/tech_clangtools.md
  docs/tech_clion.md
  docs/tech_docker.md
  docs/tech_git.md
  docs/tech_jenkins.md
  docs/tech_valgrind.md
Labels: best-practice

#1269 Fix Memory Tracking Issue (#1250)
  src/include/execution/sql/memory_tracker.h
Labels: ready-to-merge

#1273 Fixes `nested-query.test` by providing a canonical sort order
  script/testing/junit/traces/nested-query.test
Labels: bug, ready-for-ci, ready-for-review

#1271 Fix double parsing
  CMakeLists.txt
  src/execution/sql/operators/cast_operators.cpp
  src/execution/util/csv_reader.cpp
  src/execution/util/fast_double_parser.cpp
  src/include/execution/util/fast_double_parser.h
  test/execution/sql_vector_operations_vector_cast_test.cpp
Labels: bug, ready-for-ci, ready-for-review

#1275 Re-enable TPCC tests.
  test/integration/tpcc_test.cpp
Labels: best-practice, ready-for-ci, tests

#1240 Microbenchmark Test Script Metric Collection & Refactor
  Dockerfile
  Jenkinsfile
  Jenkinsfile-nightly
  script/installation/packages.sh
  script/micro_bench/.gitignore
  script/micro_bench/run_micro_bench.py
  script/testing/.pep8
  script/testing/README.md
  script/testing/microbench/README.md
  script/testing/microbench/__init__.py
  script/testing/microbench/artifact_processor.py
  script/testing/microbench/benchmarks.py
  script/testing/microbench/config.py
  script/testing/microbench/constants.py
  script/testing/microbench/google_benchmark/__init__.py
  script/testing/microbench/google_benchmark/gbench2junit.py
  script/testing/microbench/google_benchmark/gbench_historical_results.py
  script/testing/microbench/google_benchmark/gbench_run_result.py
  script/testing/microbench/google_benchmark/gbench_test_result.py
  script/testing/microbench/jenkins/jenkins.py
  script/testing/microbench/micro_benchmarks_runner.py
  script/testing/microbench/results_output.py
  script/testing/microbench/run_microbench.py
  script/testing/oltpbench/constants.py
  script/testing/oltpbench/reporting/constants.py
  script/testing/oltpbench/reporting/parse_data.py
  script/testing/oltpbench/reporting/report_result.py
  script/testing/oltpbench/run_oltpbench.py
  script/testing/oltpbench/test_case_oltp.py
  script/testing/oltpbench/utils.py
  script/testing/reporting/__init__.py
  script/testing/reporting/constants.py
  script/testing/reporting/parsers/__init__.py
  script/testing/reporting/parsers/microbenchmark/__init__.py
  script/testing/reporting/parsers/microbenchmark/config_parser.py
  script/testing/reporting/parsers/oltpbench/__init__.py
  script/testing/reporting/parsers/oltpbench/config_parser.py
  script/testing/reporting/parsers/oltpbench/res_parser.py
  script/testing/reporting/parsers/oltpbench/summary_parser.py
  script/testing/reporting/parsers/parse_data.py
  script/testing/reporting/report_result.py
  script/testing/reporting/utils.py
  script/testing/util/constants.py
Labels: ready-to-merge, tests

#1201 Add a Messenger subsystem.
  CMakeLists.txt
  Jenkinsfile
  build-support/data/ctest_resource_specs.json
  cmake_modules/FindZMQ.cmake
  script/installation/packages.sh
  src/include/common/error/exception.h
  src/include/loggers/messenger_logger.h
  src/include/main/db_main.h
  src/include/messenger/connection_destination.h
  src/include/messenger/messenger.h
  src/include/messenger/messenger_defs.h
  src/loggers/loggers_util.cpp
  src/loggers/messenger_logger.cpp
  src/main/noisepage.cpp
  src/messenger/connection_destination.cpp
  src/messenger/messenger.cpp
  test/messenger/messenger_test.cpp
Labels: feature, infrastructure, ready-for-ci

#1280 Graceful Failures in Nightly Build
  Jenkinsfile-nightly
Labels: ready-for-ci, ready-for-review

#1281 Fix spdlog in CMake.
  CMakeLists.txt
Labels: infrastructure

#1278 Disable messenger by default.
  src/include/main/db_main.h
  src/include/settings/settings_defs.h
  src/main/noisepage.cpp
  test/messenger/messenger_test.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1276 Fix RecoveryTest::UnrecoverableTransactionTest
  src/include/main/db_main.h
  src/include/transaction/deferred_action_manager.h
Labels: bug, infrastructure, ready-for-ci, ready-to-merge

#1285 Fix clang-tidy.
  Jenkinsfile
  src/messenger/messenger.cpp
Labels: infrastructure, ready-for-ci, ready-to-merge

#1286 Fix UPDATE foo SET a=a in the binder.
  script/testing/junit/traces/update.test
  src/binder/bind_node_visitor.cpp
Labels: bug, ready-for-ci, ready-to-merge
