Repository cmu-db/noisepage, pull requests merged in 2020-12, with the labels that each got.

#1364 Add support for NOT IN.
  script/testing/junit/traces/select.test
  src/parser/postgresparser.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1344 Refactor pg_proc logic out of DatabaseCatalog.
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/catalog/postgres/pg_proc_impl.cpp
  src/include/catalog/catalog_accessor.h
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/pg_proc.h
  src/include/catalog/postgres/pg_proc_impl.h
  src/include/storage/projected_row.h
  src/include/storage/recovery/recovery_manager.h
  src/storage/recovery/recovery_manager.cpp
  test/binder/binder_test.cpp
  test/catalog/catalog_test.cpp
  test/test_util/tpch/tpch_query.cpp
Labels: best-practice, ready-for-ci, ready-to-merge

#1358 Refactor pg core tables out of DatabaseCatalog + general catalog cleanup.
  docs/cpp_guidelines.md
  docs/cpp_guidelines_code_style.md
  src/catalog/catalog.cpp
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/catalog/postgres/pg_constraint_impl.cpp
  src/catalog/postgres/pg_core_impl.cpp
  src/catalog/postgres/pg_language_impl.cpp
  src/catalog/postgres/pg_proc_impl.cpp
  src/catalog/postgres/pg_type_impl.cpp
  src/include/catalog/catalog_accessor.h
  src/include/catalog/catalog_column_def.h
  src/include/catalog/database_catalog.h
  src/include/catalog/index_schema.h
  src/include/catalog/postgres/pg_attribute.h
  src/include/catalog/postgres/pg_class.h
  src/include/catalog/postgres/pg_constraint.h
  src/include/catalog/postgres/pg_constraint_impl.h
  src/include/catalog/postgres/pg_core_impl.h
  src/include/catalog/postgres/pg_database.h
  src/include/catalog/postgres/pg_index.h
  src/include/catalog/postgres/pg_language.h
  src/include/catalog/postgres/pg_language_impl.h
  src/include/catalog/postgres/pg_namespace.h
  src/include/catalog/postgres/pg_proc.h
  src/include/catalog/postgres/pg_proc_impl.h
  src/include/catalog/postgres/pg_type.h
  src/include/catalog/postgres/pg_type_impl.h
  src/include/catalog/schema.h
  src/include/storage/projected_row.h
  src/include/storage/recovery/recovery_manager.h
  src/include/type/type_id.h
  src/storage/recovery/recovery_manager.cpp
  test/catalog/catalog_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/storage/recovery_test.cpp
Labels: best-practice, ready-for-ci, ready-to-merge

#1375 Artifact Stats: Binary Size Collector #1365
  script/testing/artifact_stats/README.md
  script/testing/artifact_stats/collectors/__init__.py
  script/testing/artifact_stats/collectors/binary_size.py
Labels: infrastructure

#1369 Fix UPDATE behavior when SET clauses reference other columns.
  script/testing/junit/traces/update.test
  src/execution/compiler/operator/update_translator.cpp
  src/optimizer/plan_generator.cpp
  test/optimizer/tpcc_plan_delivery_test.cpp
  test/optimizer/tpcc_plan_neworder_test.cpp
  test/optimizer/tpcc_plan_payment_test.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1382 Disable BwTreeTests
  test/storage/bwtree_test.cpp
Labels: ready-for-ci, ready-to-merge, tests

#1389 Hardcode LLVM_DIR to llvm@8 path on OSX.
  Jenkinsfile
  script/installation/packages.sh
Labels: infrastructure, ready-for-ci

#1391 Drop macOS support.
  Jenkinsfile
  README.md
  docs/README.md
Labels: infrastructure, ready-for-ci

#1387 Implement a hacky version of SHOW for transaction_isolation.
  src/include/binder/sql_node_visitor.h
  src/include/network/network_defs.h
  src/include/network/network_util.h
  src/include/parser/parser_defs.h
  src/include/parser/postgresparser.h
  src/include/parser/statements.h
  src/include/parser/variable_show_statement.h
  src/include/traffic_cop/traffic_cop.h
  src/network/postgres/postgres_network_commands.cpp
  src/network/postgres/postgres_packet_writer.cpp
  src/parser/postgresparser.cpp
  src/traffic_cop/traffic_cop.cpp
  src/traffic_cop/traffic_cop_util.cpp
Labels: ready-for-ci, ready-to-merge

#1373 Modeling Index Inserts and Deletes
  benchmark/runner/mini_runners.cpp
  script/model/data_class/grouped_op_unit_data.py
  script/model/training_util/data_transforming_util.py
  script/model/training_util/global_data_constructing_util.py
  script/model/type.py
  src/execution/compiler/operator/delete_translator.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/include/common/perf_monitor.h
  src/include/execution/compiler/executable_query.h
  src/include/optimizer/physical_operators.h
  src/include/parser/expression/column_value_expression.h
  src/include/planner/plannodes/delete_plan_node.h
  src/include/planner/plannodes/insert_plan_node.h
  src/include/planner/plannodes/update_plan_node.h
  src/include/self_driving/modeling/operating_unit.h
  src/include/self_driving/modeling/operating_unit_defs.h
  src/include/self_driving/modeling/operating_unit_recorder.h
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/planner/plannodes/delete_plan_node.cpp
  src/planner/plannodes/insert_plan_node.cpp
  src/planner/plannodes/update_plan_node.cpp
  src/self_driving/modeling/operating_unit.cpp
  src/self_driving/modeling/operating_unit_recorder.cpp
  src/self_driving/modeling/operating_unit_util.cpp
  test/execution/compiler_test.cpp
  test/optimizer/physical_operator_test.cpp
  util/execution/table_generator/table_generator.cpp
  util/include/execution/table_generator/table_generator.h
  util/include/runner/mini_runners_argument_generator.h
  util/include/runner/mini_runners_data_config.h
  util/include/runner/mini_runners_settings.h
  util/runner/mini_runners_argument_generator.cpp
  util/runner/mini_runners_settings.cpp
Labels: ready-for-ci, ready-to-merge

#1388 Fix passing false arguments to testing scripts. Add dry-run functionality.
  script/testing/oltpbench/test_oltpbench.py
  script/testing/oltpbench/utils.py
  script/testing/util/common.py
  script/testing/util/db_server.py
  script/testing/util/test_server.py
Labels: ready-for-ci, ready-for-review

#1288 Model Server Manager Infrastructure for Pilot
  CMakeLists.txt
  Jenkinsfile
  script/installation/packages.sh
  script/model/mini_trainer.py
  script/model/model_server.py
  src/include/loggers/model_server_logger.h
  src/include/main/db_main.h
  src/include/self_driving/model_server/model_server_manager.h
  src/include/settings/settings_defs.h
  src/loggers/loggers_util.cpp
  src/loggers/model_server_logger.cpp
  src/messenger/messenger.cpp
  src/self_driving/model_server/model_server_manager.cpp
  test/messenger/messenger_test.cpp
  test/self_driving/modeling_test.cpp
Labels: ready-for-ci, ready-to-merge

#1392 Fix OpUnit that was renamed, causing modeling_test failures.
  test/self_driving/modeling_test.cpp
Labels: ready-for-ci, ready-to-merge

#1386 Add SanctionedSharedPtr and refactor loggers to use it.
  src/include/common/sanctioned_shared_pointer.h
  src/include/loggers/README.md
  src/include/loggers/binder_logger.h
  src/include/loggers/catalog_logger.h
  src/include/loggers/common_logger.h
  src/include/loggers/execution_logger.h
  src/include/loggers/index_logger.h
  src/include/loggers/loggers_util.h
  src/include/loggers/messenger_logger.h
  src/include/loggers/metrics_logger.h
  src/include/loggers/network_logger.h
  src/include/loggers/optimizer_logger.h
  src/include/loggers/parser_logger.h
  src/include/loggers/settings_logger.h
  src/include/loggers/storage_logger.h
  src/include/loggers/transaction_logger.h
  src/loggers/binder_logger.cpp
  src/loggers/catalog_logger.cpp
  src/loggers/common_logger.cpp
  src/loggers/execution_logger.cpp
  src/loggers/index_logger.cpp
  src/loggers/loggers_util.cpp
  src/loggers/messenger_logger.cpp
  src/loggers/metrics_logger.cpp
  src/loggers/network_logger.cpp
  src/loggers/optimizer_logger.cpp
  src/loggers/parser_logger.cpp
  src/loggers/settings_logger.cpp
  src/loggers/storage_logger.cpp
  src/loggers/transaction_logger.cpp
  src/optimizer/plan_generator.cpp
  test/optimizer/logical_operator_test.cpp
  test/optimizer/physical_operator_test.cpp
Labels: best-practice, ready-for-ci, ready-to-merge

#1395 Add calls to lsof in Jenkins.
  Jenkinsfile
  Jenkinsfile-nightly
Labels: infrastructure, ready-for-ci

#1409 Better command line interaction when ModelServerManager enabled
  script/model/model_server.py
  src/self_driving/model_server/model_server_manager.cpp
Labels: best-practice, ready-for-ci, ready-to-merge

#1368 Common Jenkinsfile Build Function
  Jenkinsfile
  Jenkinsfile-nightly
  Jenkinsfile-utils
  script/testing/artifact_stats/collectors/compile_time.py
  script/testing/microbench/run_microbench.py
  script/testing/oltpbench/configs/nightly/nightly.json
  script/testing/oltpbench/configs/nightly/nightly_ramdisk.json
  script/testing/oltpbench/test_case_oltp.py
  script/testing/oltpbench/test_oltpbench.py
  script/testing/util/test_server.py
Labels: ready-to-merge

#1413 Fix iterator invalidation in binding insert statements.
  script/testing/junit/traces/insert.test
  src/binder/bind_node_visitor.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1411 Add guide comments to network folder's README.
  src/network/README.md
  src/network/postgres/postgres_network_commands.cpp
Labels: best-practice, ready-for-review

#1415 add reporting to terrier build
  Jenkinsfile
Labels: ready-for-ci, ready-for-review

#1403 Workload forecasting script
  Jenkinsfile
  script/forecasting/__init__.py
  script/forecasting/cluster.py
  script/forecasting/data_loader.py
  script/forecasting/forecaster.py
  script/forecasting/models.py
  script/installation/packages.sh
  script/testing/self_driving/__init__.py
  script/testing/self_driving/constants.py
  script/testing/self_driving/forecast.py
  script/testing/util/constants.py
  script/testing/util/db_server.py
Labels: ready-to-merge

#1309 Pilot Preparation
  src/include/common/error/exception.h
  src/include/execution/compiler/executable_query.h
  src/include/loggers/selfdriving_logger.h
  src/include/main/db_main.h
  src/include/metrics/pipeline_metric.h
  src/include/self_driving/forecast/workload_forecast.h
  src/include/self_driving/forecast/workload_forecast_segment.h
  src/include/self_driving/modeling/operating_unit.h
  src/include/self_driving/pilot/pilot.h
  src/include/self_driving/pilot/pilot_thread.h
  src/include/self_driving/pilot_util.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/loggers/loggers_util.cpp
  src/loggers/selfdriving_logger.cpp
  src/self_driving/forecast/workload_forecast.cpp
  src/self_driving/forecast/workload_forecast_segment.cpp
  src/self_driving/pilot/pilot.cpp
  src/self_driving/pilot/pilot_thread.cpp
  src/self_driving/pilot_util.cpp
  src/settings/settings_callbacks.cpp
  src/settings/settings_manager.cpp
Labels: feature, ready-for-ci, ready-to-merge
