Repository cmu-db/noisepage, pull requests merged in 2020-07, with the labels that each got.

#996 Hook up per-component metrics settings to DBMain's Builder
  src/include/main/db_main.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/settings/settings_callbacks.cpp
  test/metrics/metrics_test.cpp
Labels: best-practice, ready-to-merge

#1002 Relax asserts in MetricsStore
  src/include/loggers/metrics_logger.h
  src/include/metrics/metrics_store.h
  src/loggers/loggers_util.cpp
  src/loggers/metrics_logger.cpp
  src/storage/write_ahead_log/disk_log_consumer_task.cpp
  src/storage/write_ahead_log/log_serializer_task.cpp
  src/transaction/transaction_manager.cpp
Labels: bug, ready-to-merge

#1003 ensure the match is not empty before assigning ref_cycles_us_
  src/execution/util/cpu_info.cpp
Labels: ready-to-merge

#995 Explicit instantiation of spdlog template functions
  src/include/loggers/loggers_util.h
  src/include/network/terrier_server.h
  src/include/optimizer/binding.h
  src/include/storage/write_ahead_log/disk_log_consumer_task.h
  src/include/storage/write_ahead_log/log_serializer_task.h
  src/loggers/binder_logger.cpp
  src/loggers/catalog_logger.cpp
  src/loggers/common_logger.cpp
  src/loggers/execution_logger.cpp
  src/loggers/index_logger.cpp
  src/loggers/loggers_util.cpp
  src/loggers/metrics_logger.cpp
  src/loggers/network_logger.cpp
  src/loggers/optimizer_logger.cpp
  src/loggers/parser_logger.cpp
  src/loggers/settings_logger.cpp
  src/loggers/storage_logger.cpp
  src/loggers/transaction_logger.cpp
  src/optimizer/binding.cpp
  src/optimizer/group.cpp
  src/optimizer/optimizer.cpp
  src/optimizer/optimizer_task.cpp
  test/network/network_test.cpp
  test/optimizer/top_k_elements_test.cpp
  test/parser/parser_test.cpp
Labels: best-practice, ready-for-review

#1006 Adding support for NOT expression
  script/testing/junit/src/SelectTest.java
  src/execution/sema/sema_expr.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/type.h
  src/include/execution/sql/functions/comparison_functions.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
Labels: feature, ready-for-review

#1008 Modeling Augmentation
  benchmark/runner/transaction_logging_gc_runner.cpp
  script/model/data_class/data_util.py
  script/model/data_class/grouped_op_unit_data.py
  script/model/data_class/opunit_data.py
  script/model/endtoend_estimator.py
  script/model/execution_engine_runner/generate_scan.py
  script/model/global_trainer.py
  script/model/info/data_info.py
  script/model/mini_trainer.py
  script/model/model.py
  script/model/training_util/data_transforming_util.py
  script/model/training_util/global_data_constructing_util.py
  script/model/type.py
  src/brain/brain_util.cpp
  src/brain/operating_unit_recorder.cpp
  src/include/brain/brain_util.h
  src/include/common/resource_tracker.h
  src/include/main/db_main.h
  src/include/metrics/bind_command_metric.h
  src/include/metrics/execute_command_metric.h
  src/include/metrics/execution_metric.h
  src/include/metrics/garbage_collection_metric.h
  src/include/metrics/logging_metric.h
  src/include/metrics/metrics_defs.h
  src/include/metrics/metrics_store.h
  src/include/metrics/pipeline_metric.h
  src/include/metrics/transaction_metric.h
  src/include/planner/plannodes/index_scan_plan_node.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/include/storage/garbage_collector.h
  src/include/storage/write_ahead_log/log_serializer_task.h
  src/metrics/metrics_manager.cpp
  src/metrics/metrics_store.cpp
  src/network/postgres/postgres_network_commands.cpp
  src/optimizer/plan_generator.cpp
  src/settings/settings_callbacks.cpp
  src/storage/garbage_collector.cpp
  src/storage/garbage_collector_thread.cpp
  src/storage/write_ahead_log/disk_log_consumer_task.cpp
  src/storage/write_ahead_log/log_serializer_task.cpp
  util/include/execution/table_generator/sample_output.h
Labels: ready-for-review

#1015 fix oltpbench results folder conficts
  script/testing/oltpbench/test_oltpbench.py
Labels: bug, tests

#938 Issue 936 - Move Limit/Offset Fields to AbstractScanPlanNode
  src/execution/compiler/operator/index_scan_translator.cpp
  src/include/planner/plannodes/abstract_scan_plan_node.h
  src/include/planner/plannodes/csv_scan_plan_node.h
  src/include/planner/plannodes/index_scan_plan_node.h
  src/include/planner/plannodes/seq_scan_plan_node.h
Labels: ready-to-merge

#1005 Extended Query protocol testing
  Jenkinsfile
  Jenkinsfile-nightly
Labels: ready-to-merge, tests

#1021 JUnit Trace File Testing Fixes/Cleanup
  Jenkinsfile
  script/testing/junit/build.xml
  script/testing/junit/constants.py
  script/testing/junit/run_junit.py
  script/testing/junit/src/TracefileTest.java
  script/testing/junit/test_junit.py
  script/testing/util/constants.py
  src/include/main/db_main.h
  src/include/network/connection_handle.h
  test/network/network_test.cpp
Labels: ready-for-review, tests

#1010 run_oltpbench.py: Add Debug Log Timestamps
  script/testing/junit/run_junit.py
  script/testing/oltpbench/run_oltpbench.py
  script/testing/oltpbench/test_oltpbench.py
  script/testing/util/common.py
  script/testing/util/constants.py
  script/testing/util/test_server.py
Labels: infrastructure, ready-for-review

#964 Fix issue ORDER BY column# Does Not Work #890
  src/binder/bind_node_visitor.cpp
  src/include/binder/bind_node_visitor.h
  src/include/parser/select_statement.h
Labels: ready-to-merge

#1034 Re-enable Microbenchmark Regression Checks
  script/micro_bench/run_micro_bench.py
Labels: ready-for-review

#1022 Fix self joins which use index joins
  script/testing/junit/traces/select.test
  src/include/optimizer/index_util.h
  src/optimizer/index_util.cpp
  src/optimizer/rules/implementation_rules.cpp
Labels: bug, ready-to-merge

#1039 Fix update counts, run TPCC in end-to-end performance on Jenkins.
  Jenkinsfile
  script/testing/junit/src/TrafficCopTest.java
  src/execution/compiler/codegen.cpp
  src/execution/compiler/operator/delete_translator.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/storage_interface.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/builtins.h
  src/include/execution/compiler/codegen.h
  src/include/execution/exec/execution_context.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
Labels: bug, ready-to-merge

#1044 Fix pipeline metrics, clean up some stray includes
  src/brain/operating_unit_recorder.cpp
  src/common/strong_typedef.cpp
  src/execution/compiler/compilation_context.cpp
  src/execution/compiler/compiler.cpp
  src/execution/compiler/executable_query.cpp
  src/execution/exec_defs.cpp
  src/execution/sql/vector.cpp
  src/execution/sql/vector_projection.cpp
  src/execution/vm/bytecode_module.cpp
  src/execution/vm/control_flow_builders.cpp
  src/execution/vm/llvm_engine.cpp
  src/execution/vm/vm.cpp
  src/include/brain/brain_util.h
  src/include/brain/operating_unit.h
  src/include/brain/operating_unit_recorder.h
  src/include/common/perf_monitor.h
  src/include/common/worker_pool.h
  src/include/execution/compiler/compilation_context.h
  src/include/execution/exec/output.h
  src/include/execution/exec_defs.h
  src/include/execution/vm/control_flow_builders.h
  src/include/execution/vm/llvm_engine.h
  src/include/optimizer/statistics/count_min_sketch.h
  src/include/optimizer/statistics/histogram.h
Labels: best-practice, bug, ready-to-merge
