Repository cmu-db/noisepage, pull requests merged in 2020-05, with the labels that each got.

#901 Fixes for Built-in Functions + Tests
  .travis.yml
  README.md
  script/testing/junit/BuiltinUDFTest.java
  script/testing/junit/src/FunctionsTest.java
  script/testing/junit/src/SelectTest.java
  script/testing/junit/src/TestUtility.java
  script/testing/util/constants.py
  src/binder/bind_node_visitor.cpp
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/expression/function_translator.cpp
  src/execution/functions/function_context.cpp
  src/execution/udf/udf_context.cpp
  src/include/catalog/catalog_accessor.h
  src/include/catalog/database_catalog.h
  src/include/execution/functions/HOW_TO_ADD_BUILTINS.md
  src/include/execution/functions/function_context.h
Labels: ready-for-review, tests

#893 IndexJoin Optimizer Support
  src/brain/operating_unit_recorder.cpp
  src/execution/compiler/operator/index_join_translator.cpp
  src/include/brain/operating_unit.h
  src/include/execution/compiler/operator/index_join_translator.h
  src/include/optimizer/child_property_deriver.h
  src/include/optimizer/cost_model/abstract_cost_model.h
  src/include/optimizer/cost_model/trivial_cost_model.h
  src/include/optimizer/group_expression.h
  src/include/optimizer/index_util.h
  src/include/optimizer/input_column_deriver.h
  src/include/optimizer/operator_visitor.h
  src/include/optimizer/optimizer_defs.h
  src/include/optimizer/physical_operators.h
  src/include/optimizer/plan_generator.h
  src/include/optimizer/rule.h
  src/include/optimizer/rules/implementation_rules.h
  src/include/parser/expression_util.h
  src/include/planner/plannodes/index_join_plan_node.h
  src/optimizer/child_property_deriver.cpp
  src/optimizer/group_expression.cpp
  src/optimizer/index_util.cpp
  src/optimizer/input_column_deriver.cpp
  src/optimizer/optimizer_task.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/rule.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/planner/plannodes/index_join_plan_node.cpp
  test/execution/compiler_test.cpp
  test/optimizer/idx_join_test.cpp
  test/optimizer/tpcc_plan_stocklevel_test.cpp
  util/include/optimizer/cost_model/forced_cost_model.h
Labels: ready-to-merge

#835 Inheritance structure for Optimizer Node / Contents classes
  src/include/catalog/catalog_accessor.h
  src/include/optimizer/abstract_optimizer.h
  src/include/optimizer/abstract_optimizer_node.h
  src/include/optimizer/abstract_optimizer_node_contents.h
  src/include/optimizer/binding.h
  src/include/optimizer/cost_model/trivial_cost_model.h
  src/include/optimizer/expression_node.h
  src/include/optimizer/expression_node_contents.h
  src/include/optimizer/group_expression.h
  src/include/optimizer/logical_operators.h
  src/include/optimizer/memo.h
  src/include/optimizer/operator_node.h
  src/include/optimizer/operator_node_contents.h
  src/include/optimizer/optimizer.h
  src/include/optimizer/optimizer_context.h
  src/include/optimizer/physical_operators.h
  src/include/optimizer/plan_generator.h
  src/include/optimizer/property_enforcer.h
  src/include/optimizer/query_to_operator_transformer.h
  src/include/optimizer/rule.h
  src/include/optimizer/rules/implementation_rules.h
  src/include/optimizer/rules/rewrite_rules.h
  src/include/optimizer/rules/transformation_rules.h
  src/include/optimizer/rules/unnesting_rules.h
  src/include/parser/expression/abstract_expression.h
  src/optimizer/binding.cpp
  src/optimizer/child_property_deriver.cpp
  src/optimizer/expression_node_contents.cpp
  src/optimizer/group.cpp
  src/optimizer/group_expression.cpp
  src/optimizer/input_column_deriver.cpp
  src/optimizer/logical_operators.cpp
  src/optimizer/memo.cpp
  src/optimizer/operator_node_contents.cpp
  src/optimizer/optimizer.cpp
  src/optimizer/optimizer_task.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/property_enforcer.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/rule.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/optimizer/rules/rewrite_rules.cpp
  src/optimizer/rules/transformation_rules.cpp
  src/optimizer/rules/unnesting_rules.cpp
  src/optimizer/statistics/child_stats_deriver.cpp
  src/optimizer/statistics/stats_calculator.cpp
  test/optimizer/logical_operator_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/optimizer_context_test.cpp
  test/optimizer/physical_operator_test.cpp
  util/include/optimizer/cost_model/forced_cost_model.h
Labels: ready-to-merge

#913 Update traffic_cop_test for libpqxx 7.x
  test/traffic_cop/traffic_cop_test.cpp
Labels: ready-to-merge, tests

#905 Add support for "SELECT 1" queries.
  script/testing/junit/src/SelectTest.java
  src/include/execution/compiler/operator/projection_translator.h
  src/include/network/postgres/postgres_packet_writer.h
  src/include/parser/expression/constant_value_expression.h
  src/include/parser/expression/function_expression.h
  src/parser/expression/abstract_expression.cpp
  test/parser/expression_test.cpp
Labels: bug, feature, ready-to-merge

#912 Command line args for WAL and metrics components
  src/include/main/db_main.h
  src/include/settings/settings_defs.h
  src/main/terrier.cpp
  test/metrics/metrics_test.cpp
Labels: best-practice, ready-to-merge

#918 Fix bug in OpGetParamString in bytecode_handlers
  src/include/execution/vm/bytecode_handlers.h
Labels: bug, ready-to-merge

#923 Reduce idx_join_test runtime
  test/optimizer/index_nested_loops_join_test.cpp
Labels: ready-to-merge

#925 Change CVE's underlying value to be a std::variant
  Jenkinsfile
  benchmark/runner/mini_runners.cpp
  benchmark/storage/recovery_benchmark.cpp
  src/binder/bind_node_visitor.cpp
  src/binder/binder_sherpa.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
  src/execution/sql/value_util.cpp
  src/include/binder/binder_sherpa.h
  src/include/execution/sql/value_util.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/parser/expression/constant_value_expression.h
  src/include/parser/expression_util.h
  src/include/settings/settings_common.h
  src/network/postgres/postgres_packet_util.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/statistics/selectivity.cpp
  src/optimizer/statistics/stats_calculator.cpp
  src/parser/expression/constant_value_expression.cpp
  src/parser/postgresparser.cpp
  src/settings/settings_manager.cpp
  test/binder/binder_test.cpp
  test/execution/compiler_test.cpp
  test/execution/table_vector_iterator_test.cpp
  test/include/execution/compiler/expression_util.h
  test/include/execution/sql_test.h
  test/optimizer/logical_operator_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/physical_operator_test.cpp
  test/optimizer/tpcc_plan_delivery_test.cpp
  test/optimizer/tpcc_plan_index_scan.cpp
  test/optimizer/tpcc_plan_neworder_test.cpp
  test/optimizer/tpcc_plan_payment_test.cpp
  test/optimizer/tpcc_plan_seq_scan.cpp
  test/optimizer/value_condition_test.cpp
  test/parser/constant_value_expression_test.cpp
  test/parser/expression_test.cpp
  test/parser/parser_test.cpp
  test/planner/output_schema_test.cpp
  test/planner/plan_node_json_test.cpp
  test/planner/plan_node_test.cpp
  test/test_util/tpch/workload.cpp
  util/execution/tpl.cpp
  util/include/execution/table_generator/sample_output.h
  util/include/execution/table_generator/schema_reader.h
  util/include/execution/table_generator/table_generator.h
Labels: best-practice, ready-to-merge, tests

#928 Fix failed assertion when a NULL parameter comes in
  src/include/execution/vm/bytecode_handlers.h
Labels: bug, ready-to-merge
