Repository cmu-db/noisepage, pull requests merged in 2020-09, with the labels that each got.

#1130 Revert "Explicit instantiation of spdlog template functions (#995)"
  src/include/loggers/loggers_util.h
  src/include/network/terrier_server.h
  src/include/storage/write_ahead_log/disk_log_consumer_task.h
  src/include/storage/write_ahead_log/log_serializer_task.h
  src/loggers/binder_logger.cpp
  src/loggers/catalog_logger.cpp
  src/loggers/common_logger.cpp
  src/loggers/execution_logger.cpp
  src/loggers/index_logger.cpp
  src/loggers/loggers_util.cpp
  src/loggers/metrics_logger.cpp
  src/loggers/network_logger.cpp
  src/loggers/optimizer_logger.cpp
  src/loggers/parser_logger.cpp
  src/loggers/settings_logger.cpp
  src/loggers/storage_logger.cpp
  src/loggers/transaction_logger.cpp
  test/network/network_test.cpp
  test/optimizer/top_k_elements_test.cpp
  test/parser/parser_test.cpp
Labels: infrastructure, ready-for-review

#1148 Fix CREATE INDEX creation of PR
  script/testing/junit/traces/create_index.test
  src/execution/compiler/operator/index_create_translator.cpp
Labels: bug, ready-to-merge

#1146 Handle Execution Exceptions
  src/execution/compiler/executable_query.cpp
  src/execution/compiler/operator/csv_scan_translator.cpp
  src/execution/compiler/operator/operator_translator.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
  src/execution/sql/sql.cpp
  src/execution/sql/vector_operations/arithmetic.cpp
  src/execution/sql/vector_operations/fill.cpp
  src/execution/sql/vector_operations/gather.cpp
  src/execution/sql/vector_operations/gather_select.cpp
  src/execution/sql/vector_operations/generate.cpp
  src/execution/sql/vector_operations/hash.cpp
  src/execution/sql/vector_operations/inplace_arithmetic.cpp
  src/execution/sql/vector_operations/inplace_bitwise.cpp
  src/execution/sql/vector_operations/like.cpp
  src/execution/sql/vector_operations/select.cpp
  src/include/common/error/exception.h
  src/include/execution/sql/operators/cast_operators.h
  src/include/execution/sql/vector_operations/inplace_operation_executor.h
  src/traffic_cop/traffic_cop.cpp
Labels: best-practice, ready-to-merge

#1140 Add Asin/Acos out of range error handling
  src/include/execution/sql/operators/numeric_operators.h
  test/execution/sql_functions_arithmetic_functions_test.cpp
  test/traffic_cop/traffic_cop_test.cpp
Labels: bug, ready-for-review

#1131 Apple fixes
  CMakeLists.txt
  Jenkinsfile
  cmake_modules/ThirdpartyToolchain.cmake
  util/CMakeLists.txt
Labels: infrastructure, ready-for-review

#1152 Shrink xxHash include
  third_party/xxHash/xxh3.h
  third_party/xxHash/xxhash.c
  third_party/xxHash/xxhash.h
Labels: ready-to-merge

#1144 Fix AVG Aggregations for INT Column Types.
  script/micro_bench/run_micro_bench.py
  src/execution/compiler/operator/static_aggregation_translator.cpp
Labels: bug, ready-to-merge

#1153 Modeling Support for CREATE INDEX
  benchmark/runner/mini_runners.cpp
  script/model/global_trainer.py
  script/model/mini_trainer.py
  script/model/training_util/data_transforming_util.py
  script/model/training_util/global_data_constructing_util.py
  script/model/type.py
  src/brain/brain_util.cpp
  src/brain/operating_unit_recorder.cpp
  src/execution/compiler/operator/index_create_translator.cpp
  src/execution/exec/execution_context.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/storage_interface.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/bytecode_handlers.cpp
  src/execution/vm/vm.cpp
  src/include/brain/operating_unit_recorder.h
  src/include/execution/ast/builtins.h
  src/include/execution/exec/execution_context.h
  src/include/execution/sql/storage_interface.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  util/execution/table_generator/table_generator.cpp
Labels: ready-to-merge

#1164 Add EXPORT to bytecode handler to fix TPCH runner compiled mode.
  src/include/execution/vm/bytecode_handlers.h
Labels: bug, ready-to-merge

#1171 Remove varlen_entry_benchmark from CI
  benchmark/storage/varlen_entry_benchmark.cpp
  script/micro_bench/run_micro_bench.py
  src/include/common/hash_util.h
  src/include/storage/storage_defs.h
Labels: ready-to-merge, tests

#1172 Prefer fdatasync over fsync of WAL on supported platforms
  src/include/storage/write_ahead_log/log_io.h
Labels: best-practice, performance, ready-to-merge

#1169 Adding VARCHAR type to mini-runners and random fixes
  benchmark/runner/mini_runners.cpp
  script/model/data_class/data_util.py
  script/model/data_class/grouped_op_unit_data.py
  script/model/endtoend_estimator.py
  script/model/global_model_config.py
  script/model/global_trainer.py
  script/model/mini_trainer.py
  script/model/training_util/global_data_constructing_util.py
  script/model/training_util/result_writing_util.py
  src/brain/operating_unit_recorder.cpp
  src/include/main/db_main.h
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/generic_key.h
  src/include/type/type_util.h
  src/storage/index/bwtree_index.cpp
  src/storage/index/index_builder.cpp
  test/test_util/tpch/workload.cpp
  util/execution/table_generator/table_generator.cpp
  util/execution/table_generator/table_reader.cpp
  util/include/execution/table_generator/table_generator.h
Labels: ready-for-review

#1156 Create Index in Parallel
  src/execution/compiler/operator/index_create_translator.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/table_vector_iterator.cpp
  src/include/common/constants.h
  src/include/execution/compiler/operator/index_create_translator.h
  src/include/execution/exec/execution_settings.h
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/hash_index.h
  src/storage/index/bwtree_index.cpp
  src/storage/index/hash_index.cpp
  util/include/execution/table_generator/table_generator.h
Labels: feature, ready-for-review

#1139 Add support for variadic functions in the catalog and builtin CONCAT function
  script/testing/junit/traces/functions.test
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/functions/string_functions.cpp
  src/execution/vm/bytecode_emitter.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/catalog/postgres/pg_proc.h
  src/include/execution/ast/builtins.h
  src/include/execution/sql/functions/string_functions.h
  src/include/execution/vm/bytecode_emitter.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/type/type_id.h
  test/execution/sql_functions_string_functions_test.cpp
Labels: feature, ready-to-merge

#1109 Unix domain sockets & findings from offcputime analysis
  src/include/main/db_main.h
  src/include/network/connection_dispatcher_task.h
  src/include/network/terrier_server.h
  src/include/settings/settings_defs.h
  src/network/connection_dispatcher_task.cpp
  src/network/network_io_wrapper.cpp
  src/network/terrier_server.cpp
  test/network/network_test.cpp
Labels: performance, question/discussion, ready-to-merge

#1187 Refactor FunctionContext bootstrapping in DatabaseCatalog
  src/catalog/catalog.cpp
  src/catalog/database_catalog.cpp
  src/include/catalog/database_catalog.h
  src/include/execution/functions/function_context.h
Labels: best-practice, ready-to-merge

#1192 Toolchain related fixes
  src/binder/binder_util.cpp
  src/catalog/database_catalog.cpp
  src/include/common/container/concurrent_bitmap.h
  src/include/execution/exec/execution_context.h
  src/include/execution/exec/output.h
  src/include/execution/sql/operators/cast_operators.h
  src/include/storage/access_observer.h
  src/traffic_cop/traffic_cop.cpp
  third_party/nlohmann/detail/output/serializer.hpp
  third_party/spdlog/common.h
Labels: best-practice, ready-to-merge

#1100 Left outer join
  script/testing/junit/traces/select.test
  src/binder/binder_context.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/expression/constant_translator.cpp
  src/execution/compiler/operator/hash_join_translator.cpp
  src/execution/compiler/pipeline.cpp
  src/execution/compiler/work_context.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/join_hash_table.cpp
  src/execution/sql/join_hash_table_iterator.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/bytecode_handlers.cpp
  src/execution/vm/vm.cpp
  src/include/binder/binder_context.h
  src/include/execution/ast/builtins.h
  src/include/execution/ast/type.h
  src/include/execution/compiler/codegen.h
  src/include/execution/compiler/operator/hash_join_translator.h
  src/include/execution/compiler/pipeline.h
  src/include/execution/compiler/work_context.h
  src/include/execution/sema/sema.h
  src/include/execution/sql/join_hash_table.h
  src/include/execution/vm/bytecode_generator.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/optimizer/physical_operators.h
  src/include/optimizer/rule.h
  src/include/optimizer/rules/implementation_rules.h
  src/optimizer/child_property_deriver.cpp
  src/optimizer/input_column_deriver.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/rule.cpp
  src/optimizer/rules/implementation_rules.cpp
  test/optimizer/physical_operator_test.cpp
Labels: feature, ready-to-merge

#1197 Fix complaints from new Doxygen versions
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/hash_index.h
Labels: best-practice, ready-to-merge

#1161 Query Trace Recording
  src/include/main/db_main.h
  src/include/metrics/metrics_defs.h
  src/include/metrics/metrics_store.h
  src/include/metrics/query_trace_metric.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/metrics/metrics_manager.cpp
  src/metrics/metrics_store.cpp
  src/settings/settings_callbacks.cpp
  src/traffic_cop/traffic_cop.cpp
  test/metrics/metrics_test.cpp
Labels: ready-to-merge

#1200 Network layer refactor.
  src/include/common/event_util.h
  src/include/common/notifiable_task.h
  src/include/main/db_main.h
  src/include/network/connection_dispatcher_task.h
  src/include/network/connection_handle.h
  src/include/network/connection_handle_factory.h
  src/include/network/connection_handler_task.h
  src/include/network/itp/itp_protocol_interpreter.h
  src/include/network/network_io_utils.h
  src/include/network/network_io_wrapper.h
  src/include/network/postgres/postgres_protocol_interpreter.h
  src/include/network/protocol_interpreter.h
  src/include/network/terrier_server.h
  src/network/connection_dispatcher_task.cpp
  src/network/connection_handle.cpp
  src/network/connection_handle_factory.cpp
  src/network/connection_handler_task.cpp
  src/network/network_io_wrapper.cpp
  src/network/postgres/postgres_protocol_interpreter.cpp
  src/network/terrier_server.cpp
  src/traffic_cop/traffic_cop.cpp
  test/include/test_util/manual_packet_util.h
  test/network/network_test.cpp
Labels: best-practice, ready-to-merge

#1213 Fix GC-Compactor race in storage layer
  src/storage/garbage_collector.cpp
Labels: bug, ready-to-merge
