Repository cmu-db/noisepage, pull requests merged in 2020-04, with the labels that each got.

#853 Change connection thread count to be a setting instead of a `#define`
  src/include/main/db_main.h
  src/include/network/network_defs.h
  src/include/network/terrier_server.h
  src/include/settings/settings_defs.h
  src/network/terrier_server.cpp
  test/network/network_test.cpp
Labels: best-practice, ready-to-merge

#848 OLTP-Bench Test Script + Jenkins Pipeline Update (#817)
  .gitignore
  Jenkinsfile
  script/testing/README.md
  script/testing/junit/__init__.py
  script/testing/junit/constants.py
  script/testing/junit/run_junit.py
  script/testing/junit/test_junit.py
  script/testing/oltpbench/__init__.py
  script/testing/oltpbench/constants.py
  script/testing/oltpbench/run_oltpbench.py
  script/testing/oltpbench/test_oltpbench.py
  script/testing/util/__init__.py
  script/testing/util/common.py
  script/testing/util/constants.py
  script/testing/util/test_server.py
Labels: infrastructure, tests

#869 Python Testing Junit Problems
  Jenkinsfile
  script/testing/util/constants.py
  script/testing/util/test_server.py
Labels: tests

#803 Getting builtin procs to execute end to end
  script/testing/junit/BuiltinUDFTest.java
  src/binder/bind_node_visitor.cpp
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/execution/compiler/expression/function_translator.cpp
  src/execution/compiler/translator_factory.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/udf/udf_context.cpp
  src/execution/vm/bytecode_generator.cpp
  src/include/catalog/catalog_accessor.h
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/pg_proc.h
  src/include/execution/ast/builtins.h
  src/include/execution/compiler/expression/function_translator.h
  src/include/execution/compiler/translator_factory.h
  src/include/execution/sema/sema.h
  src/include/execution/udf/HOW_TO_ADD_BUILTINS.md
  src/include/execution/udf/udf_context.h
  src/include/execution/vm/bytecode_generator.h
  src/include/parser/expression/function_expression.h
  src/include/storage/recovery/recovery_manager.h
  src/storage/recovery/recovery_manager.cpp
  test/catalog/catalog_test.cpp
Labels: ready-to-merge

#799 Increase Benchmark Result Requirement + Support Local Runs
  script/micro_bench/README.md
  script/micro_bench/run_micro_bench.py
Labels: infrastructure, tests

#871 Compiled query caching added to PostgresProtocolInterpreter
  src/execution/executable_query.cpp
  src/include/execution/executable_query.h
  src/include/main/db_main.h
  src/include/network/postgres/portal.h
  src/include/network/postgres/postgres_protocol_interpreter.h
  src/include/network/postgres/statement.h
  src/include/settings/settings_defs.h
  src/include/traffic_cop/traffic_cop.h
  src/network/postgres/postgres_network_commands.cpp
  src/traffic_cop/traffic_cop.cpp
  test/network/network_test.cpp
Labels: feature

#880 Keep query string in Statement object
  src/binder/binder_sherpa.cpp
  src/include/binder/binder_sherpa.h
  src/include/network/postgres/portal.h
  src/include/network/postgres/statement.h
  src/network/postgres/postgres_network_commands.cpp
  src/network/postgres/statement.cpp
Labels: best-practice, ready-to-merge

#876 Python Test Harness Investigations
  Jenkinsfile
  script/testing/oltpbench/constants.py
  script/testing/oltpbench/run_oltpbench.py
  script/testing/oltpbench/test_oltpbench.py
Labels: in-progress, tests
