Repository cmu-db/noisepage, pull requests merged in 2020-01, with the labels that each got.

#662 Binder and operator transformer take ManagedPointer to CatalogAccessor
  src/binder/bind_node_visitor.cpp
  src/binder/binder_context.cpp
  src/include/binder/bind_node_visitor.h
  src/include/binder/binder_context.h
  src/include/optimizer/query_to_operator_transformer.h
  src/optimizer/query_to_operator_transformer.cpp
  test/binder/binder_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/test_util/tpcc/tpcc_plan_test.cpp
Labels: best-practice, ready-to-merge

#664 Static PostgresParser
  benchmark/parser/parser_benchmark.cpp
  src/include/parser/postgresparser.h
  src/include/planner/plannodes/index_scan_plan_node.h
  src/parser/postgresparser.cpp
  test/binder/binder_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/parser/expression_test.cpp
  test/parser/parser_test.cpp
  test/test_util/tpcc/tpcc_plan_test.cpp
Labels: best-practice, ready-to-merge

#665 More ManagedPointers to sort out ownership
  benchmark/benchmark_util/data_table_benchmark_util.cpp
  benchmark/catalog/catalog_benchmark.cpp
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/index_wrapper_benchmark.cpp
  benchmark/storage/recovery_benchmark.cpp
  src/catalog/catalog.cpp
  src/catalog/database_catalog.cpp
  src/include/catalog/catalog.h
  src/include/catalog/catalog_accessor.h
  src/include/catalog/database_catalog.h
  src/include/execution/exec/execution_context.h
  src/include/main/db_main.h
  src/include/storage/data_table.h
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/hash_index.h
  src/include/storage/index/index.h
  src/include/storage/recovery/recovery_manager.h
  src/include/storage/sql_table.h
  src/storage/block_compactor.cpp
  src/storage/data_table.cpp
  src/storage/recovery/recovery_manager.cpp
  src/traffic_cop/traffic_cop.cpp
  test/binder/binder_test.cpp
  test/catalog/catalog_test.cpp
  test/common/stat_registry_test.cpp
  test/execution/ddl_executors_test.cpp
  test/include/execution/sql_test.h
  test/include/test_util/storage_test_util.h
  test/include/test_util/tpcc/loader.h
  test/metrics/metrics_test.cpp
  test/network/network_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/storage/block_compactor_test.cpp
  test/storage/bwtree_index_test.cpp
  test/storage/data_table_concurrent_test.cpp
  test/storage/data_table_test.cpp
  test/storage/garbage_collector_test.cpp
  test/storage/hash_index_test.cpp
  test/storage/index_key_test.cpp
  test/storage/log_test.cpp
  test/storage/recovery_test.cpp
  test/test_util/data_table_test_util.cpp
  test/test_util/sql_table_test_util.cpp
  test/test_util/tpcc/builder.cpp
  test/test_util/tpcc/delivery.cpp
  test/test_util/tpcc/new_order.cpp
  test/test_util/tpcc/order_status.cpp
  test/test_util/tpcc/payment.cpp
  test/test_util/tpcc/stock_level.cpp
  test/test_util/tpcc/tpcc_plan_test.cpp
  test/traffic_cop/traffic_cop_test.cpp
  test/transaction/mvcc_test.cpp
  util/execution/tpl.cpp
Labels: best-practice, ready-to-merge

#671 Travis: Unlink Homebrew's python@2 formula before running packages.sh
  .travis.yml
Labels: bug, infrastructure, ready-to-merge

#669 Fix CodeGen::StringToSql
  src/execution/compiler/codegen.cpp
Labels: bug, ready-to-merge

#670 Add Index::InsertUnique logic to CodeGen
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/storage_interface.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/bytecode_handlers.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/builtins.h
  src/include/execution/sql/storage_interface.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
Labels: bug, ready-to-merge

#676 Exposing bw-tree config parameters
  third_party/bwtree/bwtree.h
Labels: ready-to-merge

#675 Concurrent DataTable::SlotIterator benchmark
  benchmark/storage/data_table_benchmark.cpp
Labels: ready-to-merge, tests

#678 move doxygen to Jenkins
  Jenkinsfile
  README.md
Labels: infrastructure

#679 Add GetBlockStore() to Catalog and CatalogAccessor.
  src/catalog/catalog.cpp
  src/catalog/catalog_accessor.cpp
  src/include/catalog/catalog.h
  src/include/catalog/catalog_accessor.h
Labels: ready-to-merge

#681 updated cpplint.py from bustub
  build-support/cpplint.py
  test/execution/pr_filler_test.cpp
Labels: infrastructure, tests

#683 Fix read-only txns commit callback not invoked with logging enabled
  src/include/main/db_main.h
  src/storage/write_ahead_log/disk_log_consumer_task.cpp
  src/storage/write_ahead_log/log_serializer_task.cpp
  test/storage/log_test.cpp
Labels: bug, ready-to-merge

#682 OutputSchema and assorted PlanGenerator fixes
  src/execution/compiler/operator/index_scan_translator.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
  src/include/optimizer/plan_generator.h
  src/include/planner/plannodes/index_scan_plan_node.h
  src/include/planner/plannodes/seq_scan_plan_node.h
  src/optimizer/plan_generator.cpp
  test/execution/compiler_test.cpp
  test/optimizer/tpcc_plan_delivery_test.cpp
  test/optimizer/tpcc_plan_index_scan.cpp
  test/optimizer/tpcc_plan_neworder_test.cpp
  test/optimizer/tpcc_plan_payment_test.cpp
  test/optimizer/tpcc_plan_seq_scan.cpp
Labels: ready-to-merge

#688 Codegen projection
  src/execution/compiler/translator_factory.cpp
  src/include/execution/compiler/operator/projection_translator.h
  test/execution/compiler_test.cpp
Labels: feature, ready-to-merge

#680 Create/drop transformations + PlanGenerator
  build-support/bad_words.txt
  src/include/catalog/catalog_defs.h
  src/include/catalog/schema.h
  src/include/optimizer/child_property_deriver.h
  src/include/optimizer/logical_operators.h
  src/include/optimizer/physical_operators.h
  src/include/optimizer/plan_generator.h
  src/include/optimizer/rule.h
  src/include/optimizer/rules/implementation_rules.h
  src/include/planner/plannodes/create_function_plan_node.h
  src/optimizer/child_property_deriver.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/rule.cpp
  src/optimizer/rules/implementation_rules.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/physical_operator_test.cpp
  test/planner/plan_node_json_test.cpp
Labels: ready-to-merge

#691 Fix segfault in PostgresParser from creating table in a namespace
  src/parser/postgresparser.cpp
Labels: bug

#697 Dump the AST when an error occurs in code compilation.
  src/execution/executable_query.cpp
Labels: best-practice

#696 CREATE INDEX fixes
  src/binder/bind_node_visitor.cpp
  src/include/parser/expression/column_value_expression.h
  src/optimizer/plan_generator.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/parser/postgresparser.cpp
  test/optimizer/operator_transformer_test.cpp
Labels: bug, ready-to-merge

#695 Boolean Support
  sample_tpl/scan-alltypes.tpl
  sample_tpl/simple.tpl
  sample_tpl/tpl_tests.txt
  sample_tpl/types/bools.tpl
  src/execution/ast/ast_dump.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/expression/param_value_translator.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sema/sema_checking.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/llvm_engine.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/ast.h
  src/include/execution/ast/builtins.h
  src/include/execution/ast/type.h
  src/include/execution/util/execution_common.h
  src/include/execution/vm/bytecode_generator.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/network/postgres/postgres_packet_writer.h
  test/CMakeLists.txt
  test/execution/ast_dump_test.cpp
  test/execution/compiler_test.cpp
  test/execution/error_reporter_test.cpp
  test/util/CMakeLists.txt
  util/execution/table_generator/table_generator.cpp
  util/include/execution/table_generator/table_generator.h
Labels: ready-for-review

#698 Row count for INSERT, UPDATE, DELETE
  src/execution/sql/storage_interface.cpp
  src/include/execution/exec/execution_context.h
  src/include/execution/exec/output.h
  src/traffic_cop/traffic_cop.cpp
Labels: ready-to-merge

#699 Graceful shutdown via SIGINT or SIGTERM
  src/main/terrier.cpp
Labels: best-practice

#700 Stronger comments and favor anonymous namespace for db_main_handler_ptr
  src/main/terrier.cpp
Labels: best-practice

#694 Remove Postgres related methods from PacketWriter
  src/include/network/packet_writer.h
  src/include/network/postgres/postgres_packet_writer.h
Labels: best-practice, ready-for-review

#702 Configurable Multi-Threaded Benchmarks
  Jenkinsfile
  benchmark/README.md
  benchmark/benchmark_util/benchmark_config.cpp
  benchmark/benchmark_util/benchmark_main.cpp
  benchmark/catalog/catalog_benchmark.cpp
  benchmark/include/benchmark_util/benchmark_config.h
  benchmark/parser/parser_benchmark.cpp
  benchmark/storage/bwtree_benchmark.cpp
  benchmark/storage/cuckoomap_benchmark.cpp
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/index_wrapper_benchmark.cpp
  benchmark/storage/logging_benchmark.cpp
  benchmark/storage/recovery_benchmark.cpp
  benchmark/storage/slot_iterator_benchmark.cpp
  benchmark/storage/tuple_access_strategy_benchmark.cpp
  benchmark/transaction/large_transaction_benchmark.cpp
  script/micro_bench/run_micro_bench.py
Labels: ready-for-review

#709 pg_catalog not ending up in the default namespace search path
  src/binder/binder_context.cpp
Labels: ready-to-merge

#693 Index Scan Fixes from the Optimizer
  sample_tpl/delete.tpl
  sample_tpl/insert.tpl
  sample_tpl/join-index.tpl
  sample_tpl/scan-index-2.tpl
  sample_tpl/scan-index-3.tpl
  sample_tpl/scan-index.tpl
  sample_tpl/update.tpl
  src/catalog/database_catalog.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/operator/index_join_translator.cpp
  src/execution/compiler/operator/index_scan_translator.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/index_iterator.cpp
  src/execution/vm/bytecode_emitter.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/bytecode_handlers.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/builtins.h
  src/include/execution/compiler/codegen.h
  src/include/execution/sql/index_iterator.h
  src/include/execution/vm/bytecode_emitter.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/optimizer/index_util.h
  src/include/optimizer/physical_operators.h
  src/include/planner/plannodes/index_scan_plan_node.h
  src/include/planner/plannodes/plan_node_defs.h
  src/include/storage/index/bwtree_index.h
  src/include/storage/index/compact_ints_key.h
  src/include/storage/index/generic_key.h
  src/include/storage/index/hash_index.h
  src/include/storage/index/hash_key.h
  src/include/storage/index/index.h
  src/optimizer/child_property_deriver.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/planner/plannodes/index_scan_plan_node.cpp
  test/execution/compiler_test.cpp
  test/execution/index_iterator_test.cpp
  test/execution/storage_interface_test.cpp
  test/optimizer/physical_operator_test.cpp
  test/optimizer/tpcc_plan_delivery_test.cpp
  test/optimizer/tpcc_plan_index_scan.cpp
  test/optimizer/tpcc_plan_neworder_test.cpp
  test/optimizer/tpcc_plan_payment_test.cpp
  test/storage/bwtree_index_test.cpp
  test/storage/index_key_test.cpp
  test/test_util/tpcc/delivery.cpp
  test/test_util/tpcc/order_status.cpp
  test/test_util/tpcc/stock_level.cpp
Labels: ready-to-merge

#723 CREATE TABLE with a qualified namespace work as expected
  src/optimizer/query_to_operator_transformer.cpp
Labels: ready-for-review
