Repository cmu-db/noisepage, pull requests merged in 2020-11, with the labels that each got.

#1291 Hotfix Microbenchmark Decimal Reporting
  script/testing/reporting/parsers/parse_data.py
Labels: ready-for-ci, ready-for-review, tests

#1295 Populate Microbenchmark Data
  Jenkinsfile-nightly
Labels: ready-for-review, ready-to-merge, tests

#1294 Fix use-after-free in DDL aborts
  src/catalog/database_catalog.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1272 TPL Atomic Operations
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/builtins.h
  src/include/execution/sema/sema.h
  src/include/execution/vm/bytecode_generator.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  test/execution/atomics_test.cpp
Labels: feature, ready-for-ci, ready-to-merge

#1297 Upgrade fast_float to tagged release version.
  CMakeLists.txt
Labels: best-practice, ready-for-ci, ready-to-merge

#1279 fix typo in SetIndexedUpdate in Update Plannode
  src/include/planner/plannodes/update_plan_node.h
Labels: ready-for-ci, ready-to-merge

#1298 Prevent optimizer from issuing plans with range scans on hashmap indexes
  src/optimizer/index_util.cpp
  test/catalog/catalog_sql_test.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1311 Development Environment Troubleshooting Documentation
  docs/README.md
  docs/dev_troubleshooting.md
Labels: best-practice, ready-to-merge

#1316 Add port resource constraints to catalog_sql_test.
  CMakeLists.txt
Labels: infrastructure

#1320 Add error message when GenerateTrace fails
  script/testing/junit/src/GenerateTrace.java
Labels: best-practice, ready-for-ci, ready-for-review

#1310 Fix having clauses in aggregates
  script/testing/junit/traces/aggregations.test
  src/optimizer/plan_generator.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1243 collect memory consumption info during OLTPBench tests
  .gitignore
  script/testing/check_pids.py
  script/testing/collect_mem_info.py
  script/testing/oltpbench/constants.py
  script/testing/oltpbench/run_oltpbench.py
  script/testing/oltpbench/test_case_oltp.py
  script/testing/oltpbench/test_oltpbench.py
  script/testing/oltpbench/utils.py
  script/testing/reporting/parsers/oltpbench/summary_parser.py
  script/testing/reporting/parsers/parse_data.py
  script/testing/reporting/report_result.py
  script/testing/reporting/utils.py
  script/testing/util/common.py
  script/testing/util/constants.py
  script/testing/util/mem_metrics.py
  script/testing/util/periodic_task.py
  script/testing/util/test_case.py
  script/testing/util/test_server.py
Labels: ready-for-ci, ready-to-merge

#1323 Add documentation for preventing Run / Debug from CLion from crashing on ASAN Container Overflow
  docs/dev_troubleshooting.md
Labels: ready-to-merge

#1329 Hotfix: fix the nightly reporting decimal precision of memory summary issue
  script/testing/reporting/utils.py
Labels: ready-for-ci, ready-for-review

#1327 Add support for type cast expressions.
  script/testing/junit/traces/select.test
  src/binder/bind_node_visitor.cpp
  src/binder/binder_util.cpp
  src/include/parser/expression/type_cast_expression.h
  src/include/parser/expression_util.h
Labels: feature, ready-for-ci, ready-to-merge

#1236 DeriveStats Support for Semi Join
  src/include/optimizer/statistics/child_stats_deriver.h
  src/include/optimizer/statistics/stats_calculator.h
  src/optimizer/statistics/child_stats_deriver.cpp
  src/optimizer/statistics/stats_calculator.cpp
Labels: ready-for-ci, ready-to-merge

#1300 Stopping trackers on exceptional execution
  Jenkinsfile
  script/testing/junit/traces/select.test
  script/testing/junit/utils.py
  src/execution/compiler/operator/sort_translator.cpp
  src/execution/compiler/operator/static_aggregation_translator.cpp
  src/execution/compiler/pipeline.cpp
  src/execution/exec/execution_context.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/bytecode_handlers.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/builtins.h
  src/include/execution/exec/execution_context.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/optimizer/optimizer_context.h
  src/optimizer/rules/rewrite_rules.cpp
Labels: bug, infrastructure, ready-for-ci, ready-to-merge

#1336 Make DataTable::accessor_ private
  src/include/storage/data_table.h
Labels: ready-for-ci, ready-to-merge

#1315 Improve format of query trace recording.
  src/include/metrics/metrics_store.h
  src/include/metrics/query_trace_metric.h
  src/include/parser/expression/constant_value_expression.h
  src/include/type/type_util.h
  src/parser/expression/constant_value_expression.cpp
  src/traffic_cop/traffic_cop.cpp
  test/metrics/metrics_test.cpp
Labels: beginner, ready-for-ci, ready-to-merge

#1326 Add support for SQL IN operator in WHERE clauses.
  script/testing/junit/traces/select.test
  src/execution/compiler/expression/comparison_translator.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
  src/parser/postgresparser.cpp
Labels: bug, feature, ready-for-ci, ready-to-merge

#1332 Add TOPK and VARCHAR OU; add model training for default and txn metrics data
  benchmark/runner/mini_runners.cpp
  benchmark/runner/tpch_runner.cpp
  benchmark/runner/transaction_logging_gc_runner.cpp
  script/model/data_class/data_util.py
  script/model/data_class/global_model_data.py
  script/model/data_class/grouped_op_unit_data.py
  script/model/data_class/opunit_data.py
  script/model/data_class/tpcc_fixer.py
  script/model/endtoend_estimator.py
  script/model/execution_engine_runner/generate_aggregate.py
  script/model/execution_engine_runner/generate_arithmetic.py
  script/model/execution_engine_runner/generate_hashjoin.py
  script/model/execution_engine_runner/generate_scan.py
  script/model/execution_engine_runner/generate_sort.py
  script/model/global_model_config.py
  script/model/global_trainer.py
  script/model/info/data_info.py
  script/model/info/query_info.py
  script/model/info/query_info_10G.py
  script/model/info/query_info_1G.py
  script/model/mini_trainer.py
  script/model/model.py
  script/model/training_util/data_transforming_util.py
  script/model/training_util/global_data_constructing_util.py
  script/model/type.py
  src/brain/brain_util.cpp
  src/brain/operating_unit_recorder.cpp
  src/brain/operating_unit_util.cpp
  src/execution/compiler/operator/sort_translator.cpp
  src/execution/exec/execution_context.cpp
  src/include/brain/brain_defs.h
  src/include/brain/operating_unit_recorder.h
  src/include/brain/operating_unit_util.h
  src/include/execution/exec/execution_settings.h
  src/include/main/db_main.h
  test/test_util/tpch/workload.cpp
  util/execution/table_generator/table_generator.cpp
  util/execution/tpl.cpp
  util/include/execution/table_generator/table_generator.h
  util/include/runner/mini_runners_argument_generator.h
  util/include/runner/mini_runners_data_config.h
  util/runner/mini_runners_argument_generator.cpp
Labels: ready-for-ci, ready-for-review

#1321 Add support for aliases in ORDER BY.
  script/testing/junit/sql/orderby.sql
  script/testing/junit/traces/orderby.test
  src/binder/bind_node_visitor.cpp
  src/include/parser/expression_util.h
Labels: ready-for-ci, ready-to-merge

#1299 Selectivity calculation using TopK and Histogram
  src/include/optimizer/statistics/new_column_stats.h
  src/include/optimizer/statistics/selectivity_util.h
  src/include/storage/storage_defs.h
  src/optimizer/statistics/new_column_stats.cpp
  src/optimizer/statistics/selectivity_util.cpp
  test/optimizer/selectivity_util_test.cpp
Labels: ready-for-ci, ready-to-merge

#1341 Refactor self-driving namespace and directories
  benchmark/runner/mini_runners.cpp
  src/brain/operating_unit_util.cpp
  src/execution/ast/context.cpp
  src/execution/ast/type.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/compilation_context.cpp
  src/execution/compiler/executable_query.cpp
  src/execution/compiler/operator/csv_scan_translator.cpp
  src/execution/compiler/operator/delete_translator.cpp
  src/execution/compiler/operator/hash_aggregation_translator.cpp
  src/execution/compiler/operator/hash_join_translator.cpp
  src/execution/compiler/operator/index_create_translator.cpp
  src/execution/compiler/operator/index_join_translator.cpp
  src/execution/compiler/operator/index_scan_translator.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/limit_translator.cpp
  src/execution/compiler/operator/nested_loop_join_translator.cpp
  src/execution/compiler/operator/operator_translator.cpp
  src/execution/compiler/operator/output_translator.cpp
  src/execution/compiler/operator/projection_translator.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
  src/execution/compiler/operator/sort_translator.cpp
  src/execution/compiler/operator/static_aggregation_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/execution/exec/execution_context.cpp
  src/execution/sql/sorter.cpp
  src/execution/vm/bytecode_handlers.cpp
  src/execution/vm/vm.cpp
  src/include/brain/brain_util.h
  src/include/common/dedicated_thread_registry.h
  src/include/execution/ast/type.h
  src/include/execution/compiler/codegen.h
  src/include/execution/compiler/executable_query.h
  src/include/execution/compiler/operator/hash_aggregation_translator.h
  src/include/execution/compiler/operator/hash_join_translator.h
  src/include/execution/compiler/operator/operator_translator.h
  src/include/execution/compiler/operator/sort_translator.h
  src/include/execution/compiler/operator/static_aggregation_translator.h
  src/include/execution/compiler/pipeline.h
  src/include/execution/exec/execution_context.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/metrics/bind_command_metric.h
  src/include/metrics/execute_command_metric.h
  src/include/metrics/metrics_store.h
  src/include/metrics/pipeline_metric.h
  src/include/self_driving/modeling/operating_unit.h
  src/include/self_driving/modeling/operating_unit_defs.h
  src/include/self_driving/modeling/operating_unit_recorder.h
  src/include/self_driving/modeling/operating_unit_util.h
  src/self_driving/modeling/operating_unit.cpp
  src/self_driving/modeling/operating_unit_recorder.cpp
  src/self_driving/modeling/operating_unit_util.cpp
  test/execution/compiler_test.cpp
  test/optimizer/index_nested_loops_join_test.cpp
  util/runner/mini_runners_argument_generator.cpp
Labels: ready-for-ci, ready-for-review

#1351 Fix SET parallel_execution which was not hooked up to execution.
  src/execution/exec/execution_settings.cpp
  src/include/common/constants.h
Labels: bug, ready-for-ci, ready-for-review

#1330 Artifact Stats
  .dockerignore
  Dockerfile
  Jenkinsfile
  Jenkinsfile-nightly
  build-support/check_github_labels.py
  script/installation/packages.sh
  script/testing/README.md
  script/testing/artifact_stats/README.md
  script/testing/artifact_stats/__init__.py
  script/testing/artifact_stats/base_artifact_stats_collector.py
  script/testing/artifact_stats/collectors/__init__.py
  script/testing/artifact_stats/collectors/compile_time.py
  script/testing/artifact_stats/collectors/memory_on_start.py
  script/testing/artifact_stats/run_artifact_stats.py
  script/testing/check_pids.py
  script/testing/collect_mem_info.py
  script/testing/junit/run_junit.py
  script/testing/junit/test_junit.py
  script/testing/junit/utils.py
  script/testing/microbench/config.py
  script/testing/oltpbench/constants.py
  script/testing/oltpbench/run_oltpbench.py
  script/testing/oltpbench/test_case_oltp.py
  script/testing/oltpbench/test_oltpbench.py
  script/testing/oltpbench/utils.py
  script/testing/reporting/parsers/parse_data.py
  script/testing/reporting/report_result.py
  script/testing/reporting/utils.py
  script/testing/util/constants.py
  script/testing/util/db_server.py
  script/testing/util/mem_metrics.py
  script/testing/util/periodic_task.py
  script/testing/util/test_case.py
  script/testing/util/test_server.py
Labels: ready-for-ci, ready-to-merge
