Repository cmu-db/noisepage, pull requests merged in 2020-08, with the labels that each got.

#1057 compiled_query_execution command line arg
  src/include/main/db_main.h
  src/include/settings/settings_defs.h
  src/include/traffic_cop/traffic_cop.h
  src/traffic_cop/traffic_cop.cpp
  test/network/network_test.cpp
Labels: ready-to-merge

#1051 Forward declare (operator and expression) translators, fix TPL AstPrettyPrint for array length.
  src/execution/ast/ast_pretty_print.cpp
  src/execution/compiler/compilation_context.cpp
  src/execution/compiler/expression/arithmetic_translator.cpp
  src/execution/compiler/expression/column_value_translator.cpp
  src/execution/compiler/expression/comparison_translator.cpp
  src/execution/compiler/expression/conjunction_translator.cpp
  src/execution/compiler/expression/constant_translator.cpp
  src/execution/compiler/expression/derived_value_translator.cpp
  src/execution/compiler/expression/null_check_translator.cpp
  src/execution/compiler/expression/unary_translator.cpp
  src/execution/compiler/operator/delete_translator.cpp
  src/execution/compiler/operator/hash_aggregation_translator.cpp
  src/execution/compiler/operator/index_scan_translator.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/execution/compiler/work_context.cpp
  src/execution/sql/join_hash_table_vector_probe.cpp
  src/execution/sql/sql.cpp
  src/execution/sql/table_vector_iterator.cpp
  src/execution/sql/vector_operations/arithmetic.cpp
  src/execution/sql/vector_operations/fill.cpp
  src/execution/sql/vector_operations/like.cpp
  src/include/execution/compiler/codegen.h
  src/include/execution/compiler/compilation_context.h
  src/include/execution/compiler/expression/arithmetic_translator.h
  src/include/execution/compiler/expression/column_value_translator.h
  src/include/execution/compiler/expression/comparison_translator.h
  src/include/execution/compiler/expression/conjunction_translator.h
  src/include/execution/compiler/expression/constant_translator.h
  src/include/execution/compiler/expression/derived_value_translator.h
  src/include/execution/compiler/expression/function_translator.h
  src/include/execution/compiler/expression/null_check_translator.h
  src/include/execution/compiler/expression/param_value_translator.h
  src/include/execution/compiler/expression/star_translator.h
  src/include/execution/compiler/expression/unary_translator.h
  src/include/execution/compiler/operator/csv_scan_translator.h
  src/include/execution/compiler/operator/delete_translator.h
  src/include/execution/compiler/operator/hash_aggregation_translator.h
  src/include/execution/compiler/operator/hash_join_translator.h
  src/include/execution/compiler/operator/index_join_translator.h
  src/include/execution/compiler/operator/index_scan_translator.h
  src/include/execution/compiler/operator/insert_translator.h
  src/include/execution/compiler/operator/limit_translator.h
  src/include/execution/compiler/operator/operator_translator.h
  src/include/execution/compiler/operator/output_translator.h
  src/include/execution/compiler/operator/seq_scan_translator.h
  src/include/execution/compiler/operator/sort_translator.h
  src/include/execution/compiler/operator/update_translator.h
  src/include/execution/compiler/work_context.h
  src/include/execution/exec/execution_context.h
  src/include/execution/sql/operators/cast_operators.h
  src/include/execution/sql/vector_operations/inplace_operation_executor.h
  src/include/execution/sql/vector_projection_iterator.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/planner/plannodes/index_join_plan_node.h
  src/include/storage/storage_defs.h
  test/execution/sql_vector_test.cpp
  test/execution/system_functions_test.cpp
  test/include/execution/sql_test.h
  test/optimizer/index_nested_loops_join_test.cpp
Labels: best-practice, ready-to-merge

#1056 Fix parallel codegen and parallel scan, force insert/update/delete to be serial.
  build-support/data/lsan_suppressions.txt
  sample_tpl/parallel-join.tpl
  sample_tpl/parallel-scan.tpl
  src/execution/compiler/codegen.cpp
  src/execution/compiler/operator/delete_translator.cpp
  src/execution/compiler/operator/index_join_translator.cpp
  src/execution/compiler/operator/index_scan_translator.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/projection_translator.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/execution/compiler/pipeline.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/table_vector_iterator.cpp
  src/include/brain/operating_unit.h
  src/include/common/constants.h
  src/include/execution/compiler/codegen.h
  src/include/execution/compiler/operator/delete_translator.h
  src/include/execution/compiler/operator/index_join_translator.h
  src/include/execution/compiler/operator/index_scan_translator.h
  src/include/execution/compiler/operator/insert_translator.h
  src/include/execution/compiler/operator/projection_translator.h
  src/include/execution/compiler/operator/update_translator.h
  src/include/execution/exec/execution_settings.h
  src/include/execution/sql/table_vector_iterator.h
  test/execution/compiler_test.cpp
  test/execution/sql_table_vector_iterator_test.cpp
Labels: bug, ready-to-merge

#1064 Fix for More Than Two Disjunction Predicate
  script/testing/junit/traces/select.test
  src/execution/compiler/expression/conjunction_translator.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
Labels: ready-for-review

#1055 VarlenEntry microbenchmark
  benchmark/storage/varlen_entry_benchmark.cpp
  script/micro_bench/run_micro_bench.py
Labels: ready-for-review, tests

#1060 Mini-Runners Update for TPLv2 Engine
  benchmark/runner/mini_runners.cpp
  script/model/data_class/grouped_op_unit_data.py
  script/model/data_class/opunit_data.py
  script/model/global_trainer.py
  script/model/info/data_info.py
  script/model/mini_trainer.py
  script/model/training_util/global_data_constructing_util.py
  script/model/type.py
  src/brain/operating_unit_recorder.cpp
  src/execution/compiler/executable_query.cpp
  src/execution/compiler/operator/hash_aggregation_translator.cpp
  src/execution/compiler/operator/static_aggregation_translator.cpp
  src/execution/compiler/pipeline.cpp
  src/execution/sql/aggregation_hash_table.cpp
  src/execution/sql/bloom_filter.cpp
  src/execution/sql/chaining_hash_table.cpp
  src/execution/sql/concise_hash_table.cpp
  src/execution/sql/join_hash_table.cpp
  src/execution/sql/memory_pool.cpp
  src/execution/vm/vm.cpp
  src/include/brain/operating_unit.h
  src/include/execution/compiler/executable_query.h
  src/include/execution/compiler/pipeline.h
  src/include/execution/exec/execution_settings.h
  src/include/execution/sql/chaining_hash_table.h
  src/include/execution/sql/concise_hash_table.h
  src/include/execution/util/memory.h
  src/include/metrics/pipeline_metric.h
  test/execution/compiler_test.cpp
  test/execution/sql_chaining_hash_table_test.cpp
  test/execution/sql_concise_hash_table_test.cpp
  test/optimizer/index_nested_loops_join_test.cpp
  util/execution/table_generator/table_generator.cpp
Labels: ready-to-merge

#1078 Hackathon hyperbolic trig functions
  script/testing/junit/traces/functions.test
  src/catalog/database_catalog.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_generator.cpp
  src/include/catalog/postgres/pg_proc.h
  src/include/execution/ast/builtins.h
Labels: ready-for-review

#1059 TPCH Port Over
  benchmark/runner/tpch_runner.cpp
  sample_tpl/date-functions.tpl
  sample_tpl/sql-date.tpl
  src/brain/brain_util.cpp
  src/catalog/database_catalog.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/catalog/postgres/pg_proc.h
  src/include/execution/ast/builtins.h
  src/include/execution/sql/sql_def.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/include/parser/expression/function_expression.h
  test/include/execution/compiler/expression_maker.h
  test/include/test_util/tpch/tpch_query.h
  test/include/test_util/tpch/workload.h
  test/test_util/tpch/tpch_query.cpp
  test/test_util/tpch/workload.cpp
Labels: ready-to-merge

#1081 Increase microbenchmark lax_tolerance from 30 to 50.
  script/micro_bench/run_micro_bench.py
Labels: best-practice, ready-to-merge

#1085 Fix AdaptiveCheckTest in sql_filter_manager_test.cpp
  test/execution/sql_filter_manager_test.cpp
Labels: bug, ready-to-merge

#1088 Standardize WAL Setting Parameter Names
  benchmark/storage/recovery_benchmark.cpp
  src/include/main/db_main.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/settings/settings_callbacks.cpp
  test/settings/settings_test.cpp
  test/storage/log_test.cpp
  test/storage/recovery_test.cpp
Labels: best-practice, ready-to-merge

#1073 Support for SET statements.
  src/include/common/error/exception.h
  src/include/main/db_main.h
  src/include/network/network_defs.h
  src/include/network/network_util.h
  src/include/parser/expression/constant_value_expression.h
  src/include/parser/variable_set_statement.h
  src/include/settings/settings_common.h
  src/include/settings/settings_defs.h
  src/include/settings/settings_manager.h
  src/include/traffic_cop/traffic_cop.h
  src/network/postgres/postgres_network_commands.cpp
  src/parser/expression/constant_value_expression.cpp
  src/parser/postgresparser.cpp
  src/settings/settings_manager.cpp
  src/traffic_cop/traffic_cop.cpp
  test/network/network_test.cpp
  test/settings/settings_test.cpp
Labels: feature, ready-to-merge

#1066 Fix VarlenEntry CompareEqualOrNot to ignore reclaim bit properly.
  src/include/storage/storage_defs.h
  test/storage/varlen_entry_test.cpp
Labels: bug, ready-to-merge

#1090 Hackathon math funcs
  script/testing/junit/traces/functions.test
  src/catalog/database_catalog.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_generator.cpp
  src/include/catalog/postgres/pg_proc.h
  src/include/execution/ast/builtins.h
  src/include/execution/sql/functions/arithmetic_functions.h
  test/execution/sql_functions_arithmetic_functions_test.cpp
Labels: feature, ready-for-review

#1097 MiniRunners Update/Delete + OURecorder fixes
  benchmark/runner/mini_runners.cpp
  script/model/data_class/grouped_op_unit_data.py
  script/model/data_class/tpcc_fixer.py
  script/model/global_trainer.py
  script/model/training_util/global_data_constructing_util.py
  src/brain/brain_util.cpp
  src/brain/operating_unit_recorder.cpp
  src/execution/compiler/operator/static_aggregation_translator.cpp
  src/include/brain/brain_defs.h
  src/include/brain/operating_unit_recorder.h
  src/include/brain/operating_unit_util.h
  test/execution/compiler_test.cpp
  util/execution/table_generator/table_generator.cpp
  util/include/execution/table_generator/table_generator.h
Labels: ready-to-merge

#1093 Star Schema Benmark Port over
  benchmark/runner/README.md
  benchmark/runner/tpch_runner.cpp
  test/include/execution/compiler/expression_maker.h
  test/include/test_util/ssb/star_schema_query.h
  test/include/test_util/tpch/tpch_query.h
  test/include/test_util/tpch/workload.h
  test/test_util/ssb/star_schema_query.cpp
  test/test_util/tpch/tpch_query.cpp
  test/test_util/tpch/workload.cpp
Labels: ready-to-merge

#1108 Modeling Updates
  script/model/data_class/grouped_op_unit_data.py
  script/model/data_class/opunit_data.py
  script/model/data_class/tpcc_fixer.py
  script/model/endtoend_estimator.py
  script/model/global_trainer.py
  script/model/info/query_info.py
  script/model/info/query_info_10G.py
  script/model/info/query_info_1G.py
  script/model/mini_trainer.py
  script/model/model.py
  script/model/training_util/data_transforming_util.py
  script/model/training_util/global_data_constructing_util.py
  src/brain/operating_unit_recorder.cpp
  src/execution/compiler/compilation_context.cpp
  src/include/brain/operating_unit_recorder.h
  src/include/execution/compiler/compilation_context.h
  src/include/execution/compiler/executable_query.h
  src/include/execution/compiler/pipeline.h
  src/include/metrics/logging_metric.h
  src/traffic_cop/traffic_cop.cpp
Labels: ready-to-merge

#1101 May 2020 Hackathon SQL String Functions 2
  script/testing/junit/traces/functions.test
  src/catalog/database_catalog.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/functions/string_functions.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/catalog/postgres/pg_proc.h
  src/include/execution/ast/builtins.h
  src/include/execution/sql/functions/string_functions.h
  src/include/execution/vm/bytecode_generator.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  test/execution/sql_functions_arithmetic_functions_test.cpp
  test/execution/sql_functions_string_functions_test.cpp
Labels: feature, ready-to-merge

#1121 Address check-clang-tidy issues on master
  benchmark/runner/mini_runners.cpp
  test/execution/parsing_scanner_test.cpp
  test/execution/sql_sorter_test.cpp
  test/execution/sql_thread_state_container_test.cpp
  test/execution/util_chunked_vector_test.cpp
Labels: best-practice, bug, ready-for-review

#1103 Remove strong typedef operator
  src/binder/bind_node_visitor.cpp
  src/brain/operating_unit_recorder.cpp
  src/catalog/database_catalog.cpp
  src/execution/compiler/codegen.cpp
  src/execution/compiler/operator/csv_scan_translator.cpp
  src/execution/compiler/operator/delete_translator.cpp
  src/execution/compiler/operator/index_join_translator.cpp
  src/execution/compiler/operator/index_scan_translator.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/execution/compiler/pipeline.cpp
  src/include/catalog/catalog_cache.h
  src/include/common/strong_typedef.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/metrics/pipeline_metric.h
  src/include/optimizer/binding.h
  src/include/optimizer/memo.h
  src/include/storage/arrow_block_metadata.h
  src/include/storage/block_layout.h
  src/include/storage/index/compact_ints_key.h
  src/include/storage/index/generic_key.h
  src/include/storage/tuple_access_strategy.h
  src/include/transaction/transaction_util.h
  src/optimizer/binding.cpp
  src/optimizer/group.cpp
  src/optimizer/optimizer.cpp
  src/optimizer/optimizer_task.cpp
  src/planner/plannodes/drop_view_plan_node.cpp
  src/storage/arrow_serializer.cpp
  src/storage/block_compactor.cpp
  src/storage/garbage_collector.cpp
  src/storage/recovery/recovery_manager.cpp
  src/traffic_cop/traffic_cop.cpp
  test/execution/index_iterator_test.cpp
  test/execution/sql_table_vector_iterator_test.cpp
  test/execution/storage_interface_test.cpp
  test/include/test_util/storage_test_util.h
  test/storage/data_table_test.cpp
  test/storage/export_table_test.cpp
  test/storage/index_key_test.cpp
  test/storage/storage_util_test.cpp
  test/traffic_cop/traffic_cop_test.cpp
Labels: best-practice, ready-to-merge

#1123 Templated perf monitor and benchmark
  benchmark/CMakeLists.txt
  benchmark/common/CMakeLists.txt
  benchmark/common/perf_monitor_benchmark.cpp
  src/include/common/perf_monitor.h
  src/include/common/resource_tracker.h
  test/common/perf_monitor_test.cpp
Labels: best-practice, ready-to-merge

#1114 May 2020 Hackathon SQL Math and String Functions
  script/testing/junit/src/moglib/MogDb.java
  script/testing/junit/traces/functions.test
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/functions/string_functions.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/catalog/catalog_accessor.h
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/pg_proc.h
  src/include/execution/ast/builtins.h
  src/include/execution/sql/functions/arithmetic_functions.h
  src/include/execution/sql/functions/string_functions.h
  src/include/execution/sql/operators/numeric_operators.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  test/execution/sql_functions_arithmetic_functions_test.cpp
  test/execution/sql_functions_string_functions_test.cpp
  test/execution/vm_bytecodes_test.cpp
Labels: feature, ready-to-merge

#1126 Add support for single-threaded CREATE INDEX.
  src/execution/compiler/compilation_context.cpp
  src/execution/compiler/operator/index_create_translator.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sql/storage_interface.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/bytecode_handlers.cpp
  src/execution/vm/vm.cpp
  src/include/brain/brain_defs.h
  src/include/execution/ast/builtins.h
  src/include/execution/compiler/operator/index_create_translator.h
  src/include/execution/sql/storage_interface.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/network/postgres/postgres_network_commands.cpp
  src/optimizer/plan_generator.cpp
  src/traffic_cop/traffic_cop.cpp
  test/execution/index_create_test.cpp
  test/optimizer/index_nested_loops_join_test.cpp
  util/execution/table_generator/table_generator.cpp
  util/include/execution/table_generator/table_generator.h
Labels: feature, ready-to-merge

#1118 May 2020 Hackathon RTRIM, LTRIM, RPAD, LPAD Functions
  script/testing/junit/traces/functions.test
  src/catalog/database_catalog.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/sema/sema_checking.cpp
  src/execution/sql/functions/string_functions.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/catalog/postgres/pg_proc.h
  src/include/execution/ast/builtins.h
  src/include/execution/sema/error_message.h
  src/include/execution/sema/sema.h
  src/include/execution/sql/functions/string_functions.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  test/execution/sql_functions_string_functions_test.cpp
Labels: feature, ready-to-merge
