Repository cmu-db/noisepage, pull requests merged in 2020-03, with the labels that each got.

#758 Support default value expressions, out-of-order inserts
  script/testing/junit/InsertTest.java
  src/binder/bind_node_visitor.cpp
Labels: ready-to-merge

#762 Fix Bugs found with TPCC
  sample_tpl/distinct-agg.tpl
  sample_tpl/sort-limit.tpl
  sample_tpl/static-agg.tpl
  sample_tpl/tpl_tests.txt
  src/binder/bind_node_visitor.cpp
  src/execution/compiler/expression/tuple_value_translator.cpp
  src/execution/compiler/operator/aggregate_translator.cpp
  src/execution/compiler/operator/aggregate_util.cpp
  src/execution/compiler/operator/limit_translator.cpp
  src/execution/compiler/operator/sort_translator.cpp
  src/execution/compiler/operator/static_aggregate_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/execution/compiler/translator_factory.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_generator.cpp
  src/include/brain/brain_defs.h
  src/include/brain/operating_unit.h
  src/include/execution/ast/builtins.h
  src/include/execution/compiler/expression/tuple_value_translator.h
  src/include/execution/compiler/operator/aggregate_translator.h
  src/include/execution/compiler/operator/aggregate_util.h
  src/include/execution/compiler/operator/index_scan_translator.h
  src/include/execution/compiler/operator/limit_translator.h
  src/include/execution/compiler/operator/operator_translator.h
  src/include/execution/compiler/operator/seq_scan_translator.h
  src/include/execution/compiler/operator/sort_translator.h
  src/include/execution/compiler/operator/static_aggregate_translator.h
  src/include/execution/compiler/operator/update_translator.h
  src/include/execution/sema/sema.h
  src/include/execution/vm/bytecodes.h
  src/include/parser/update_statement.h
  src/optimizer/plan_generator.cpp
  src/optimizer/query_to_operator_transformer.cpp
  test/execution/compiler_test.cpp
  test/include/execution/compiler/expression_util.h
  test/include/execution/compiler/output_schema_util.h
Labels: ready-for-review

#810 Fix select junit test
  script/testing/junit/SelectTest.java
Labels: ready-for-review

#805 Fix NULL regression, add simple test for inserting a single NULL int.
  script/testing/junit/InsertTest.java
  src/binder/bind_node_visitor.cpp
Labels: ready-for-review

#816 Fix compiler_test by removing outdated assert after #762.
  src/include/planner/plannodes/order_by_plan_node.h
Labels: bug, ready-to-merge

#815 Disable Broken Tests / Microbenchmarks
  script/micro_bench/run_micro_bench.py
  script/testing/junit/.gitignore
  script/testing/junit/README.md
  script/testing/junit/Readme.txt
  script/testing/junit/build.xml
  script/testing/junit/src/InsertTest.java
  script/testing/junit/src/SelectTest.java
  script/testing/junit/src/TPCCBootstrapTest.java
  script/testing/junit/src/TestUtility.java
  test/execution/filter_manager_test.cpp
  test/integration/tpcc_test.cpp
Labels: ready-for-review, tests

#820 ASAN Leak Fix for ThreadContainerStateTest
  test/execution/thread_state_container_test.cpp
Labels: ready-for-review

#826 Cast SQL Integers to Reals for arithmetic operations.
  script/testing/junit/src/InsertTest.java
  script/testing/junit/src/SelectTest.java
  script/testing/junit/src/TestUtility.java
  src/execution/ast/ast_dump.cpp
  src/execution/sema/sema_checking.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/ast.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
Labels: bug, ready-to-merge

#825 Binder logic to convert mismatched types in update statements.
  script/testing/junit/src/UpdateTest.java
  src/binder/bind_node_visitor.cpp
  test/optimizer/tpcc_plan_delivery_test.cpp
  test/optimizer/tpcc_plan_neworder_test.cpp
  test/optimizer/tpcc_plan_payment_test.cpp
Labels: bug, ready-to-merge

#823 Fix Having Clause (#793)
  script/testing/junit/src/SelectTest.java
  src/optimizer/rules/implementation_rules.cpp
  src/parser/postgresparser.cpp
Labels: bug, ready-to-merge

#827 bwtree_index_test: fix potential bad access in results vector
  test/storage/bwtree_index_test.cpp
Labels: bug, tests

#830 Enable ccache in Jenkins
  Jenkinsfile
  script/jenkins/benchmark-agent-setup.sh
  script/jenkins/docker-agent-setup.sh
Labels: infrastructure, ready-to-merge

#832 Fix Remaining Benchmarks To Support BenchmarkConfig
  benchmark/catalog/catalog_benchmark.cpp
  benchmark/metrics/garbage_collection_metrics_benchmark.cpp
  benchmark/metrics/large_transaction_metrics_benchmark.cpp
  benchmark/metrics/logging_metrics_benchmark.cpp
  benchmark/storage/data_table_benchmark.cpp
  benchmark/storage/logging_benchmark.cpp
Labels: ready-for-review

#801 Return results for VARBINARY type
  src/execution/compiler/codegen.cpp
  src/include/network/postgres/postgres_packet_writer.h
Labels: ready-to-merge

#616 Dump Table
  cmake_modules/ThirdpartyToolchain.cmake
  script/installation/packages.sh
  src/include/storage/arrow_block_metadata.h
  src/include/storage/arrow_serializer.h
  src/include/storage/data_table.h
  src/include/storage/sql_table.h
  src/include/storage/storage_util.h
  src/storage/arrow_serializer.cpp
  src/storage/block_compactor.cpp
  src/storage/data_table.cpp
  src/storage/sql_table.cpp
  test/storage/block_compactor_test.cpp
  test/storage/export_table_test.cpp
  third_party/flatbuffers/base.h
  third_party/flatbuffers/flatbuffers.h
  third_party/flatbuffers/format/Message.fbs
  third_party/flatbuffers/format/Schema.fbs
  third_party/flatbuffers/generated/File_generated.h
  third_party/flatbuffers/generated/Message_generated.h
  third_party/flatbuffers/generated/Schema_generated.h
  third_party/flatbuffers/generated/SparseTensor_generated.h
  third_party/flatbuffers/generated/Tensor_generated.h
  third_party/flatbuffers/stl_emulation.h
Labels: ready-to-merge

#831 BinderSherpa
  sample_tpl/tpl_tests.txt
  sample_tpl/types/bigint.tpl
  script/testing/junit/src/InsertTest.java
  script/testing/junit/src/SelectTest.java
  src/binder/bind_node_visitor.cpp
  src/binder/binder_context.cpp
  src/binder/sql_node_visitor.cpp
  src/common/sql_node_visitor.cpp
  src/execution/vm/vm.cpp
  src/include/binder/bind_node_visitor.h
  src/include/binder/binder_context.h
  src/include/binder/binder_sherpa.h
  src/include/binder/binder_util.h
  src/include/binder/sql_node_visitor.h
  src/include/common/sql_node_visitor.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/optimizer/query_to_operator_transformer.h
  src/include/parser/analyze_statement.h
  src/include/parser/copy_statement.h
  src/include/parser/create_function_statement.h
  src/include/parser/create_statement.h
  src/include/parser/delete_statement.h
  src/include/parser/drop_statement.h
  src/include/parser/execute_statement.h
  src/include/parser/explain_statement.h
  src/include/parser/expression/abstract_expression.h
  src/include/parser/expression/aggregate_expression.h
  src/include/parser/expression/case_expression.h
  src/include/parser/expression/column_value_expression.h
  src/include/parser/expression/comparison_expression.h
  src/include/parser/expression/conjunction_expression.h
  src/include/parser/expression/constant_value_expression.h
  src/include/parser/expression/default_value_expression.h
  src/include/parser/expression/derived_value_expression.h
  src/include/parser/expression/function_expression.h
  src/include/parser/expression/operator_expression.h
  src/include/parser/expression/parameter_value_expression.h
  src/include/parser/expression/star_expression.h
  src/include/parser/expression/subquery_expression.h
  src/include/parser/expression/type_cast_expression.h
  src/include/parser/insert_statement.h
  src/include/parser/prepare_statement.h
  src/include/parser/select_statement.h
  src/include/parser/sql_statement.h
  src/include/parser/table_ref.h
  src/include/parser/transaction_statement.h
  src/include/parser/update_statement.h
  src/include/parser/variable_set_statement.h
  src/include/traffic_cop/traffic_cop_util.h
  src/optimizer/query_to_operator_transformer.cpp
  src/parser/postgresparser.cpp
  src/traffic_cop/traffic_cop.cpp
  src/traffic_cop/traffic_cop_util.cpp
  test/binder/binder_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/tpcc_plan_delivery_test.cpp
  test/optimizer/tpcc_plan_index_scan.cpp
  test/optimizer/tpcc_plan_seq_scan.cpp
  test/test_util/tpcc/tpcc_plan_test.cpp
Labels: ready-to-merge

#743 Analyze Operators + Plan Nodes
  src/include/optimizer/logical_operators.h
  src/include/optimizer/operator_visitor.h
  src/include/optimizer/optimizer_defs.h
  src/include/optimizer/physical_operators.h
  src/include/optimizer/plan_generator.h
  src/include/optimizer/rule.h
  src/include/optimizer/rules/implementation_rules.h
  src/include/parser/analyze_statement.h
  src/include/planner/plannodes/analyze_plan_node.h
  src/optimizer/logical_operators.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/rule.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/planner/plannodes/analyze_plan_node.cpp
  test/optimizer/operator_transformer_test.cpp
  test/planner/plan_node_json_test.cpp
  test/planner/plan_node_test.cpp
Labels: in-progress

#814 MiniRunners + OperatingUnits
  benchmark/runner/mini_runners.cpp
  src/brain/operating_unit_recorder.cpp
  src/execution/compiler/compiler.cpp
  src/execution/compiler/operator/static_aggregate_translator.cpp
  src/include/brain/brain_defs.h
  src/include/brain/brain_util.h
  src/include/brain/operating_unit.h
  src/include/brain/operating_unit_recorder.h
  src/include/brain/operating_unit_util.h
  src/include/execution/compiler/operator/static_aggregate_translator.h
  src/include/execution/exec/output.h
  src/include/execution/executable_query.h
  src/include/metrics/pipeline_metric.h
  src/include/optimizer/physical_operators.h
  src/include/planner/plannodes/nested_loop_join_plan_node.h
  src/include/storage/garbage_collector_thread.h
  src/include/traffic_cop/traffic_cop_util.h
  src/optimizer/input_column_deriver.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/planner/plannodes/nested_loop_join_plan_node.cpp
  src/traffic_cop/traffic_cop.cpp
  src/traffic_cop/traffic_cop_util.cpp
  test/execution/compiler_test.cpp
  test/optimizer/physical_operator_test.cpp
  test/optimizer/tpcc_plan_stocklevel_test.cpp
  util/execution/table_generator/table_generator.cpp
  util/include/execution/table_generator/table_generator.h
  util/include/optimizer/cost_model/forced_cost_model.h
Labels: ready-to-merge

#844 Modeling based on operating units
  benchmark/metrics/garbage_collection_metrics_benchmark.cpp
  benchmark/runner/tpcc_runner.cpp
  benchmark/runner/tpch_runner.cpp
  cmake_modules/BuildUtils.cmake
  sample_tpl/date-functions.tpl
  sample_tpl/tpl_tests.txt
  script/model/data_class/global_model_data.py
  script/model/data_class/grouped_op_unit_data.py
  script/model/data_class/opunit_data.py
  script/model/endtoend_estimator.py
  script/model/execution_engine_runner/generate_aggregate.py
  script/model/execution_engine_runner/generate_arithmetic.py
  script/model/execution_engine_runner/generate_hashjoin.py
  script/model/execution_engine_runner/generate_scan.py
  script/model/execution_engine_runner/generate_sort.py
  script/model/global_model_config.py
  script/model/global_trainer.py
  script/model/info/data_info.py
  script/model/info/hardware_info.py
  script/model/info/query_info.py
  script/model/mini_trainer.py
  script/model/model.py
  script/model/training_util/data_transforming_util.py
  script/model/training_util/global_data_constructing_util.py
  script/model/training_util/result_writing_util.py
  script/model/type.py
  script/model/util/io_util.py
  script/model/util/logging_util.py
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_generator.cpp
  src/execution/vm/vm.cpp
  src/include/execution/ast/builtins.h
  src/include/execution/sema/sema.h
  src/include/execution/vm/bytecode_generator.h
  src/include/execution/vm/bytecode_handlers.h
  src/include/execution/vm/bytecodes.h
  src/storage/data_table.cpp
  test/include/test_util/tpcc/workload_cached.h
  test/include/test_util/tpch/workload.h
  test/test_util/tpcc/workload_cached.cpp
  test/test_util/tpch/workload.cpp
  util/execution/table_generator/table_generator.cpp
  util/include/execution/table_generator/sample_output.h
Labels: ready-for-review

#833 Minor Fix for Junit Python Script
  script/testing/junit/run_junit.py
  script/testing/junit/src/InsertTest.java
  script/testing/junit/src/SelectTest.java
  script/testing/junit/src/TPCCBootstrapTest.java
  script/testing/junit/src/TestUtility.java
  script/testing/junit/src/UpdateTest.java
Labels: ready-for-review
