Repository cmu-db/noisepage, pull requests merged in 2021-03, with the labels that each got.

#1479 ModelServer Abstraction and Integration
  CMakeLists.txt
  Jenkinsfile
  Jenkinsfile-utils
  script/forecasting/__init__.py
  script/self_driving/.gitignore
  script/self_driving/endtoend_estimator.py
  script/self_driving/forecaster_standalone.py
  script/self_driving/forecasting/cluster.py
  script/self_driving/forecasting/data_loader.py
  script/self_driving/forecasting/forecaster.py
  script/self_driving/forecasting/models.py
  script/self_driving/global_trainer.py
  script/self_driving/mini_trainer.py
  script/self_driving/model/data_class/data_util.py
  script/self_driving/model/data_class/global_model_data.py
  script/self_driving/model/data_class/grouped_op_unit_data.py
  script/self_driving/model/data_class/opunit_data.py
  script/self_driving/model/global_model_config.py
  script/self_driving/model/info/data_info.py
  script/self_driving/model/info/hardware_info.py
  script/self_driving/model/model.py
  script/self_driving/model/training_util/data_transforming_util.py
  script/self_driving/model/training_util/global_data_constructing_util.py
  script/self_driving/model/training_util/result_writing_util.py
  script/self_driving/model/type.py
  script/self_driving/model/util/io_util.py
  script/self_driving/model/util/logging_util.py
  script/self_driving/model/util/result_writing_util.py
  script/self_driving/model_server.py
  src/include/main/db_main.h
  src/include/metrics/metrics_store.h
  src/include/metrics/query_trace_metric.h
  src/include/self_driving/forecast/workload_forecast.h
  src/include/self_driving/model_server/model_server_manager.h
  src/include/self_driving/pilot/pilot.h
  src/include/self_driving/pilot/pilot_thread.h
  src/include/settings/settings_defs.h
  src/self_driving/model_server/model_server_manager.cpp
  src/self_driving/pilot/pilot.cpp
  src/self_driving/pilot/pilot_thread.cpp
  src/self_driving/pilot_util.cpp
  src/traffic_cop/traffic_cop.cpp
  test/self_driving_e2e/model_server_test.cpp
Labels: ready-for-ci, ready-to-merge

#1505 Jenkins: Move microbenchmark building to pre-test and to any node. Add print_docker_info.sh.
  Jenkinsfile
  build-support/print_docker_info.sh
Labels: infrastructure, ready-for-ci

#1507 Add guide to getting debug symbols on clang.
  docs/dev_troubleshooting.md
Labels: best-practice, ready-for-review

#1513 Forward declare BPlusTree
  src/include/storage/index/bplustree_index.h
  src/storage/index/bplustree.cpp
  src/storage/index/bplustree_index.cpp
Labels: best-practice, performance, ready-for-ci, ready-to-merge

#1506 Replace BwTree with BPlusTree
  benchmark/catalog/catalog_benchmark.cpp
  benchmark/storage/index_wrapper_benchmark.cpp
  benchmark/storage/recovery_benchmark.cpp
  src/catalog/postgres/builder.cpp
  src/execution/sql/ddl_executors.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/parser/postgresparser.cpp
  test/catalog/catalog_test.cpp
  test/execution/ddl_executors_test.cpp
  test/execution/index_create_test.cpp
  test/include/test_util/storage_test_util.h
  test/integration/tpcc_test.cpp
  test/optimizer/logical_operator_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/physical_operator_test.cpp
  test/parser/parser_test.cpp
  test/storage/index_key_test.cpp
  test/storage/recovery_test.cpp
  test/test_util/tpcc/builder.cpp
  test/test_util/tpcc/tpcc_plan_test.cpp
  util/execution/table_generator/table_generator.cpp
  util/execution/table_generator/table_reader.cpp
Labels: ready-for-ci, ready-to-merge

#1514 fix Jenkinsfile-utils for self-driving e2e tests
  Jenkinsfile-utils
Labels: bug, infrastructure, ready-for-ci, ready-to-merge

#1509 Add code coverage report to self-driving components
  Jenkinsfile
  Jenkinsfile-utils
  build-support/run-test.sh
  script/installation/packages.sh
  script/self_driving/modeling/data/grouped_op_unit_data.py
  script/self_driving/modeling/data/opunit_data.py
  script/self_driving/modeling/info/data_info.py
  script/self_driving/modeling/ou_model_trainer.py
  script/self_driving/modeling/training_util/result_writing_util.py
  src/include/main/db_main.h
  src/include/self_driving/model_server/model_server_manager.h
  src/self_driving/model_server/model_server_manager.cpp
  test/self_driving_e2e/model_server_test.cpp
Labels: ready-for-ci, ready-for-review

#1516 Logging metrics sampling
  src/include/main/db_main.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/settings/settings_callbacks.cpp
Labels: in-progress, ready-for-ci

#1482 Fix storage interface, table vector iterator not being freed on abort.
  src/execution/compiler/codegen.cpp
  src/execution/compiler/operator/analyze_translator.cpp
  src/execution/compiler/operator/delete_translator.cpp
  src/execution/compiler/operator/index_scan_translator.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/execution/compiler/operator/seq_scan_translator.cpp
  src/execution/compiler/operator/update_translator.cpp
  src/include/execution/compiler/codegen.h
  src/include/execution/compiler/operator/analyze_translator.h
  src/include/execution/compiler/operator/delete_translator.h
  src/include/execution/compiler/operator/index_scan_translator.h
  src/include/execution/compiler/operator/insert_translator.h
  src/include/execution/compiler/operator/seq_scan_translator.h
  src/include/execution/compiler/operator/update_translator.h
Labels: bug, ready-for-ci, ready-for-review

#1517 Check for DBMS exit codes in CI's script.testing.junit.
  script/testing/junit/__main__.py
  script/testing/util/db_server.py
  script/testing/util/test_server.py
Labels: ready-for-ci, ready-for-review, tests

#1520 Upgrade fast float to major version
  CMakeLists.txt
Labels: best-practice, ready-for-ci, ready-to-merge

#1521 Increase record_buffer_segment_size in TPCC performance test to 1e7; increase default record_buffer_segment_size and block_store_size in settings_defs.h to 1e6
  script/testing/oltpbench/configs/end_to_end_performance/tpcc.json
  src/include/settings/settings_defs.h
  test/settings/settings_test.cpp
Labels: ready-for-ci

#1522 Jenkins: rearrange coverage tests to run on the more performant 'dgb' machine group
  Jenkinsfile
Labels: ready-for-ci

#1410 Add enum_defs and convert ExpressionType to be serialized to JSON as string.
  docs/cpp_guidelines_code_style.md
  src/execution/compiler/codegen.cpp
  src/execution/compiler/compilation_context.cpp
  src/execution/compiler/expression/arithmetic_translator.cpp
  src/execution/compiler/expression/comparison_translator.cpp
  src/execution/compiler/expression/conjunction_translator.cpp
  src/execution/compiler/expression/null_check_translator.cpp
  src/include/common/enum_defs.h
  src/include/parser/expression_defs.h
  src/optimizer/statistics/selectivity.cpp
  src/optimizer/statistics/selectivity_util.cpp
  src/parser/expression/abstract_expression.cpp
  src/parser/expression_defs.cpp
  test/parser/expression_defs_test.cpp
Labels: ready-for-ci, ready-to-merge

#1470 Run JUnit CI Tests with Compiled Query Execution
  Jenkinsfile
  build-support/tpl_bytecode_handlers_ir_compiler.py
  script/testing/README.md
  script/testing/meta/__init__.py
  script/testing/meta/util/__init__.py
  script/testing/meta/util/test_db_server.py
  script/testing/util/db_server.py
Labels: infrastructure, ready-for-ci, ready-to-merge, tests

#1527 fix broken import in binary size artifacts collection script
  script/testing/artifact_stats/collectors/binary_size.py
Labels: bug, infrastructure, ready-for-ci, ready-for-review

#1529 Fix Failing Nightly Performance Benchmarks + Prefix for Temp Files
  benchmark/benchmark_util/benchmark_config.cpp
  script/testing/junit/constants.py
  script/testing/microbench/constants.py
  script/testing/oltpbench/README.md
  script/testing/oltpbench/configs/end_to_end_debug/noop.json
  script/testing/oltpbench/configs/end_to_end_debug/smallbank.json
  script/testing/oltpbench/configs/end_to_end_debug/tatp.json
  script/testing/oltpbench/configs/end_to_end_debug/tatp_wal_disabled.json
  script/testing/oltpbench/configs/end_to_end_debug/tpcc.json
  script/testing/oltpbench/configs/end_to_end_debug/tpcc_parallel_disabled.json
  script/testing/oltpbench/configs/end_to_end_debug/ycsb.json
  script/testing/oltpbench/configs/end_to_end_performance/tatp.json
  script/testing/oltpbench/configs/end_to_end_performance/tatp_wal_disabled.json
  script/testing/oltpbench/configs/end_to_end_performance/tatp_wal_ramdisk.json
  script/testing/oltpbench/configs/end_to_end_performance/tpcc.json
  script/testing/oltpbench/configs/end_to_end_performance/tpcc_wal_disabled.json
  script/testing/oltpbench/configs/end_to_end_performance/tpcc_wal_ramdisk.json
  script/testing/oltpbench/configs/nightly/nightly.json
  script/testing/oltpbench/configs/nightly/nightly_ramdisk.json
  script/testing/oltpbench/configs/nightly/nightly_wal_disabled.json
  script/testing/util/common.py
  script/testing/util/constants.py
  src/execution/util/file.cpp
  test/execution/util_file_test.cpp
Labels: best-practice, bug, infrastructure, ready-for-ci
