Repository cmu-db/noisepage, pull requests merged in 2021-05, with the labels that each got.

#1572 Switch Replication Messages to Message Pack
  src/include/replication/replication_messages.h
  src/replication/replication_messages.cpp
Labels: performance, ready-for-ci, ready-for-review

#1573 Add explicit `u` suffix to initialize TrafficCopResult for EXPLAIN.
  src/traffic_cop/traffic_cop.cpp
Labels: best-practice, ready-for-ci, ready-for-review

#1561 Internal Query Execution Status (Issue #1555)
  src/include/task/task.h
  src/include/util/query_exec_util.h
  src/main/db_main.cpp
  src/self_driving/planning/pilot.cpp
  src/self_driving/planning/pilot_util.cpp
  src/task/task.cpp
  src/util/query_exec_util.cpp
  test/self_driving/query_trace_logging_test.cpp
  test/task/task_manager_test.cpp
Labels: ready-for-ci, ready-to-merge

#1574 Augmenting Pilot with Interference Model and OU Feature Generation from the Stats (instead of Executing Queries)
  Jenkinsfile-utils.groovy
  script/self_driving/forecasting/forecaster.py
  script/self_driving/forecasting/forecaster_standalone.py
  script/self_driving/modeling/interference_model_trainer.py
  script/testing/self_driving/forecast.py
  src/execution/compiler/compilation_context.cpp
  src/execution/compiler/executable_query.cpp
  src/include/execution/compiler/compilation_context.h
  src/include/execution/compiler/executable_query.h
  src/include/execution/exec/execution_settings.h
  src/include/execution/exec_defs.h
  src/include/main/db_main.h
  src/include/metrics/metrics_manager.h
  src/include/network/postgres/statement.h
  src/include/optimizer/group.h
  src/include/optimizer/index_util.h
  src/include/optimizer/statistics/histogram.h
  src/include/optimizer/statistics/stats_calculator.h
  src/include/optimizer/statistics/top_k_elements.h
  src/include/planner/plannodes/plan_meta_data.h
  src/include/self_driving/forecasting/workload_forecast.h
  src/include/self_driving/modeling/operating_unit.h
  src/include/self_driving/modeling/operating_unit_recorder.h
  src/include/self_driving/planning/mcts/monte_carlo_tree_search.h
  src/include/self_driving/planning/mcts/tree_node.h
  src/include/self_driving/planning/pilot.h
  src/include/self_driving/planning/pilot_util.h
  src/include/settings/settings_defs.h
  src/include/task/task.h
  src/include/util/query_exec_util.h
  src/optimizer/optimizer.cpp
  src/optimizer/statistics/selectivity_util.cpp
  src/optimizer/statistics/stats_calculator.cpp
  src/self_driving/forecasting/workload_forecast.cpp
  src/self_driving/modeling/operating_unit_recorder.cpp
  src/self_driving/planning/mcts/monte_carlo_tree_search.cpp
  src/self_driving/planning/mcts/tree_node.cpp
  src/self_driving/planning/pilot.cpp
  src/self_driving/planning/pilot_util.cpp
  src/task/task.cpp
  src/traffic_cop/traffic_cop.cpp
  src/util/query_exec_util.cpp
  test/optimizer/index_nested_loops_join_test.cpp
  test/self_driving/query_trace_logging_test.cpp
  test/sql/analyze_test.cpp
  test/task/task_manager_test.cpp
Labels: ready-for-ci, ready-to-merge

#1577 Refactor workload forecasting logic in Pilot to a separate Forecaster class
  src/include/self_driving/forecasting/forecaster.h
  src/include/self_driving/planning/pilot.h
  src/self_driving/forecasting/forecaster.cpp
  src/self_driving/planning/pilot.cpp
Labels: ready-for-ci, ready-for-review

#1578 Fix waiting for commit callbacks to be invoked by non-existent replicas.
  src/replication/primary_replication_manager.cpp
Labels: ready-for-ci

#1579 Monte Carlo Search Tree Fix: Varying action horizon for different levels
  src/include/self_driving/planning/mcts/monte_carlo_tree_search.h
  src/include/self_driving/planning/mcts/tree_node.h
  src/include/self_driving/planning/pilot.h
  src/self_driving/planning/mcts/monte_carlo_tree_search.cpp
  src/self_driving/planning/mcts/tree_node.cpp
Labels: ready-for-ci

#1567 Run check-clang-tidy-full on master build.
  CMakeLists.txt
  Jenkinsfile-utils.groovy
  build-support/run-clang-tidy.py
  build-support/run_clang_tidy_extra.py
  src/execution/sql/thread_state_container.cpp
Labels: ready-for-ci, ready-for-review

#1552 Log throughput Benchmark Scripts
  .gitignore
  script/testing/replication/log_throughput/__init__.py
  script/testing/replication/log_throughput/__main__.py
  script/testing/replication/log_throughput/constants.py
  script/testing/replication/log_throughput/log_scraper.py
  script/testing/replication/log_throughput/log_shipper.py
  script/testing/replication/log_throughput/log_sink.py
  script/testing/replication/log_throughput/log_throughput.py
  script/testing/replication/log_throughput/metrics_file_util.py
  script/testing/replication/log_throughput/node_server.py
  script/testing/replication/log_throughput/resources/replication.config
  script/testing/replication/log_throughput/test_type.py
  src/include/metrics/logging_metric.h
  src/include/metrics/metrics_store.h
  src/include/storage/recovery/recovery_manager.h
  src/storage/recovery/recovery_manager.cpp
Labels: performance, ready-for-ci, ready-for-review

#1580 Small fix to compile on Mac (note that we do not support Mac builds).
  src/optimizer/statistics/selectivity_util.cpp
Labels: ready-for-ci, ready-to-merge

#1575 Internal Table Actions Recording
  src/common/strong_typedef.cpp
  src/include/self_driving/planning/mcts/monte_carlo_tree_search.h
  src/include/self_driving/planning/mcts/tree_node.h
  src/include/self_driving/planning/pilot.h
  src/include/util/self_driving_recording_util.h
  src/main/startup.sql
  src/metrics/query_trace_metric.cpp
  src/self_driving/forecasting/forecaster.cpp
  src/self_driving/planning/mcts/monte_carlo_tree_search.cpp
  src/self_driving/planning/mcts/tree_node.cpp
  src/self_driving/planning/pilot.cpp
  src/util/self_driving_recording_util.cpp
Labels: ready-for-ci, ready-for-review

#1587 Update design_replication doc to compare with Postgres streaming replication.
  docs/design_replication.md
Labels: ready-for-review

#1586 Port TPL behavior for float literals. Change print behavior for REAL.
  script/testing/junit/traces/functions.test
  script/testing/junit/traces/select.test
  src/execution/vm/bytecode_generator.cpp
  src/network/postgres/postgres_packet_writer.cpp
Labels: bug, ready-for-ci, ready-for-review

#1584 Add memory constraint support for Pilot
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/catalog/postgres/pg_core_impl.cpp
  src/include/catalog/catalog.h
  src/include/catalog/catalog_accessor.h
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/pg_core_impl.h
  src/include/optimizer/logical_operators.h
  src/include/optimizer/statistics/stats_calculator.h
  src/include/self_driving/forecasting/workload_forecast.h
  src/include/self_driving/planning/action/abstract_action.h
  src/include/self_driving/planning/action/change_knob_action.h
  src/include/self_driving/planning/action/create_index_action.h
  src/include/self_driving/planning/action/drop_index_action.h
  src/include/self_driving/planning/mcts/action_state.h
  src/include/self_driving/planning/mcts/monte_carlo_tree_search.h
  src/include/self_driving/planning/mcts/tree_node.h
  src/include/self_driving/planning/memory_info.h
  src/include/self_driving/planning/pilot.h
  src/include/self_driving/planning/pilot_util.h
  src/include/self_driving/planning/planning_context.h
  src/include/util/query_exec_util.h
  src/optimizer/logical_operators.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/statistics/stats_calculator.cpp
  src/self_driving/forecasting/forecaster.cpp
  src/self_driving/forecasting/workload_forecast.cpp
  src/self_driving/planning/action/change_knob_action.cpp
  src/self_driving/planning/action/create_index_action.cpp
  src/self_driving/planning/action/drop_index_action.cpp
  src/self_driving/planning/action/generators/index_action_generator.cpp
  src/self_driving/planning/mcts/monte_carlo_tree_search.cpp
  src/self_driving/planning/mcts/tree_node.cpp
  src/self_driving/planning/pilot.cpp
  src/self_driving/planning/pilot_util.cpp
  src/self_driving/planning/planning_context.cpp
  src/util/query_exec_util.cpp
  src/util/self_driving_recording_util.cpp
  test/catalog/catalog_test.cpp
  test/optimizer/logical_operator_test.cpp
Labels: ready-for-ci, ready-for-review

#1589 Backend for EXPLAIN (FORMAT TPL) queries.
  src/execution/compiler/compilation_context.cpp
  src/execution/compiler/compiler.cpp
  src/execution/compiler/executable_query.cpp
  src/execution/compiler/executable_query_builder.cpp
  src/execution/vm/module.cpp
  src/include/execution/compiler/compilation_context.h
  src/include/execution/compiler/compiler.h
  src/include/execution/compiler/compiler_settings.h
  src/include/execution/compiler/executable_query.h
  src/include/execution/compiler/executable_query_builder.h
  src/include/execution/exec/execution_settings.h
  src/include/execution/vm/module.h
  src/include/execution/vm/module_metadata.h
  src/include/traffic_cop/traffic_cop.h
  src/network/postgres/postgres_network_commands.cpp
  src/traffic_cop/traffic_cop.cpp
  test/execution/atomics_test.cpp
  test/execution/compiler_test.cpp
  test/include/execution/vm/module_compiler.h
  util/execution/tpl.cpp
Labels: ready-for-ci, ready-to-merge

#1593 Add type-check to ManagedPointer::CastManagedPointerTo.
  benchmark/parser/parser_benchmark.cpp
  src/include/common/managed_pointer.h
  src/replication/replication_manager.cpp
  src/traffic_cop/traffic_cop.cpp
  src/util/query_exec_util.cpp
Labels: ready-to-merge

#1588 EXPLAIN (FORMAT TPL) and EXPLAIN (FORMAT TBC).
  src/include/parser/explain_statement.h
  src/network/postgres/postgres_network_commands.cpp
  src/parser/postgresparser.cpp
  src/traffic_cop/traffic_cop.cpp
Labels: feature, ready-for-ci, ready-for-review

#1596 Fix DurabilityPolicy::DISABLE configuration.
  src/include/transaction/transaction_context.h
  src/storage/record_buffer.cpp
  src/traffic_cop/traffic_cop.cpp
  src/transaction/transaction_manager.cpp
Labels: ready-for-ci, ready-for-review

#1581 Pilot Planning Baseline: Sequence Tuning for action selection
  src/include/self_driving/planning/pilot.h
  src/include/self_driving/planning/pilot_util.h
  src/include/self_driving/planning/seq_tuning/graph_solver.h
  src/include/self_driving/planning/seq_tuning/path_solution.h
  src/include/self_driving/planning/seq_tuning/seq_node.h
  src/include/self_driving/planning/seq_tuning/sequence_tuning.h
  src/include/settings/settings_defs.h
  src/self_driving/planning/mcts/monte_carlo_tree_search.cpp
  src/self_driving/planning/pilot.cpp
  src/self_driving/planning/pilot_util.cpp
  src/self_driving/planning/seq_tuning/graph_solver.cpp
  src/self_driving/planning/seq_tuning/sequence_tuning.cpp
Labels: ready-for-ci, ready-for-review
