Repository cmu-db/noisepage, pull requests merged in 2021-07, with the labels that each got.

#1621 Add ClearQueryCache setting
  benchmark/runner/execution_runners.cpp
  src/execution/compiler/compilation_context.cpp
  src/execution/compiler/executable_query.cpp
  src/include/execution/compiler/executable_query.h
  src/include/network/postgres/portal.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/include/traffic_cop/traffic_cop.h
  src/include/transaction/transaction_manager.h
  src/network/postgres/statement.cpp
  src/settings/settings_callbacks.cpp
  src/traffic_cop/traffic_cop.cpp
  test/test_util/tpcc/workload_cached.cpp
Labels: ready-for-ci, ready-to-merge

#1627 Add Validation to Column Constructor
  src/include/catalog/schema.h
Labels: bug, ready-for-ci, ready-to-merge

#1631 Refactor support for SHOW commands in DESCRIBE.
  src/include/traffic_cop/traffic_cop.h
  src/network/postgres/postgres_network_commands.cpp
  src/network/postgres/postgres_packet_util.cpp
  src/traffic_cop/traffic_cop.cpp
Labels: ready-for-ci, ready-for-review

#1620 Fix trace files that end in comments
  script/testing/junit/src/GenerateTrace.java
Labels: bug, ready-for-ci, ready-to-merge

#1633 disable unity build for modeling coverage.
  Jenkinsfile-utils.groovy
Labels: bug, infrastructure, ready-for-ci, ready-to-merge

#1635 Fix the conversion between SqlTypeId and string
  src/execution/sql/sql.cpp
Labels: ready-for-ci, ready-for-review

#1630 pg_proc cleanup
  script/testing/junit/traces/functions.test
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/catalog/postgres/pg_proc_impl.cpp
  src/common/strong_typedef.cpp
  src/include/catalog/catalog_accessor.h
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/pg_proc_impl.h
  src/include/execution/sql/sql.h
  test/catalog/catalog_test.cpp
Labels: best-practice, ready-for-ci

#1619 Unique table alias
  script/testing/junit/traces/nested_query.test
  src/binder/bind_node_visitor.cpp
  src/binder/binder_context.cpp
  src/binder/cte/dependency_graph.cpp
  src/binder/cte/lexical_scope.cpp
  src/binder/cte/structured_statement.cpp
  src/include/binder/bind_node_visitor.h
  src/include/binder/binder_context.h
  src/include/binder/binder_sherpa.h
  src/include/optimizer/abstract_optimizer_node_contents.h
  src/include/optimizer/group.h
  src/include/optimizer/index_util.h
  src/include/optimizer/input_column_deriver.h
  src/include/optimizer/logical_operators.h
  src/include/optimizer/optimizer_defs.h
  src/include/optimizer/physical_operators.h
  src/include/optimizer/query_to_operator_transformer.h
  src/include/optimizer/rules/unnesting_rules.h
  src/include/optimizer/util.h
  src/include/parser/expression/abstract_expression.h
  src/include/parser/expression/column_value_expression.h
  src/include/parser/expression_defs.h
  src/include/parser/postgresparser.h
  src/include/parser/table_ref.h
  src/optimizer/child_property_deriver.cpp
  src/optimizer/index_util.cpp
  src/optimizer/input_column_deriver.cpp
  src/optimizer/logical_operators.cpp
  src/optimizer/memo.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/optimizer/rules/rewrite_rules.cpp
  src/optimizer/rules/transformation_rules.cpp
  src/optimizer/rules/unnesting_rules.cpp
  src/optimizer/util.cpp
  src/parser/expression/abstract_expression.cpp
  src/parser/expression/column_value_expression.cpp
  src/parser/postgresparser.cpp
  src/parser/table_ref.cpp
  src/self_driving/planning/action/generators/index_action_generator.cpp
  test/binder/binder_test.cpp
  test/binder/cte_dependency_graph_test.cpp
  test/binder/cte_structured_statement_test.cpp
  test/optimizer/logical_operator_test.cpp
  test/optimizer/operator_transformer_test.cpp
  test/optimizer/optimizer_context_test.cpp
  test/optimizer/physical_operator_test.cpp
  test/optimizer/stats_calculator_test.cpp
  test/parser/expression_test.cpp
  test/parser/parser_test.cpp
  test/planner/plan_node_json_test.cpp
  test/planner/plan_node_test.cpp
Labels: feature, ready-for-ci, ready-to-merge
