Repository cmu-db/noisepage, pull requests merged in 2021-01, with the labels that each got.

#1425 Add a spin-until-initialized to messenger_test to avoid races.
  test/messenger/messenger_test.cpp
Labels: bug, ready-for-ci, ready-for-review

#1424 Remove terrier from issue template
  .github/ISSUE_TEMPLATE/noisepage-issue-template.md
Labels: ready-to-merge

#1420 Add event loop docs
  docs/discussion_event_loop.md
Labels: best-practice, ready-to-merge

#1407 Fix missing includes in model_server_manager header.
  src/include/self_driving/model_server/model_server_manager.h
Labels: best-practice, ready-for-ci

#1405 Fix correlated subquery optimizer rules
  script/testing/junit/traces/nested-query.test
  src/include/optimizer/rules/unnesting_rules.h
  src/optimizer/rules/rewrite_rules.cpp
  src/optimizer/rules/unnesting_rules.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1419 Increase the fake sleep in AdaptiveCheckTest.
  test/execution/sql_filter_manager_test.cpp
Labels: ready-for-review

#1428 CPU Frequency Modeling Augmentation
  script/model/info/data_info.py
  script/model/type.py
  src/include/execution/util/cpu_info.h
  src/include/metrics/metrics_util.h
  src/include/metrics/pipeline_metric.h
  test/self_driving/modeling_test.cpp
Labels: ready-for-ci, ready-for-review

#1376 Add step-by-step instruction to test runner infra code.
  script/testing/README.md
  script/testing/oltpbench/README.md
  script/testing/oltpbench/configs/README.md
  script/testing/util/test_server.py
Labels: ready-for-ci, ready-for-review

#1426 Self-Driving Index/Knob Actions
  CMakeLists.txt
  Jenkinsfile
  script/model/training_util/global_data_constructing_util.py
  src/include/optimizer/index_util.h
  src/include/optimizer/physical_operators.h
  src/include/planner/plannodes/index_scan_plan_node.h
  src/include/self_driving/pilot/action/abstract_action.h
  src/include/self_driving/pilot/action/action_defs.h
  src/include/self_driving/pilot/action/change_knob_action.h
  src/include/self_driving/pilot/action/change_knob_value_config.h
  src/include/self_driving/pilot/action/create_index_action.h
  src/include/self_driving/pilot/action/drop_index_action.h
  src/include/self_driving/pilot/action/generators/abstract_action_generator.h
  src/include/self_driving/pilot/action/generators/change_knob_action_generator.h
  src/include/self_driving/pilot/action/generators/index_action_generator.h
  src/include/self_driving/pilot/action/index_action_util.h
  src/include/self_driving/pilot/action/index_column.h
  src/include/settings/settings_manager.h
  src/include/settings/settings_param.h
  src/optimizer/index_util.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/planner/plannodes/index_scan_plan_node.cpp
  src/self_driving/pilot/action/abstract_action.cpp
  src/self_driving/pilot/action/change_knob_action.cpp
  src/self_driving/pilot/action/change_knob_value_config.cpp
  src/self_driving/pilot/action/generators/change_knob_action_generator.cpp
  src/self_driving/pilot/action/generators/index_action_generator.cpp
  test/include/execution/sql_test.h
  test/optimizer/physical_operator_test.cpp
  test/self_driving/generate_change_knob_action_test.cpp
  test/self_driving/generate_index_action_test.cpp
  test/self_driving_e2e/modeling_test.cpp
  util/execution/table_generator/table_generator.cpp
  util/include/execution/table_generator/table_generator.h
Labels: ready-for-ci, ready-for-review

#1436 Save and load data_info along with the mini models
  script/model/data_class/grouped_op_unit_data.py
  script/model/data_class/opunit_data.py
  script/model/endtoend_estimator.py
  script/model/global_trainer.py
  script/model/info/data_info.py
  script/model/mini_trainer.py
  script/model/model_server.py
  script/model/training_util/data_transforming_util.py
  script/model/training_util/global_data_constructing_util.py
  script/model/training_util/result_writing_util.py
  script/model/type.py
Labels: ready-for-ci, ready-for-review

#1437 Skip recording the un-modeled LIMIT operating unit
  script/model/data_class/grouped_op_unit_data.py
  src/include/self_driving/modeling/operating_unit_defs.h
  src/self_driving/modeling/operating_unit_recorder.cpp
Labels: ready-for-ci, ready-for-review

#1438 Add validation check for self-driving knob actions and add dynamic setting to wal_serialization_interval
  src/include/self_driving/pilot/action/abstract_action.h
  src/include/self_driving/pilot/action/change_knob_action.h
  src/include/self_driving/pilot/action/change_knob_value_config.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/include/settings/settings_param.h
  src/include/storage/write_ahead_log/log_manager.h
  src/include/storage/write_ahead_log/log_serializer_task.h
  src/self_driving/pilot/action/change_knob_action.cpp
  src/self_driving/pilot/action/change_knob_value_config.cpp
  src/self_driving/pilot/action/generators/change_knob_action_generator.cpp
  src/settings/settings_callbacks.cpp
  src/storage/write_ahead_log/log_manager.cpp
  test/self_driving/generate_change_knob_action_test.cpp
  test/settings/settings_test.cpp
Labels: ready-for-ci, ready-for-review

#1443 Add ptrace capabilities to all Docker containers.
  Jenkinsfile
Labels: infrastructure

#1442 Switch lightgbm to random forest in modeling_test
  src/self_driving/model_server/model_server_manager.cpp
  test/self_driving_e2e/modeling_test.cpp
Labels: ready-for-ci, ready-for-review

#1444 Replace dirty spinwaits with pthread cond waits in messenger test.
  test/messenger/messenger_test.cpp
Labels: bug, in-progress, ready-for-ci

#1441 Replace tbb::reader_writer_lock with std::shared_mutex.
  src/include/common/shared_latch.h
Labels: question/discussion, ready-for-ci, ready-to-merge

#1445 Additional AbstractAction Information
  src/include/self_driving/pilot/action/abstract_action.h
  src/include/self_driving/pilot/action/create_index_action.h
  src/include/self_driving/pilot/action/drop_index_action.h
  src/self_driving/pilot/action/change_knob_action.cpp
  src/self_driving/pilot/action/generators/change_knob_action_generator.cpp
  src/self_driving/pilot/action/generators/index_action_generator.cpp
  test/self_driving/generate_index_action_test.cpp
Labels: ready-for-ci

#1416 Add the framework for the pg_statistic table.
  src/catalog/database_catalog.cpp
  src/catalog/postgres/builder.cpp
  src/catalog/postgres/pg_statistic_impl.cpp
  src/include/catalog/database_catalog.h
  src/include/catalog/postgres/builder.h
  src/include/catalog/postgres/pg_statistic.h
  src/include/catalog/postgres/pg_statistic_impl.h
  src/include/storage/projected_row.h
  src/storage/recovery/recovery_manager.cpp
Labels: ready-for-ci, ready-to-merge

#1451 Fix default values of mismatched types
  script/testing/junit/traces/insert.test
  src/binder/bind_node_visitor.cpp
  src/include/catalog/schema.h
Labels: bug, ready-for-ci, ready-to-merge

#1447 DiskLogConsumerTask avoids calling Persist() if no data written
  src/storage/write_ahead_log/disk_log_consumer_task.cpp
Labels: performance, ready-for-ci, ready-for-review
