Repository cmu-db/noisepage, pull requests merged in 2021-04, with the labels that each got.

#1531 Add documentation for attaching to existing processes in CLion.
  docs/tech_clion.md
Labels: best-practice, ready-for-review

#1525 Add countdown latch to tcop commit callback.
  script/testing/replication/tests_simple.py
  src/include/storage/record_buffer.h
  src/include/storage/write_ahead_log/log_io.h
  src/include/storage/write_ahead_log/log_manager.h
  src/include/storage/write_ahead_log/log_serializer_task.h
  src/include/transaction/transaction_context.h
  src/include/transaction/transaction_defs.h
  src/storage/record_buffer.cpp
  src/storage/write_ahead_log/log_manager.cpp
  src/storage/write_ahead_log/log_serializer_task.cpp
  src/traffic_cop/traffic_cop.cpp
  src/transaction/transaction_manager.cpp
Labels: ready-for-ci, ready-to-merge

#1532 WAL async commit no longer generates CommitRecord for read-only txns
  src/transaction/transaction_manager.cpp
Labels: performance, ready-for-ci

#1538 Print startup message with std::cout.
  script/testing/util/db_server.py
  src/include/network/noisepage_server.h
  src/main/db_main.cpp
Labels: infrastructure, ready-for-ci, ready-for-review

#1542 Remove print statement from model_server's _parse_msg.
  script/self_driving/model_server.py
Labels: best-practice

#1543 Nightly Microbenchmark JSON Fixes
  script/testing/.gitignore
  script/testing/microbench/micro_benchmarks_runner.py
Labels: ready-for-ci, ready-to-merge, tests

#1530 Pilot Preparation Fix: Update query trace loading in WorkloadForecast
  src/self_driving/forecasting/workload_forecast.cpp
Labels: ready-for-ci

#1548 Delete WAL in tests if it is specified as a relative path
  script/testing/util/db_server.py
Labels: bug, ready-for-ci, ready-to-merge

#1545 Binder catches WHERE clause with incorrect return type
  script/testing/junit/traces/select.test
  src/binder/bind_node_visitor.cpp
  src/binder/binder_util.cpp
  src/include/binder/binder_util.h
  src/optimizer/statistics/stats_calculator.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1551 Rename port setting from Terrier to NoisePage
  src/include/settings/settings_defs.h
Labels: best-practice, ready-for-ci, ready-for-review

#1550 Add configurable timeout to run db script
  script/testing/util/db_server.py
Labels: feature, ready-for-ci, ready-for-review

#1557 Add -async_replication_enable command line arg.
  src/include/main/db_main.h
  src/include/settings/settings_defs.h
Labels: feature, ready-for-ci, ready-to-merge

#1553 Port LLVMEngine::Optimize to skip module passes.
  src/execution/vm/llvm_engine.cpp
Labels: ready-for-ci, ready-to-merge

#1540 Refactor Jenkinsfile scripts.
  CMakeLists.txt
  Jenkinsfile
  Jenkinsfile-nightly
  Jenkinsfile-utils
  Jenkinsfile-utils.groovy
Labels: ready-for-ci, ready-to-merge

#1563 Invoke ninja instead of ninja noisepage so that microbenchmarks are built.
  Jenkinsfile-utils.groovy
Labels: infrastructure

#1562 Allow sync durability with async replication
  src/include/transaction/transaction_context.h
Labels: ready-for-ci, ready-for-review

#1564 Update microbenchmark docs
  benchmark/README.md
  script/testing/microbench/README.md
  script/testing/microbench/benchmarks.py
Labels: ready-for-review

#1560 Fix task_manager_test (Issue #1556)
  src/util/query_exec_util.cpp
Labels: ready-for-ci, ready-to-merge

#1565 Abstract replication message format and serialization benchmark
  CMakeLists.txt
  benchmark/replication/replication_messages_benchmark.cpp
  script/testing/microbench/benchmarks.py
  src/include/replication/replication_messages.h
  src/replication/primary_replication_manager.cpp
  src/replication/replica_replication_manager.cpp
  src/replication/replication_manager.cpp
  src/replication/replication_messages.cpp
Labels: feature, performance, ready-for-ci, ready-to-merge

#1534 Move metrics enabled check for logging
  src/storage/write_ahead_log/disk_log_consumer_task.cpp
  src/storage/write_ahead_log/log_serializer_task.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1568 Refactor future.Wait() into future.WaitFor() and future.DangerousWait().
  src/include/common/future.h
  src/include/self_driving/model_server/model_server_manager.h
  src/include/self_driving/planning/pilot.h
  src/self_driving/model_server/model_server_manager.cpp
  src/self_driving/planning/pilot.cpp
  src/self_driving/planning/pilot_util.cpp
  test/self_driving/query_trace_logging_test.cpp
  test/self_driving_e2e/model_server_test.cpp
  test/task/task_manager_test.cpp
Labels: ready-for-ci, ready-for-review

#1234 SQL Explain
  script/testing/junit/traces/explain.test
  src/binder/bind_node_visitor.cpp
  src/include/network/network_defs.h
  src/include/network/postgres/postgres_packet_writer.h
  src/include/traffic_cop/traffic_cop.h
  src/network/postgres/postgres_network_commands.cpp
  src/network/postgres/postgres_packet_writer.cpp
  src/network/postgres/postgres_protocol_util.cpp
  src/traffic_cop/traffic_cop.cpp
  src/traffic_cop/traffic_cop_util.cpp
Labels: feature, ready-for-ci, ready-to-merge

#1571 Minor Catalog refactors
  src/catalog/catalog_accessor.cpp
  src/catalog/database_catalog.cpp
  src/catalog/postgres/pg_constraint_impl.cpp
  src/catalog/postgres/pg_core_impl.cpp
  src/catalog/postgres/pg_language_impl.cpp
  src/catalog/postgres/pg_proc_impl.cpp
  src/catalog/postgres/pg_statistic_impl.cpp
  src/include/catalog/database_catalog.h
  src/include/catalog/index_schema.h
Labels: best-practice, ready-for-ci, ready-to-merge
