Repository cmu-db/noisepage, pull requests merged in 2021-02, with the labels that each got.

#1456 Microbenchmark fix %change mistake
  script/installation/packages.sh
  script/testing/microbench/README.md
  script/testing/microbench/artifact_processor.py
  script/testing/microbench/micro_benchmarks_runner.py
Labels: ready-for-ci, ready-for-review

#1453 Add predict_ou_only option to GlobalTrainer
  script/model/endtoend_estimator.py
  script/model/global_trainer.py
  script/model/training_util/global_data_constructing_util.py
Labels: ready-for-review

#1446 Added wal_async_commit_enable setting, defaulted to false
  benchmark/benchmark_util/data_table_benchmark_util.cpp
  benchmark/integration/tpcc_benchmark.cpp
  benchmark/storage/block_compactor_benchmark.cpp
  benchmark/storage/index_wrapper_benchmark.cpp
  src/include/main/db_main.h
  src/include/settings/settings_defs.h
  src/include/transaction/transaction_manager.h
  src/transaction/transaction_manager.cpp
  test/network/network_test.cpp
  test/optimizer/logical_operator_test.cpp
  test/optimizer/optimizer_context_test.cpp
  test/optimizer/physical_operator_test.cpp
  test/storage/block_compactor_test.cpp
  test/storage/export_table_test.cpp
  test/traffic_cop/traffic_cop_test.cpp
Labels: performance, ready-for-ci, ready-for-review

#1457 Change metrics sample interval to a sample rate [0,100]
  Jenkinsfile
  benchmark/integration/tpcc_benchmark.cpp
  benchmark/metrics/garbage_collection_metrics_benchmark.cpp
  benchmark/metrics/large_transaction_metrics_benchmark.cpp
  benchmark/metrics/logging_metrics_benchmark.cpp
  benchmark/runner/mini_runners.cpp
  benchmark/runner/tpcc_runner.cpp
  benchmark/runner/tpch_runner.cpp
  benchmark/runner/transaction_logging_gc_runner.cpp
  src/include/main/db_main.h
  src/include/metrics/metrics_manager.h
  src/include/metrics/metrics_store.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/metrics/metrics_manager.cpp
  src/metrics/metrics_store.cpp
  src/self_driving/pilot/pilot.cpp
  src/settings/settings_callbacks.cpp
  test/integration/tpcc_test.cpp
  test/metrics/metrics_test.cpp
Labels: best-practice, ready-for-ci, ready-to-merge

#1459 Kill forked model server upon parent NoisePage process death.
  src/self_driving/model_server/model_server_manager.cpp
Labels: best-practice, ready-for-ci, ready-to-merge

#1458 Proper model caching in model server
  script/model/model_server.py
Labels: performance, ready-for-ci, ready-for-review

#1433 Monte Carlo Search Tree for action selection based on forecasted queries
  src/include/metrics/pipeline_metric.h
  src/include/self_driving/forecast/workload_forecast.h
  src/include/self_driving/forecast/workload_forecast_segment.h
  src/include/self_driving/modeling/operating_unit.h
  src/include/self_driving/pilot/mcts/monte_carlo_tree_search.h
  src/include/self_driving/pilot/mcts/tree_node.h
  src/include/self_driving/pilot/pilot.h
  src/include/self_driving/pilot_util.h
  src/self_driving/forecast/workload_forecast.cpp
  src/self_driving/forecast/workload_forecast_segment.cpp
  src/self_driving/pilot/mcts/monte_carlo_tree_search.cpp
  src/self_driving/pilot/mcts/tree_node.cpp
  src/self_driving/pilot/pilot.cpp
  src/self_driving/pilot_util.cpp
Labels: ready-for-ci, ready-for-review

#1429 Refactor scripts/testing.
  Jenkinsfile
  Jenkinsfile-nightly
  script/forecasting/__init__.py
  script/forecasting/cluster.py
  script/forecasting/data_loader.py
  script/forecasting/forecaster.py
  script/forecasting/models.py
  script/testing/README.md
  script/testing/__init__.py
  script/testing/artifact_stats/README.md
  script/testing/artifact_stats/__main__.py
  script/testing/artifact_stats/base_artifact_stats_collector.py
  script/testing/artifact_stats/collectors/__init__.py
  script/testing/artifact_stats/collectors/binary_size.py
  script/testing/artifact_stats/collectors/compile_time.py
  script/testing/artifact_stats/collectors/memory_on_start.py
  script/testing/artifact_stats/run_artifact_stats.py
  script/testing/check_pids.py
  script/testing/collect_mem_info.py
  script/testing/junit/__main__.py
  script/testing/junit/constants.py
  script/testing/junit/run_junit.py
  script/testing/junit/test_case_junit.py
  script/testing/junit/test_junit.py
  script/testing/junit/utils.py
  script/testing/kill_server.py
  script/testing/microbench/__main__.py
  script/testing/microbench/artifact_processor.py
  script/testing/microbench/benchmarks.py
  script/testing/microbench/config.py
  script/testing/microbench/google_benchmark/gbench2junit.py
  script/testing/microbench/google_benchmark/gbench_run_result.py
  script/testing/microbench/jenkins/jenkins.py
  script/testing/microbench/micro_benchmarks_runner.py
  script/testing/microbench/results_output.py
  script/testing/oltpbench/__main__.py
  script/testing/oltpbench/constants.py
  script/testing/oltpbench/run_oltpbench.py
  script/testing/oltpbench/test_case_oltp.py
  script/testing/oltpbench/test_oltpbench.py
  script/testing/oltpbench/utils.py
  script/testing/reporting/constants.py
  script/testing/reporting/parsers/oltpbench/config_parser.py
  script/testing/reporting/parsers/oltpbench/res_parser.py
  script/testing/reporting/parsers/oltpbench/summary_parser.py
  script/testing/reporting/parsers/parse_data.py
  script/testing/reporting/report_result.py
  script/testing/reporting/utils.py
  script/testing/self_driving/constants.py
  script/testing/self_driving/forecast.py
  script/testing/util/common.py
  script/testing/util/constants.py
  script/testing/util/db_server.py
  script/testing/util/mem_metrics.py
  script/testing/util/periodic_task.py
  script/testing/util/test_case.py
  script/testing/util/test_server.py
Labels: infrastructure, ready-for-ci, ready-to-merge, tests

#1466 Fix missing artifact stats import.
  script/testing/artifact_stats/base_artifact_stats_collector.py
Labels: infrastructure

#1455 Refactor LLVM Engine with Configurable Bytecode Handlers Path
  CMakeLists.txt
  benchmark/runner/tpcc_runner.cpp
  benchmark/runner/tpch_runner.cpp
  build-support/generate-bitcodes.sh
  src/execution/vm/llvm_engine.cpp
  src/include/execution/execution_util.h
  src/include/execution/vm/llvm_engine.h
  src/include/main/db_main.h
  src/include/settings/settings_defs.h
  src/main/db_main.cpp
  test/execution/atomics_test.cpp
  test/execution/sql_codegen_csv_scan_translator_test.cpp
  test/include/execution/compiled_tpl_test.h
  test/include/test_util/fs_util.h
  test/test_util/fs_util.cpp
  util/execution/tpl.cpp
Labels: feature, infrastructure, ready-for-ci

#1468 Fix nightly oltpbenchmark and microbenchmark builds.
  Jenkinsfile-nightly
  script/testing/util/db_server.py
Labels: infrastructure

#1462 Throw a binder exception for invalid date strings.
  src/binder/binder_util.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1474 Hotfix for CI Builds.
  CMakeLists.txt
  build-support/generate-bitcodes.sh
Labels: bug, infrastructure, ready-for-ci, ready-for-review

#1461 Fix memory leak associated with aggregators
  src/execution/compiler/codegen.cpp
  src/execution/compiler/operator/hash_aggregation_translator.cpp
  src/execution/compiler/operator/static_aggregation_translator.cpp
  src/execution/sema/sema_builtin.cpp
  src/execution/vm/bytecode_generator.cpp
  src/include/execution/ast/builtins.h
  src/include/execution/compiler/codegen.h
  src/include/execution/compiler/operator/hash_aggregation_translator.h
  src/include/execution/compiler/operator/static_aggregation_translator.h
  src/include/parser/expression/aggregate_expression.h
  src/include/planner/plannodes/aggregate_plan_node.h
  src/parser/expression/aggregate_expression.cpp
  src/planner/plannodes/aggregate_plan_node.cpp
  test/parser/expression_test.cpp
  test/planner/plan_node_test.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1473 Favor std::mutex over SpinLatch for OutputWriter synchronization.
  src/execution/exec/output.cpp
  src/include/execution/exec/output.h
Labels: best-practice, performance, ready-for-ci, ready-to-merge

#1477 Delete domain socket on DBMS shutdown. Clarify junit tracefile reporting.
  script/testing/junit/__main__.py
  script/testing/junit/src/TracefileTest.java
  script/testing/util/db_server.py
  script/testing/util/test_server.py
Labels: infrastructure, ready-for-ci, ready-to-merge

#1480 Reorder Jenkinsfile tests to run faster flakier tests first.
  Jenkinsfile
Labels: infrastructure

#1486 Add ninja job pools to limit link parallelism.
  CMakeLists.txt
Labels: infrastructure, ready-for-ci, ready-for-review

#1475 Create/Drop Index Action Fix and Costing Adjustment for Pilot
  script/model/training_util/data_transforming_util.py
  src/include/self_driving/pilot/action/create_index_action.h
  src/include/self_driving/pilot/mcts/monte_carlo_tree_search.h
  src/include/self_driving/pilot/mcts/tree_node.h
  src/include/self_driving/pilot/pilot.h
  src/include/self_driving/pilot_util.h
  src/include/settings/settings_defs.h
  src/self_driving/model_server/model_server_manager.cpp
  src/self_driving/pilot/mcts/monte_carlo_tree_search.cpp
  src/self_driving/pilot/mcts/tree_node.cpp
  src/self_driving/pilot/pilot.cpp
  src/self_driving/pilot_util.cpp
  test/self_driving/generate_index_action_test.cpp
Labels: ready-for-ci, ready-for-review

#1494 Increase db_server start time from 60s to 600s.
  script/testing/util/db_server.py
Labels: infrastructure, ready-for-ci, ready-to-merge

#1495 Log DB server output in all runs.
  script/testing/util/db_server.py
Labels: infrastructure, ready-for-ci, ready-for-review

#1383 Concurrent B+ Tree
  benchmark/storage/bplustree_benchmark.cpp
  src/include/parser/parser_defs.h
  src/include/storage/data_table.h
  src/include/storage/index/bplustree.h
  src/include/storage/index/bplustree_index.h
  src/include/storage/index/index_builder.h
  src/include/storage/index/index_defs.h
  src/optimizer/rules/implementation_rules.cpp
  src/parser/postgresparser.cpp
  src/storage/index/bplustree.cpp
  src/storage/index/bplustree_index.cpp
  src/storage/index/index_builder.cpp
  test/storage/bplustree_index_test.cpp
  test/storage/bplustree_test.cpp
Labels: feature, ready-for-ci, ready-to-merge

#1498 Fix NOISEPAGE_USE_LOGGING=OFF compilation
  src/self_driving/pilot/mcts/monte_carlo_tree_search.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1499 Switch gcc/Debug/Coverage/unittest to only use h0.
  Jenkinsfile
Labels: infrastructure, ready-for-ci

#1454 Add support for INSERT INTO SELECT statement
  script/testing/junit/traces/insert.test
  src/binder/bind_node_visitor.cpp
  src/execution/compiler/operator/insert_translator.cpp
  src/include/binder/bind_node_visitor.h
  src/include/execution/compiler/operator/insert_translator.h
  src/include/optimizer/logical_operators.h
  src/include/optimizer/physical_operators.h
  src/include/optimizer/query_to_operator_transformer.h
  src/include/planner/plannodes/insert_plan_node.h
  src/include/traffic_cop/traffic_cop_util.h
  src/optimizer/input_column_deriver.cpp
  src/optimizer/logical_operators.cpp
  src/optimizer/physical_operators.cpp
  src/optimizer/plan_generator.cpp
  src/optimizer/query_to_operator_transformer.cpp
  src/optimizer/rules/implementation_rules.cpp
  src/planner/plannodes/insert_plan_node.cpp
  src/traffic_cop/traffic_cop_util.cpp
  test/execution/compiler_test.cpp
  test/optimizer/logical_operator_test.cpp
  test/optimizer/physical_operator_test.cpp
Labels: feature, ready-for-ci, ready-to-merge

#1496 Fix bplustree.h redefined constant shared with bwtree.h.
  src/include/storage/index/bplustree.h
Labels: best-practice, ready-for-ci

#1478 Fix Directory Walk Race in Unit Tests
  CMakeLists.txt
  benchmark/runner/tpcc_runner.cpp
  benchmark/runner/tpch_runner.cpp
  test/include/execution/compiled_tpl_test.h
  test/include/test_util/fs_util.h
  test/test_util/fs_util.cpp
Labels: bug, ready-for-ci, ready-to-merge

#1487 Update packages.sh script (drop mac support, split Python into test/build, cleanup).
  script/installation/packages.sh
Labels: infrastructure, ready-for-ci, ready-for-review

#1501 Fix for BPlusTree test failures
  script/testing/microbench/benchmarks.py
  src/include/storage/index/bplustree.h
Labels: bug, ready-for-ci
