Repository cmu-db/noisepage, pull requests merged in 2021-06, with the labels that each got.

#1591 Add support for arbitrary SHOW. Add "set log_level_blah".
  src/include/loggers/loggers_util.h
  src/include/main/db_main.h
  src/include/metrics/metrics_util.h
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/include/settings/settings_manager.h
  src/include/settings/settings_param.h
  src/loggers/loggers_util.cpp
  src/settings/settings_callbacks.cpp
  src/traffic_cop/traffic_cop.cpp
Labels: feature, ready-for-ci, ready-to-merge

#1608 Unify pilot namespace
  src/include/catalog/catalog.h
  src/include/execution/compiler/executable_query.h
  src/include/execution/exec/execution_settings.h
  src/include/main/db_main.h
  src/include/metrics/pipeline_metric.h
  src/include/self_driving/forecasting/workload_forecast.h
  src/include/self_driving/planning/mcts/monte_carlo_tree_search.h
  src/include/self_driving/planning/mcts/tree_node.h
  src/include/self_driving/planning/pilot.h
  src/include/self_driving/planning/pilot_thread.h
  src/include/self_driving/planning/pilot_util.h
  src/self_driving/planning/pilot.cpp
  src/self_driving/planning/pilot_thread.cpp
  src/self_driving/planning/pilot_util.cpp
Labels: ready-for-ci

#1599 Small fixes to explain json and tpl for chbenchmark q2.
  src/planner/plannodes/abstract_join_plan_node.cpp
  src/self_driving/modeling/operating_unit_recorder.cpp
Labels: ready-for-ci, ready-to-merge

#1609 Enable changing the compiled_query_execution setting at runtime
  src/include/settings/settings_callbacks.h
  src/include/settings/settings_defs.h
  src/include/traffic_cop/traffic_cop.h
  src/settings/settings_callbacks.cpp
Labels: ready-for-ci, ready-to-merge

#1611 Add PYTHONPATH to tests in CMake. Ignore cmake-build-relwithdebinfo. Verbose self-driving tests.
  .gitignore
  CMakeLists.txt
Labels: ready-for-ci, ready-for-review

#1615 Clone oltpbench with depth 1.
  script/testing/oltpbench/constants.py
Labels: ready-for-ci, tests

#1617 Flush pending writes on connection close
  src/network/connection_handle.cpp
Labels: ready-to-merge

#1616 Execution Engine Design Document
  docs/design_execution.md
Labels: feature, question/discussion, ready-to-merge

#1614 Cache pilot cost computation and account for action duration and interference
  script/self_driving/model_server.py
  src/include/self_driving/forecasting/workload_forecast.h
  src/include/self_driving/planning/inference_results.h
  src/include/self_driving/planning/mcts/action_state.h
  src/include/self_driving/planning/mcts/monte_carlo_tree_search.h
  src/include/self_driving/planning/mcts/tree_node.h
  src/include/self_driving/planning/pilot_util.h
  src/include/self_driving/planning/planning_context.h
  src/include/self_driving/planning/seq_tuning/graph_solver.h
  src/include/self_driving/planning/seq_tuning/sequence_tuning.h
  src/include/settings/settings_defs.h
  src/self_driving/planning/mcts/monte_carlo_tree_search.cpp
  src/self_driving/planning/mcts/tree_node.cpp
  src/self_driving/planning/pilot.cpp
  src/self_driving/planning/pilot_util.cpp
  src/self_driving/planning/seq_tuning/graph_solver.cpp
  src/self_driving/planning/seq_tuning/sequence_tuning.cpp
Labels: ready-for-ci, ready-for-review
